/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_CooperateIndication_H_
#define	_CooperateIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CooperateIndication {
	CooperateIndication_leftChangeAllow	= 0,
	CooperateIndication_leftChangeForbid	= 1,
	CooperateIndication_rightChangeAllow	= 2,
	CooperateIndication_rightChangeForbid	= 3,
	CooperateIndication_rampInAllow	= 4,
	CooperateIndication_rampInForbid	= 5,
	CooperateIndication_isntEV	= 6,
	CooperateIndication_laneClear	= 7,
	CooperateIndication_laneIsntClear	= 8,
	CooperateIndication_laneReserve	= 9,
	CooperateIndication_laneAcquire	= 10,
	CooperateIndication_requestFaild	= 11
} e_CooperateIndication;

/* CooperateIndication */
typedef long	 CooperateIndication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CooperateIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CooperateIndication;
extern const asn_INTEGER_specifics_t asn_SPC_CooperateIndication_specs_1;
asn_struct_free_f CooperateIndication_free;
asn_struct_print_f CooperateIndication_print;
asn_constr_check_f CooperateIndication_constraint;
ber_type_decoder_f CooperateIndication_decode_ber;
der_type_encoder_f CooperateIndication_encode_der;
xer_type_decoder_f CooperateIndication_decode_xer;
xer_type_encoder_f CooperateIndication_encode_xer;
oer_type_decoder_f CooperateIndication_decode_oer;
oer_type_encoder_f CooperateIndication_encode_oer;
per_type_decoder_f CooperateIndication_decode_uper;
per_type_encoder_f CooperateIndication_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CooperateIndication_H_ */
#include <asn_internal.h>
