/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "CooperateIndication.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_CooperateIndication_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_CooperateIndication_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_CooperateIndication_value2enum_1[] = {
	{ 0,	15,	"leftChangeAllow" },
	{ 1,	16,	"leftChangeForbid" },
	{ 2,	16,	"rightChangeAllow" },
	{ 3,	17,	"rightChangeForbid" },
	{ 4,	11,	"rampInAllow" },
	{ 5,	12,	"rampInForbid" },
	{ 6,	6,	"isntEV" },
	{ 7,	9,	"laneClear" },
	{ 8,	13,	"laneIsntClear" },
	{ 9,	11,	"laneReserve" },
	{ 10,	11,	"laneAcquire" },
	{ 11,	12,	"requestFaild" }
};
static const unsigned int asn_MAP_CooperateIndication_enum2value_1[] = {
	6,	/* isntEV(6) */
	10,	/* laneAcquire(10) */
	7,	/* laneClear(7) */
	8,	/* laneIsntClear(8) */
	9,	/* laneReserve(9) */
	0,	/* leftChangeAllow(0) */
	1,	/* leftChangeForbid(1) */
	4,	/* rampInAllow(4) */
	5,	/* rampInForbid(5) */
	11,	/* requestFaild(11) */
	2,	/* rightChangeAllow(2) */
	3	/* rightChangeForbid(3) */
};
const asn_INTEGER_specifics_t asn_SPC_CooperateIndication_specs_1 = {
	asn_MAP_CooperateIndication_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_CooperateIndication_enum2value_1,	/* N => "tag"; sorted by N */
	12,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_CooperateIndication_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_CooperateIndication = {
	"CooperateIndication",
	"CooperateIndication",
	&asn_OP_NativeEnumerated,
	asn_DEF_CooperateIndication_tags_1,
	sizeof(asn_DEF_CooperateIndication_tags_1)
		/sizeof(asn_DEF_CooperateIndication_tags_1[0]), /* 1 */
	asn_DEF_CooperateIndication_tags_1,	/* Same as above */
	sizeof(asn_DEF_CooperateIndication_tags_1)
		/sizeof(asn_DEF_CooperateIndication_tags_1[0]), /* 1 */
	{ &asn_OER_type_CooperateIndication_constr_1, &asn_PER_type_CooperateIndication_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_CooperateIndication_specs_1	/* Additional specs */
};

