/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "HLW.h"

asn_TYPE_member_t asn_MBR_HLW_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HLW, warnState),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WarnState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"warnState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HLW, eventType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HLW, eventSource),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventSource,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventSource"
		},
};
static const ber_tlv_tag_t asn_DEF_HLW_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HLW_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* warnState */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eventType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* eventSource */
};
asn_SEQUENCE_specifics_t asn_SPC_HLW_specs_1 = {
	sizeof(struct HLW),
	offsetof(struct HLW, _asn_ctx),
	asn_MAP_HLW_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_HLW = {
	"HLW",
	"HLW",
	&asn_OP_SEQUENCE,
	asn_DEF_HLW_tags_1,
	sizeof(asn_DEF_HLW_tags_1)
		/sizeof(asn_DEF_HLW_tags_1[0]), /* 1 */
	asn_DEF_HLW_tags_1,	/* Same as above */
	sizeof(asn_DEF_HLW_tags_1)
		/sizeof(asn_DEF_HLW_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_HLW_1,
	3,	/* Elements count */
	&asn_SPC_HLW_specs_1	/* Additional specs */
};

