/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "OBUMessageFrame.h"

static asn_oer_constraints_t asn_OER_type_OBUMessageFrame_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_OBUMessageFrame_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  13 }	/* (0..13,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_OBUMessageFrame_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.loginFrame),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Login,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"loginFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.ackFrame),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ACK,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ackFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.localFrame),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"localFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.v2vwFrame),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_V2VW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2vwFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.glosaFrame),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GLOSA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"glosaFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.slwFrame),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SLW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"slwFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.vrucwFrame),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VRUCW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vrucwFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.hlwFrame),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HLW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hlwFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.ivsFrame),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IVS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ivsFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.rlvwFrame),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RLVW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlvwFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.tjwFrame),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TJW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tjwFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.virqFrame),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VIRQ,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"virqFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.rscpFrame),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSCP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rscpFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OBUMessageFrame, choice.vstatFrame),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VSTAT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vstatFrame"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_OBUMessageFrame_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* loginFrame */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ackFrame */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* localFrame */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* v2vwFrame */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* glosaFrame */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* slwFrame */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* vrucwFrame */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* hlwFrame */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ivsFrame */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* rlvwFrame */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* tjwFrame */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* virqFrame */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* rscpFrame */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* vstatFrame */
};
static asn_CHOICE_specifics_t asn_SPC_OBUMessageFrame_specs_1 = {
	sizeof(struct OBUMessageFrame),
	offsetof(struct OBUMessageFrame, _asn_ctx),
	offsetof(struct OBUMessageFrame, present),
	sizeof(((struct OBUMessageFrame *)0)->present),
	asn_MAP_OBUMessageFrame_tag2el_1,
	14,	/* Count of tags in the map */
	0, 0,
	14	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_OBUMessageFrame = {
	"OBUMessageFrame",
	"OBUMessageFrame",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_OBUMessageFrame_constr_1, &asn_PER_type_OBUMessageFrame_constr_1, CHOICE_constraint },
	asn_MBR_OBUMessageFrame_1,
	14,	/* Elements count */
	&asn_SPC_OBUMessageFrame_specs_1	/* Additional specs */
};

