/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_OBUMessageFrame_H_
#define	_OBUMessageFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Login.h"
#include "ACK.h"
#include "LocalInfo.h"
#include "V2VW.h"
#include "GLOSA.h"
#include "SLW.h"
#include "VRUCW.h"
#include "HLW.h"
#include "IVS.h"
#include "RLVW.h"
#include "TJW.h"
#include "VIRQ.h"
#include "RSCP.h"
#include "VSTAT.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OBUMessageFrame_PR {
	OBUMessageFrame_PR_NOTHING,	/* No components present */
	OBUMessageFrame_PR_loginFrame,
	OBUMessageFrame_PR_ackFrame,
	OBUMessageFrame_PR_localFrame,
	OBUMessageFrame_PR_v2vwFrame,
	OBUMessageFrame_PR_glosaFrame,
	OBUMessageFrame_PR_slwFrame,
	OBUMessageFrame_PR_vrucwFrame,
	OBUMessageFrame_PR_hlwFrame,
	OBUMessageFrame_PR_ivsFrame,
	OBUMessageFrame_PR_rlvwFrame,
	OBUMessageFrame_PR_tjwFrame,
	OBUMessageFrame_PR_virqFrame,
	OBUMessageFrame_PR_rscpFrame,
	OBUMessageFrame_PR_vstatFrame
	/* Extensions may appear below */
	
} OBUMessageFrame_PR;

/* OBUMessageFrame */
typedef struct OBUMessageFrame {
	OBUMessageFrame_PR present;
	union OBUMessageFrame_u {
		Login_t	 loginFrame;
		ACK_t	 ackFrame;
		LocalInfo_t	 localFrame;
		V2VW_t	 v2vwFrame;
		GLOSA_t	 glosaFrame;
		SLW_t	 slwFrame;
		VRUCW_t	 vrucwFrame;
		HLW_t	 hlwFrame;
		IVS_t	 ivsFrame;
		RLVW_t	 rlvwFrame;
		TJW_t	 tjwFrame;
		VIRQ_t	 virqFrame;
		RSCP_t	 rscpFrame;
		VSTAT_t	 vstatFrame;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OBUMessageFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OBUMessageFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _OBUMessageFrame_H_ */
#include <asn_internal.h>
