/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_OBUMessageFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_Login;
extern struct asn_TYPE_descriptor_s asn_DEF_ACK;
extern struct asn_TYPE_descriptor_s asn_DEF_LocalInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_RemoteInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_V2VW;
extern struct asn_TYPE_descriptor_s asn_DEF_GLOSA;
extern struct asn_TYPE_descriptor_s asn_DEF_VRUCW;
extern struct asn_TYPE_descriptor_s asn_DEF_SLW;
extern struct asn_TYPE_descriptor_s asn_DEF_HLW;
extern struct asn_TYPE_descriptor_s asn_DEF_IVS;
extern struct asn_TYPE_descriptor_s asn_DEF_RLVW;
extern struct asn_TYPE_descriptor_s asn_DEF_TJW;
extern struct asn_TYPE_descriptor_s asn_DEF_VIRQ;
extern struct asn_TYPE_descriptor_s asn_DEF_RSCP;
extern struct asn_TYPE_descriptor_s asn_DEF_VSTAT;
extern struct asn_TYPE_descriptor_s asn_DEF_ErrorCode;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSize;
extern struct asn_TYPE_descriptor_s asn_DEF_WarnType;
extern struct asn_TYPE_descriptor_s asn_DEF_WarnState;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleType;
extern struct asn_TYPE_descriptor_s asn_DEF_Direction;
extern struct asn_TYPE_descriptor_s asn_DEF_TJLevel;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedAdvice;
extern struct asn_TYPE_descriptor_s asn_DEF_BehaviorType;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestState;
extern struct asn_TYPE_descriptor_s asn_DEF_CooperateIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_LightState;
extern struct asn_TYPE_descriptor_s asn_DEF_EventSource;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleEvent;
extern struct asn_TYPE_descriptor_s asn_DEF_DSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_Distance;
extern struct asn_TYPE_descriptor_s asn_DEF_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_Speed;
extern struct asn_TYPE_descriptor_s asn_DEF_Heading;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleHeight;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeMark;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneID;
extern struct asn_TYPE_descriptor_s asn_DEF_EventType;
extern struct asn_TYPE_descriptor_s asn_DEF_SignType;
extern struct asn_TYPE_descriptor_s asn_DEF_TextUTF8;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module OBU in asn/OBU.asn */
	&asn_DEF_OBUMessageFrame,	
	&asn_DEF_Login,	
	&asn_DEF_ACK,	
	&asn_DEF_LocalInfo,	
	&asn_DEF_RemoteInfo,	
	&asn_DEF_ParticipantInfo,	
	&asn_DEF_V2VW,	
	&asn_DEF_GLOSA,	
	&asn_DEF_VRUCW,	
	&asn_DEF_SLW,	
	&asn_DEF_HLW,	
	&asn_DEF_IVS,	
	&asn_DEF_RLVW,	
	&asn_DEF_TJW,	
	&asn_DEF_VIRQ,	
	&asn_DEF_RSCP,	
	&asn_DEF_VSTAT,	
	&asn_DEF_ErrorCode,	
	&asn_DEF_Position3D,	
	&asn_DEF_VehicleSize,	
	&asn_DEF_WarnType,	
	&asn_DEF_WarnState,	
	&asn_DEF_VehicleType,	
	&asn_DEF_Direction,	
	&asn_DEF_TJLevel,	
	&asn_DEF_SpeedAdvice,	
	&asn_DEF_BehaviorType,	
	&asn_DEF_RequestState,	
	&asn_DEF_CooperateIndication,	
	&asn_DEF_LightState,	
	&asn_DEF_EventSource,	
	&asn_DEF_VehicleEvent,	
	&asn_DEF_DSecond,	
	&asn_DEF_Distance,	
	&asn_DEF_Latitude,	
	&asn_DEF_Longitude,	
	&asn_DEF_Elevation,	
	&asn_DEF_Speed,	
	&asn_DEF_Heading,	
	&asn_DEF_VehicleHeight,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleWidth,	
	&asn_DEF_TimeMark,	
	&asn_DEF_LaneID,	
	&asn_DEF_EventType,	
	&asn_DEF_SignType,	
	&asn_DEF_TextUTF8,	
	0
};

