/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RequestState_H_
#define	_RequestState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestState {
	RequestState_off	= 0,
	RequestState_on	= 1
} e_RequestState;

/* RequestState */
typedef long	 RequestState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RequestState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RequestState;
extern const asn_INTEGER_specifics_t asn_SPC_RequestState_specs_1;
asn_struct_free_f RequestState_free;
asn_struct_print_f RequestState_print;
asn_constr_check_f RequestState_constraint;
ber_type_decoder_f RequestState_decode_ber;
der_type_encoder_f RequestState_encode_der;
xer_type_decoder_f RequestState_decode_xer;
xer_type_encoder_f RequestState_encode_xer;
oer_type_decoder_f RequestState_decode_oer;
oer_type_encoder_f RequestState_encode_oer;
per_type_decoder_f RequestState_decode_uper;
per_type_encoder_f RequestState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestState_H_ */
#include <asn_internal.h>
