/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RLVW_H_
#define	_RLVW_H_


#include <asn_application.h>

/* Including external dependencies */
#include "WarnState.h"
#include "SpeedAdvice.h"
#include "LightState.h"
#include "TimeMark.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RLVW */
typedef struct RLVW {
	WarnState_t	 warnState;
	SpeedAdvice_t	 speedadvice;
	LightState_t	 light;
	TimeMark_t	 timeCountDown;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLVW_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLVW;
extern asn_SEQUENCE_specifics_t asn_SPC_RLVW_specs_1;
extern asn_TYPE_member_t asn_MBR_RLVW_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RLVW_H_ */
#include <asn_internal.h>
