/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "RSCP.h"

asn_TYPE_member_t asn_MBR_RSCP_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RSCP, coopIndict),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CooperateIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"coopIndict"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSCP, laneId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSCP, coopToast),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TextUTF8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"coopToast"
		},
};
static const ber_tlv_tag_t asn_DEF_RSCP_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RSCP_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* coopIndict */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* laneId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* coopToast */
};
asn_SEQUENCE_specifics_t asn_SPC_RSCP_specs_1 = {
	sizeof(struct RSCP),
	offsetof(struct RSCP, _asn_ctx),
	asn_MAP_RSCP_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RSCP = {
	"RSCP",
	"RSCP",
	&asn_OP_SEQUENCE,
	asn_DEF_RSCP_tags_1,
	sizeof(asn_DEF_RSCP_tags_1)
		/sizeof(asn_DEF_RSCP_tags_1[0]), /* 1 */
	asn_DEF_RSCP_tags_1,	/* Same as above */
	sizeof(asn_DEF_RSCP_tags_1)
		/sizeof(asn_DEF_RSCP_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RSCP_1,
	3,	/* Elements count */
	&asn_SPC_RSCP_specs_1	/* Additional specs */
};

