/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RSCP_H_
#define	_RSCP_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CooperateIndication.h"
#include "LaneID.h"
#include "TextUTF8.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSCP */
typedef struct RSCP {
	CooperateIndication_t	 coopIndict;
	LaneID_t	 laneId;
	TextUTF8_t	 coopToast;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RSCP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSCP;
extern asn_SEQUENCE_specifics_t asn_SPC_RSCP_specs_1;
extern asn_TYPE_member_t asn_MBR_RSCP_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RSCP_H_ */
#include <asn_internal.h>
