/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_SpeedAdvice_H_
#define	_SpeedAdvice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpeedAdvice {
	SpeedAdvice_null	= 0,
	SpeedAdvice_keep	= 1,
	SpeedAdvice_slamTheBrakes	= 2,
	SpeedAdvice_slowDownStop	= 3,
	SpeedAdvice_fastAcceleration	= 4,
	SpeedAdvice_acceleration	= 5,
	SpeedAdvice_fastDeceleration	= 6,
	SpeedAdvice_deceleration	= 7,
	SpeedAdvice_speeding	= 8,
	SpeedAdvice_belowLimit	= 9,
	SpeedAdvice_farAway	= 16,
	SpeedAdvice_danger	= 17
} e_SpeedAdvice;

/* SpeedAdvice */
typedef long	 SpeedAdvice_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SpeedAdvice_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SpeedAdvice;
extern const asn_INTEGER_specifics_t asn_SPC_SpeedAdvice_specs_1;
asn_struct_free_f SpeedAdvice_free;
asn_struct_print_f SpeedAdvice_print;
asn_constr_check_f SpeedAdvice_constraint;
ber_type_decoder_f SpeedAdvice_decode_ber;
der_type_encoder_f SpeedAdvice_encode_der;
xer_type_decoder_f SpeedAdvice_decode_xer;
xer_type_encoder_f SpeedAdvice_encode_xer;
oer_type_decoder_f SpeedAdvice_decode_oer;
oer_type_encoder_f SpeedAdvice_encode_oer;
per_type_decoder_f SpeedAdvice_decode_uper;
per_type_encoder_f SpeedAdvice_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedAdvice_H_ */
#include <asn_internal.h>
