/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_V2VW_H_
#define	_V2VW_H_


#include <asn_application.h>

/* Including external dependencies */
#include "WarnType.h"
#include "WarnState.h"
#include "Distance.h"
#include "Direction.h"
#include "RemoteInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* V2VW */
typedef struct V2VW {
	WarnType_t	 warnType;
	WarnState_t	 warnState;
	Distance_t	 distance;
	Direction_t	 direction;
	RemoteInfo_t	 remoteInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2VW_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2VW;
extern asn_SEQUENCE_specifics_t asn_SPC_V2VW_specs_1;
extern asn_TYPE_member_t asn_MBR_V2VW_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _V2VW_H_ */
#include <asn_internal.h>
