/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "V2VW.h"

asn_TYPE_member_t asn_MBR_V2VW_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct V2VW, warnType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WarnType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"warnType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2VW, warnState),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WarnState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"warnState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2VW, distance),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Distance,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"distance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2VW, direction),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Direction,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"direction"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2VW, remoteInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RemoteInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"remoteInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_V2VW_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_V2VW_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* warnType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* warnState */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* distance */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* direction */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* remoteInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_V2VW_specs_1 = {
	sizeof(struct V2VW),
	offsetof(struct V2VW, _asn_ctx),
	asn_MAP_V2VW_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_V2VW = {
	"V2VW",
	"V2VW",
	&asn_OP_SEQUENCE,
	asn_DEF_V2VW_tags_1,
	sizeof(asn_DEF_V2VW_tags_1)
		/sizeof(asn_DEF_V2VW_tags_1[0]), /* 1 */
	asn_DEF_V2VW_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2VW_tags_1)
		/sizeof(asn_DEF_V2VW_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_V2VW_1,
	5,	/* Elements count */
	&asn_SPC_V2VW_specs_1	/* Additional specs */
};

