/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_VehicleEvent_H_
#define	_VehicleEvent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleEvent {
	VehicleEvent_none	= 0,
	VehicleEvent_hazardLights	= 1,
	VehicleEvent_stopLineViolation	= 2,
	VehicleEvent_absActivated	= 3,
	VehicleEvent_tractionControlLoss	= 4,
	VehicleEvent_stabilityControlactivated	= 5,
	VehicleEvent_hazardousMaterials	= 6,
	VehicleEvent_hardBraking	= 7,
	VehicleEvent_lightChanged	= 8,
	VehicleEvent_wipersChanged	= 9,
	VehicleEvent_flatTire	= 10,
	VehicleEvent_disabledVehicle	= 11,
	VehicleEvent_airBagDeployment	= 12
} e_VehicleEvent;

/* VehicleEvent */
typedef BIT_STRING_t	 VehicleEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleEvent;
asn_struct_free_f VehicleEvent_free;
asn_struct_print_f VehicleEvent_print;
asn_constr_check_f VehicleEvent_constraint;
ber_type_decoder_f VehicleEvent_decode_ber;
der_type_encoder_f VehicleEvent_encode_der;
xer_type_decoder_f VehicleEvent_decode_xer;
xer_type_encoder_f VehicleEvent_encode_xer;
oer_type_decoder_f VehicleEvent_decode_oer;
oer_type_encoder_f VehicleEvent_encode_oer;
per_type_decoder_f VehicleEvent_decode_uper;
per_type_encoder_f VehicleEvent_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleEvent_H_ */
#include <asn_internal.h>
