/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_VSTAT_H_
#define	_VSTAT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VSTAT__lights {
	VSTAT__lights_lowBeamHeadlightsOn	= 0,
	VSTAT__lights_highBeamHeadlightsOn	= 1,
	VSTAT__lights_leftTurnSignalOn	= 2,
	VSTAT__lights_rightTurnSignalOn	= 3,
	VSTAT__lights_hazardSignalOn	= 4,
	VSTAT__lights_automaticLightControlOn	= 5,
	VSTAT__lights_daytimeRunningLightsOn	= 6,
	VSTAT__lights_fogLightOn	= 7,
	VSTAT__lights_parkingLightsOn	= 8
} e_VSTAT__lights;

/* VSTAT */
typedef struct VSTAT {
	OCTET_STRING_t	 id;
	long	 Long;
	long	 lat;
	long	 vert;
	long	 yaw;
	long	 brakePadel;
	long	 abs;
	long	 scs;
	BIT_STRING_t	 lights;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VSTAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VSTAT;
extern asn_SEQUENCE_specifics_t asn_SPC_VSTAT_specs_1;
extern asn_TYPE_member_t asn_MBR_VSTAT_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _VSTAT_H_ */
#include <asn_internal.h>
