/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_WarnType_H_
#define	_WarnType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WarnType {
	WarnType_noWarning	= 0,
	WarnType_fcw	= 1,
	WarnType_icw	= 2,
	WarnType_lta	= 3,
	WarnType_bsw	= 4,
	WarnType_lcw	= 5,
	WarnType_dnpw	= 6,
	WarnType_ebw	= 7,
	WarnType_avw	= 8,
	WarnType_clw	= 9
} e_WarnType;

/* WarnType */
typedef long	 WarnType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_WarnType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_WarnType;
extern const asn_INTEGER_specifics_t asn_SPC_WarnType_specs_1;
asn_struct_free_f WarnType_free;
asn_struct_print_f WarnType_print;
asn_constr_check_f WarnType_constraint;
ber_type_decoder_f WarnType_decode_ber;
der_type_encoder_f WarnType_encode_der;
xer_type_decoder_f WarnType_decode_xer;
xer_type_encoder_f WarnType_encode_xer;
oer_type_decoder_f WarnType_decode_oer;
oer_type_encoder_f WarnType_encode_oer;
per_type_decoder_f WarnType_decode_uper;
per_type_encoder_f WarnType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WarnType_H_ */
#include <asn_internal.h>
