/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "OBU"
 * 	found in "asn/OBU.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_WarnState_H_
#define	_WarnState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WarnState {
	WarnState_off	= 0,
	WarnState_on	= 1
} e_WarnState;

/* WarnState */
typedef long	 WarnState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_WarnState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_WarnState;
extern const asn_INTEGER_specifics_t asn_SPC_WarnState_specs_1;
asn_struct_free_f WarnState_free;
asn_struct_print_f WarnState_print;
asn_constr_check_f WarnState_constraint;
ber_type_decoder_f WarnState_decode_ber;
der_type_encoder_f WarnState_encode_der;
xer_type_decoder_f WarnState_decode_xer;
xer_type_encoder_f WarnState_encode_xer;
oer_type_decoder_f WarnState_decode_oer;
oer_type_encoder_f WarnState_encode_oer;
per_type_decoder_f WarnState_decode_uper;
per_type_encoder_f WarnState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WarnState_H_ */
#include <asn_internal.h>
