/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "ApplicationType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ApplicationType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ApplicationType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  14 }	/* (0..14,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ApplicationType_value2enum_1[] = {
	{ 0,	3,	"dsa" },
	{ 1,	11,	"bsm-general" },
	{ 2,	10,	"bsm-events" },
	{ 3,	21,	"emergency-bsm-general" },
	{ 4,	20,	"emergency-bsm-events" },
	{ 5,	13,	"vehicle-after" },
	{ 6,	3,	"map" },
	{ 7,	4,	"spat" },
	{ 8,	10,	"rsi-static" },
	{ 9,	14,	"rsi-semistatic" },
	{ 10,	12,	"rsi-dynamics" },
	{ 11,	3,	"rsm" },
	{ 12,	12,	"vehicle-test" },
	{ 13,	9,	"rsu-test1" },
	{ 14,	9,	"rsu-test2" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ApplicationType_enum2value_1[] = {
	2,	/* bsm-events(2) */
	1,	/* bsm-general(1) */
	0,	/* dsa(0) */
	4,	/* emergency-bsm-events(4) */
	3,	/* emergency-bsm-general(3) */
	6,	/* map(6) */
	10,	/* rsi-dynamics(10) */
	9,	/* rsi-semistatic(9) */
	8,	/* rsi-static(8) */
	11,	/* rsm(11) */
	13,	/* rsu-test1(13) */
	14,	/* rsu-test2(14) */
	7,	/* spat(7) */
	5,	/* vehicle-after(5) */
	12	/* vehicle-test(12) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_ApplicationType_specs_1 = {
	asn_MAP_ApplicationType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ApplicationType_enum2value_1,	/* N => "tag"; sorted by N */
	15,	/* Number of elements in the maps */
	16,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ApplicationType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ApplicationType = {
	"ApplicationType",
	"ApplicationType",
	&asn_OP_NativeEnumerated,
	asn_DEF_ApplicationType_tags_1,
	sizeof(asn_DEF_ApplicationType_tags_1)
		/sizeof(asn_DEF_ApplicationType_tags_1[0]), /* 1 */
	asn_DEF_ApplicationType_tags_1,	/* Same as above */
	sizeof(asn_DEF_ApplicationType_tags_1)
		/sizeof(asn_DEF_ApplicationType_tags_1[0]), /* 1 */
	{ &asn_OER_type_ApplicationType_constr_1, &asn_PER_type_ApplicationType_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ApplicationType_specs_1	/* Additional specs */
};

