/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "AvailableSpdu.h"

static int
memb_data_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)st; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_data_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_data_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AvailableSpdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AvailableSpdu, itsAid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"itsAid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AvailableSpdu, data),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_data_constr_3, &asn_PER_memb_data_constr_3,  memb_data_constraint_1 },
		0, 0, /* No default value */
		"data"
		},
};
static const ber_tlv_tag_t asn_DEF_AvailableSpdu_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AvailableSpdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* itsAid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* data */
};
asn_SEQUENCE_specifics_t asn_SPC_AvailableSpdu_specs_1 = {
	sizeof(struct AvailableSpdu),
	offsetof(struct AvailableSpdu, _asn_ctx),
	asn_MAP_AvailableSpdu_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AvailableSpdu = {
	"AvailableSpdu",
	"AvailableSpdu",
	&asn_OP_SEQUENCE,
	asn_DEF_AvailableSpdu_tags_1,
	sizeof(asn_DEF_AvailableSpdu_tags_1)
		/sizeof(asn_DEF_AvailableSpdu_tags_1[0]), /* 1 */
	asn_DEF_AvailableSpdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_AvailableSpdu_tags_1)
		/sizeof(asn_DEF_AvailableSpdu_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AvailableSpdu_1,
	2,	/* Elements count */
	&asn_SPC_AvailableSpdu_specs_1	/* Additional specs */
};

