/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "BasicMapLaneInfo.h"

asn_TYPE_member_t asn_MBR_BasicMapLaneInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BasicMapLaneInfo, laneID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneID"
		},
	{ ATF_POINTER, 2, offsetof(struct BasicMapLaneInfo, laneWidth),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneWidth,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneWidth"
		},
	{ ATF_POINTER, 1, offsetof(struct BasicMapLaneInfo, laneSpeedLimits),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedLimitList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laneSpeedLimits"
		},
};
static const int asn_MAP_BasicMapLaneInfo_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_BasicMapLaneInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BasicMapLaneInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* laneID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* laneWidth */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* laneSpeedLimits */
};
asn_SEQUENCE_specifics_t asn_SPC_BasicMapLaneInfo_specs_1 = {
	sizeof(struct BasicMapLaneInfo),
	offsetof(struct BasicMapLaneInfo, _asn_ctx),
	asn_MAP_BasicMapLaneInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_BasicMapLaneInfo_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BasicMapLaneInfo = {
	"BasicMapLaneInfo",
	"BasicMapLaneInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_BasicMapLaneInfo_tags_1,
	sizeof(asn_DEF_BasicMapLaneInfo_tags_1)
		/sizeof(asn_DEF_BasicMapLaneInfo_tags_1[0]), /* 1 */
	asn_DEF_BasicMapLaneInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_BasicMapLaneInfo_tags_1)
		/sizeof(asn_DEF_BasicMapLaneInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BasicMapLaneInfo_1,
	3,	/* Elements count */
	&asn_SPC_BasicMapLaneInfo_specs_1	/* Additional specs */
};

