/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_BasicRSM_H_
#define	_BasicRSM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RsuId.h"
#include "TestPosition3D.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasicRSM */
typedef struct BasicRSM {
	RsuId_t	 rsuId;
	TestPosition3D_t	 refPos;
	long	 countParticipants;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicRSM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicRSM;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicRSM_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicRSM_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _BasicRSM_H_ */
#include <asn_internal.h>
