/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_BasicMapLaneInfo_H_
#define	_BasicMapLaneInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneID.h"
#include "LaneWidth.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedLimitList;

/* BasicMapLaneInfo */
typedef struct BasicMapLaneInfo {
	LaneID_t	 laneID;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	struct SpeedLimitList	*laneSpeedLimits	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicMapLaneInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicMapLaneInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicMapLaneInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicMapLaneInfo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedLimitList.h"

#endif	/* _BasicMapLaneInfo_H_ */
#include <asn_internal.h>
