/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_BasicMapLinkInfo_H_
#define	_BasicMapLinkInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "NodeReferenceID.h"
#include "LaneWidth.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedLimitList;

/* BasicMapLinkInfo */
typedef struct BasicMapLinkInfo {
	DescriptiveName_t	*linkName	/* OPTIONAL */;
	NodeReferenceID_t	 linkUpstreamNodeId;
	struct SpeedLimitList	*linkSpeedLimits	/* OPTIONAL */;
	LaneWidth_t	*linkWidth	/* OPTIONAL */;
	long	 lanesInLink;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicMapLinkInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicMapLinkInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicMapLinkInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicMapLinkInfo_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedLimitList.h"

#endif	/* _BasicMapLinkInfo_H_ */
#include <asn_internal.h>
