/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_BasicMapNodesInfo_H_
#define	_BasicMapNodesInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "DescriptiveName.h"
#include "NodeReferenceID.h"
#include "TestPosition3D.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasicMapNodesInfo */
typedef struct BasicMapNodesInfo {
	long	 sizeNodeList;
	DescriptiveName_t	*nodeName	/* OPTIONAL */;
	NodeReferenceID_t	 nodeId;
	TestPosition3D_t	 nodeCenterPos;
	long	 linksInNode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicMapNodesInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicMapNodesInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicMapNodesInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicMapNodesInfo_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _BasicMapNodesInfo_H_ */
#include <asn_internal.h>
