/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_BasicSpatIntersections_H_
#define	_BasicSpatIntersections_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "NodeReferenceID.h"
#include "IntersectionStatusObject.h"
#include "DSecond.h"
#include "TimeConfidence.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasicSpatIntersections */
typedef struct BasicSpatIntersections {
	long	 sizeInterStateList;
	NodeReferenceID_t	 intersectionId;
	IntersectionStatusObject_t	 status;
	DSecond_t	*timeStamp	/* OPTIONAL */;
	TimeConfidence_t	*timeConfidence	/* OPTIONAL */;
	long	 phaseListSize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSpatIntersections_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSpatIntersections;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicSpatIntersections_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicSpatIntersections_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _BasicSpatIntersections_H_ */
#include <asn_internal.h>
