/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "BasicRSM.h"

static int
memb_countParticipants_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_countParticipants_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (1..16) */,
	-1};
static asn_per_constraints_t asn_PER_memb_countParticipants_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_BasicRSM_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BasicRSM, rsuId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RsuId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsuId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BasicRSM, refPos),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TestPosition3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"refPos"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BasicRSM, countParticipants),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_countParticipants_constr_4, &asn_PER_memb_countParticipants_constr_4,  memb_countParticipants_constraint_1 },
		0, 0, /* No default value */
		"countParticipants"
		},
};
static const ber_tlv_tag_t asn_DEF_BasicRSM_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BasicRSM_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsuId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* refPos */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* countParticipants */
};
asn_SEQUENCE_specifics_t asn_SPC_BasicRSM_specs_1 = {
	sizeof(struct BasicRSM),
	offsetof(struct BasicRSM, _asn_ctx),
	asn_MAP_BasicRSM_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BasicRSM = {
	"BasicRSM",
	"BasicRSM",
	&asn_OP_SEQUENCE,
	asn_DEF_BasicRSM_tags_1,
	sizeof(asn_DEF_BasicRSM_tags_1)
		/sizeof(asn_DEF_BasicRSM_tags_1[0]), /* 1 */
	asn_DEF_BasicRSM_tags_1,	/* Same as above */
	sizeof(asn_DEF_BasicRSM_tags_1)
		/sizeof(asn_DEF_BasicRSM_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BasicRSM_1,
	3,	/* Elements count */
	&asn_SPC_BasicRSM_specs_1	/* Additional specs */
};

