/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_BsmInfo_H_
#define	_BsmInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehTransmissionState.h"
#include "VehSpeed.h"
#include "VehHeading.h"
#include "VehEventFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TestPosition3D;
struct VehBrakeSystemStatus;
struct VehSize;
struct VehClassification;
struct VehEmergencyExtensions;

/* BsmInfo */
typedef struct BsmInfo {
	struct TestPosition3D	*position3D	/* OPTIONAL */;
	VehTransmissionState_t	*transmission	/* OPTIONAL */;
	VehSpeed_t	*speed	/* OPTIONAL */;
	VehHeading_t	*heading	/* OPTIONAL */;
	struct VehBrakeSystemStatus	*brakes	/* OPTIONAL */;
	struct VehSize	*size	/* OPTIONAL */;
	struct VehClassification	*vehClass	/* OPTIONAL */;
	VehEventFlags_t	*eventFlags	/* OPTIONAL */;
	struct VehEmergencyExtensions	*emergencyExt	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BsmInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BsmInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_BsmInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_BsmInfo_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TestPosition3D.h"
#include "VehBrakeSystemStatus.h"
#include "VehSize.h"
#include "VehClassification.h"
#include "VehEmergencyExtensions.h"

#endif	/* _BsmInfo_H_ */
#include <asn_internal.h>
