/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_CertRequest_H_
#define	_CertRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertRequest */
typedef OCTET_STRING_t	 CertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertRequest;
asn_struct_free_f CertRequest_free;
asn_struct_print_f CertRequest_print;
asn_constr_check_f CertRequest_constraint;
ber_type_decoder_f CertRequest_decode_ber;
der_type_encoder_f CertRequest_encode_der;
xer_type_decoder_f CertRequest_decode_xer;
xer_type_encoder_f CertRequest_encode_xer;
oer_type_decoder_f CertRequest_decode_oer;
oer_type_encoder_f CertRequest_encode_oer;
per_type_decoder_f CertRequest_decode_uper;
per_type_encoder_f CertRequest_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CertRequest_H_ */
#include <asn_internal.h>
