/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "CertInterface.h"

static asn_oer_constraints_t asn_OER_type_CertInterface_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_CertInterface_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_CertInterface_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertInterface, choice.sendCertReq),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SendCertReq,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sendCertReq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertInterface, choice.certRequest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertInterface, choice.certAck),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertAck,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certAck"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertInterface, choice.certDownload),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertDownload,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certDownload"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CertInterface_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sendCertReq */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* certRequest */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* certAck */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* certDownload */
};
asn_CHOICE_specifics_t asn_SPC_CertInterface_specs_1 = {
	sizeof(struct CertInterface),
	offsetof(struct CertInterface, _asn_ctx),
	offsetof(struct CertInterface, present),
	sizeof(((struct CertInterface *)0)->present),
	asn_MAP_CertInterface_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CertInterface = {
	"CertInterface",
	"CertInterface",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_CertInterface_constr_1, &asn_PER_type_CertInterface_constr_1, CHOICE_constraint },
	asn_MBR_CertInterface_1,
	4,	/* Elements count */
	&asn_SPC_CertInterface_specs_1	/* Additional specs */
};

