/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_CertAck_H_
#define	_CertAck_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertAck */
typedef OCTET_STRING_t	 CertAck_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertAck;
asn_struct_free_f CertAck_free;
asn_struct_print_f CertAck_print;
asn_constr_check_f CertAck_constraint;
ber_type_decoder_f CertAck_decode_ber;
der_type_encoder_f CertAck_encode_der;
xer_type_decoder_f CertAck_decode_xer;
xer_type_encoder_f CertAck_encode_xer;
oer_type_decoder_f CertAck_decode_oer;
oer_type_encoder_f CertAck_encode_oer;
per_type_decoder_f CertAck_decode_uper;
per_type_encoder_f CertAck_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CertAck_H_ */
#include <asn_internal.h>
