/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_CurrentPhase_H_
#define	_CurrentPhase_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhaseID.h"
#include "PhaseState.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CurrentPhase */
typedef struct CurrentPhase {
	PhaseID_t	 id;
	PhaseState_t	 phaseState;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurrentPhase_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurrentPhase;
extern asn_SEQUENCE_specifics_t asn_SPC_CurrentPhase_specs_1;
extern asn_TYPE_member_t asn_MBR_CurrentPhase_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CurrentPhase_H_ */
#include <asn_internal.h>
