/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "DsmFrame.h"

static int
memb_dsmpVersion_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dsmpExtensionIndicator_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_dsmpVersion_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..7) */,
	-1};
static asn_per_constraints_t asn_PER_memb_dsmpVersion_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_dsmpExtensionIndicator_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_dsmpExtensionIndicator_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_DsmFrame_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DsmFrame, dsmpVersion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_dsmpVersion_constr_2, &asn_PER_memb_dsmpVersion_constr_2,  memb_dsmpVersion_constraint_1 },
		0, 0, /* No default value */
		"dsmpVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DsmFrame, dsmpExtensionIndicator),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_dsmpExtensionIndicator_constr_3, &asn_PER_memb_dsmpExtensionIndicator_constr_3,  memb_dsmpExtensionIndicator_constraint_1 },
		0, 0, /* No default value */
		"dsmpExtensionIndicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DsmFrame, aid),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_Aid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DsmFrame, dsmLength),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DsmMaxLength,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dsmLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DsmFrame, dsmData),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DsmData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dsmData"
		},
};
static const ber_tlv_tag_t asn_DEF_DsmFrame_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DsmFrame_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dsmpVersion */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dsmpExtensionIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aid */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dsmLength */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* dsmData */
};
asn_SEQUENCE_specifics_t asn_SPC_DsmFrame_specs_1 = {
	sizeof(struct DsmFrame),
	offsetof(struct DsmFrame, _asn_ctx),
	asn_MAP_DsmFrame_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DsmFrame = {
	"DsmFrame",
	"DsmFrame",
	&asn_OP_SEQUENCE,
	asn_DEF_DsmFrame_tags_1,
	sizeof(asn_DEF_DsmFrame_tags_1)
		/sizeof(asn_DEF_DsmFrame_tags_1[0]), /* 1 */
	asn_DEF_DsmFrame_tags_1,	/* Same as above */
	sizeof(asn_DEF_DsmFrame_tags_1)
		/sizeof(asn_DEF_DsmFrame_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DsmFrame_1,
	5,	/* Elements count */
	&asn_SPC_DsmFrame_specs_1	/* Additional specs */
};

