/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_DsmFrame_H_
#define	_DsmFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "TciNetworkLayerFrame_Aid.h"
#include "DsmMaxLength.h"
#include "DsmData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DsmFrame */
typedef struct DsmFrame {
	long	 dsmpVersion;
	long	 dsmpExtensionIndicator;
	TciNetworkLayerFrame_Aid_t	 aid;
	DsmMaxLength_t	 dsmLength;
	DsmData_t	 dsmData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DsmFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DsmFrame;
extern asn_SEQUENCE_specifics_t asn_SPC_DsmFrame_specs_1;
extern asn_TYPE_member_t asn_MBR_DsmFrame_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DsmFrame_H_ */
#include <asn_internal.h>
