/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_DsmMaxLength_H_
#define	_DsmMaxLength_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DsmMaxLength */
typedef long	 DsmMaxLength_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DsmMaxLength_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DsmMaxLength;
asn_struct_free_f DsmMaxLength_free;
asn_struct_print_f DsmMaxLength_print;
asn_constr_check_f DsmMaxLength_constraint;
ber_type_decoder_f DsmMaxLength_decode_ber;
der_type_encoder_f DsmMaxLength_encode_der;
xer_type_decoder_f DsmMaxLength_decode_xer;
xer_type_encoder_f DsmMaxLength_encode_xer;
oer_type_decoder_f DsmMaxLength_decode_oer;
oer_type_encoder_f DsmMaxLength_encode_oer;
per_type_decoder_f DsmMaxLength_decode_uper;
per_type_encoder_f DsmMaxLength_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DsmMaxLength_H_ */
#include <asn_internal.h>
