/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_MsgLayerPduParam_H_
#define	_MsgLayerPduParam_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BsmInfo.h"
#include "RxMapInfo.h"
#include "RxSpatInfo.h"
#include "RxRsiInfo.h"
#include "RxRsmInfo.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MsgLayerPduParam_PR {
	MsgLayerPduParam_PR_NOTHING,	/* No components present */
	MsgLayerPduParam_PR_bsmPduParam,
	MsgLayerPduParam_PR_mapPduParam,
	MsgLayerPduParam_PR_spatPduParam,
	MsgLayerPduParam_PR_rsiPduParam,
	MsgLayerPduParam_PR_rsmPduParam
	/* Extensions may appear below */
	
} MsgLayerPduParam_PR;

/* MsgLayerPduParam */
typedef struct MsgLayerPduParam {
	MsgLayerPduParam_PR present;
	union MsgLayerPduParam_u {
		BsmInfo_t	 bsmPduParam;
		RxMapInfo_t	 mapPduParam;
		RxSpatInfo_t	 spatPduParam;
		RxRsiInfo_t	 rsiPduParam;
		RxRsmInfo_t	 rsmPduParam;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MsgLayerPduParam_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgLayerPduParam;
extern asn_CHOICE_specifics_t asn_SPC_MsgLayerPduParam_specs_1;
extern asn_TYPE_member_t asn_MBR_MsgLayerPduParam_1[5];
extern asn_per_constraints_t asn_PER_type_MsgLayerPduParam_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgLayerPduParam_H_ */
#include <asn_internal.h>
