/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_NetworkLayerFrame_H_
#define	_NetworkLayerFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolType.h"
#include "DsmFrame.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NetworkLayerFrame */
typedef struct NetworkLayerFrame {
	ProtocolType_t	 protocolType;
	DsmFrame_t	 dsmFrame;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NetworkLayerFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkLayerFrame;
extern asn_SEQUENCE_specifics_t asn_SPC_NetworkLayerFrame_specs_1;
extern asn_TYPE_member_t asn_MBR_NetworkLayerFrame_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkLayerFrame_H_ */
#include <asn_internal.h>
