/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "NetworkLayerFrame.h"

asn_TYPE_member_t asn_MBR_NetworkLayerFrame_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkLayerFrame, protocolType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocolType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkLayerFrame, dsmFrame),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DsmFrame,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dsmFrame"
		},
};
static const ber_tlv_tag_t asn_DEF_NetworkLayerFrame_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NetworkLayerFrame_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocolType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* dsmFrame */
};
asn_SEQUENCE_specifics_t asn_SPC_NetworkLayerFrame_specs_1 = {
	sizeof(struct NetworkLayerFrame),
	offsetof(struct NetworkLayerFrame, _asn_ctx),
	asn_MAP_NetworkLayerFrame_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NetworkLayerFrame = {
	"NetworkLayerFrame",
	"NetworkLayerFrame",
	&asn_OP_SEQUENCE,
	asn_DEF_NetworkLayerFrame_tags_1,
	sizeof(asn_DEF_NetworkLayerFrame_tags_1)
		/sizeof(asn_DEF_NetworkLayerFrame_tags_1[0]), /* 1 */
	asn_DEF_NetworkLayerFrame_tags_1,	/* Same as above */
	sizeof(asn_DEF_NetworkLayerFrame_tags_1)
		/sizeof(asn_DEF_NetworkLayerFrame_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NetworkLayerFrame_1,
	2,	/* Elements count */
	&asn_SPC_NetworkLayerFrame_specs_1	/* Additional specs */
};

