/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ParamInRsi_H_
#define	_ParamInRsi_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParamInRsi {
	ParamInRsi_containsBasicRSI	= 0,
	ParamInRsi_containsRteData	= 1,
	ParamInRsi_containsRtsData	= 2
} e_ParamInRsi;

/* ParamInRsi */
typedef BIT_STRING_t	 ParamInRsi_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParamInRsi;
asn_struct_free_f ParamInRsi_free;
asn_struct_print_f ParamInRsi_print;
asn_constr_check_f ParamInRsi_constraint;
ber_type_decoder_f ParamInRsi_decode_ber;
der_type_encoder_f ParamInRsi_encode_der;
xer_type_decoder_f ParamInRsi_decode_xer;
xer_type_encoder_f ParamInRsi_encode_xer;
oer_type_decoder_f ParamInRsi_decode_oer;
oer_type_encoder_f ParamInRsi_encode_oer;
per_type_decoder_f ParamInRsi_decode_uper;
per_type_encoder_f ParamInRsi_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParamInRsi_H_ */
#include <asn_internal.h>
