/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ParamInSpat_H_
#define	_ParamInSpat_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParamInSpat {
	ParamInSpat_containsBasicSpatIntersections	= 0,
	ParamInSpat_containsCurrentPhase	= 1
} e_ParamInSpat;

/* ParamInSpat */
typedef BIT_STRING_t	 ParamInSpat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParamInSpat;
asn_struct_free_f ParamInSpat_free;
asn_struct_print_f ParamInSpat_print;
asn_constr_check_f ParamInSpat_constraint;
ber_type_decoder_f ParamInSpat_decode_ber;
der_type_encoder_f ParamInSpat_encode_der;
xer_type_decoder_f ParamInSpat_decode_xer;
xer_type_encoder_f ParamInSpat_encode_xer;
oer_type_decoder_f ParamInSpat_decode_oer;
oer_type_encoder_f ParamInSpat_encode_oer;
per_type_decoder_f ParamInSpat_decode_uper;
per_type_encoder_f ParamInSpat_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParamInSpat_H_ */
#include <asn_internal.h>
