/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayer;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_TciMsgFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_SetInitialState;
extern struct asn_TYPE_descriptor_s asn_DEF_StartMsgLayerTx;
extern struct asn_TYPE_descriptor_s asn_DEF_StopMsgLayerTx;
extern struct asn_TYPE_descriptor_s asn_DEF_StartMsgLayerRx;
extern struct asn_TYPE_descriptor_s asn_DEF_StopMsgLayerRx;
extern struct asn_TYPE_descriptor_s asn_DEF_SetBsmInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SetRsmInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_TestPosition3D;
extern struct asn_TYPE_descriptor_s asn_DEF_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_BsmInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_VehSpeed;
extern struct asn_TYPE_descriptor_s asn_DEF_VehHeading;
extern struct asn_TYPE_descriptor_s asn_DEF_VehTransmissionState;
extern struct asn_TYPE_descriptor_s asn_DEF_VehBrakeSystemStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_VehSize;
extern struct asn_TYPE_descriptor_s asn_DEF_VehClassification;
extern struct asn_TYPE_descriptor_s asn_DEF_VehEventFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_VehEmergencyExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicMapNodesInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicMapLinkInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicMapLaneInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeReferenceID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadRegulatorID;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeID;
extern struct asn_TYPE_descriptor_s asn_DEF_DescriptiveName;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneID;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitList;
extern struct asn_TYPE_descriptor_s asn_DEF_RegulatorySpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitType;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectsToList;
extern struct asn_TYPE_descriptor_s asn_DEF_Connection;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectingLane;
extern struct asn_TYPE_descriptor_s asn_DEF_AllowedManeuvers;
extern struct asn_TYPE_descriptor_s asn_DEF_RxMapInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicSpatIntersections;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStatusObject;
extern struct asn_TYPE_descriptor_s asn_DEF_DSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_CurrentPhase;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseState;
extern struct asn_TYPE_descriptor_s asn_DEF_LightState;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseID;
extern struct asn_TYPE_descriptor_s asn_DEF_SignType;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeMark;
extern struct asn_TYPE_descriptor_s asn_DEF_RxSpatInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_TestVehicleInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicRSI;
extern struct asn_TYPE_descriptor_s asn_DEF_RteData;
extern struct asn_TYPE_descriptor_s asn_DEF_EventType;
extern struct asn_TYPE_descriptor_s asn_DEF_EventSource;
extern struct asn_TYPE_descriptor_s asn_DEF_RtsData;
extern struct asn_TYPE_descriptor_s asn_DEF_RxRsiInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicRSM;
extern struct asn_TYPE_descriptor_s asn_DEF_PtcData;
extern struct asn_TYPE_descriptor_s asn_DEF_PtcType;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceType;
extern struct asn_TYPE_descriptor_s asn_DEF_RxRsmInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_RsuId;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_MsgID;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Aid;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_RepeatRate;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_ResultCode;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Exception;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_ExceptionType;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Module;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_ExceptionId;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_ExceptionText;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_EventHandling;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_RxFlag;
extern struct asn_TYPE_descriptor_s asn_DEF_RxPduParamFlag;
extern struct asn_TYPE_descriptor_s asn_DEF_BsmPduParam;
extern struct asn_TYPE_descriptor_s asn_DEF_RxMapRequirement;
extern struct asn_TYPE_descriptor_s asn_DEF_ParamInMap;
extern struct asn_TYPE_descriptor_s asn_DEF_RxSpatRequirement;
extern struct asn_TYPE_descriptor_s asn_DEF_ParamInSpat;
extern struct asn_TYPE_descriptor_s asn_DEF_RxRsiRequirement;
extern struct asn_TYPE_descriptor_s asn_DEF_ParamInRsi;
extern struct asn_TYPE_descriptor_s asn_DEF_RxRsmRequirement;
extern struct asn_TYPE_descriptor_s asn_DEF_ParamInRsm;
extern struct asn_TYPE_descriptor_s asn_DEF_MsgType;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Indication;
extern struct asn_TYPE_descriptor_s asn_DEF_TciMsgLayerFrame_Event;
extern struct asn_TYPE_descriptor_s asn_DEF_MsgLayerPduParam;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOffsetLLV;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B14;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B16;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B18;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B22;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B24;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_24B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_28B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_32B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_36B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_44B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_48B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LLmD_64b;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOffsetLL;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B07;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B08;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B09;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B10;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B11;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_ElevationConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayer;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_TciMsgFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_SetInitialState;
extern struct asn_TYPE_descriptor_s asn_DEF_StartDsmTx;
extern struct asn_TYPE_descriptor_s asn_DEF_StopDsmTx;
extern struct asn_TYPE_descriptor_s asn_DEF_StartDsmRx;
extern struct asn_TYPE_descriptor_s asn_DEF_StopDsmRx;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_MsgID;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Aid;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_RepeatRate;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_ResultCode;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Exception;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_ExceptionType;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Module;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_ExceptionId;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_ExceptionText;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_EventHandling;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_RxFlag;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Indication;
extern struct asn_TYPE_descriptor_s asn_DEF_TciNetworkLayerFrame_Event;
extern struct asn_TYPE_descriptor_s asn_DEF_NetworkLayerFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_DsmFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtocolType;
extern struct asn_TYPE_descriptor_s asn_DEF_DsmMaxLength;
extern struct asn_TYPE_descriptor_s asn_DEF_DsmData;
extern struct asn_TYPE_descriptor_s asn_DEF_SetMibInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsg;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_TciMsgFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_SetInitialState;
extern struct asn_TYPE_descriptor_s asn_DEF_StartSpduTx;
extern struct asn_TYPE_descriptor_s asn_DEF_StopSpduTx;
extern struct asn_TYPE_descriptor_s asn_DEF_StartSpduRx;
extern struct asn_TYPE_descriptor_s asn_DEF_StopSpduRx;
extern struct asn_TYPE_descriptor_s asn_DEF_Opaque;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_MsgID;
extern struct asn_TYPE_descriptor_s asn_DEF_ApplicationType;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerIdentifierType;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_RepeatRate;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_ResultCode;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_Exception;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_ExceptionType;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_ExceptionId;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_Module;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_ExceptionText;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_EventHandling;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_RxFlag;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_Indication;
extern struct asn_TYPE_descriptor_s asn_DEF_TciSecMsgFrame_Event;
extern struct asn_TYPE_descriptor_s asn_DEF_AvailableSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_IncorrectSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityResultCode;
extern struct asn_TYPE_descriptor_s asn_DEF_CertInterface;
extern struct asn_TYPE_descriptor_s asn_DEF_SendCertReq;
extern struct asn_TYPE_descriptor_s asn_DEF_CertRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_CertAck;
extern struct asn_TYPE_descriptor_s asn_DEF_CertDownload;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module TciMsgLayerFrame in asn/msg_conformance.asn */
	&asn_DEF_TciMsgLayer,	
	&asn_DEF_TciMsgLayerFrame_TciMsgFrame,	
	&asn_DEF_TciMsgLayerFrame_Request,	
	&asn_DEF_TciMsgLayerFrame_SetInitialState,	
	&asn_DEF_StartMsgLayerTx,	
	&asn_DEF_StopMsgLayerTx,	
	&asn_DEF_StartMsgLayerRx,	
	&asn_DEF_StopMsgLayerRx,	
	&asn_DEF_SetBsmInfo,	
	&asn_DEF_SetRsmInfo,	
	&asn_DEF_TestPosition3D,	
	&asn_DEF_Latitude,	
	&asn_DEF_Longitude,	
	&asn_DEF_Elevation,	
	&asn_DEF_BsmInfo,	
	&asn_DEF_VehSpeed,	
	&asn_DEF_VehHeading,	
	&asn_DEF_VehTransmissionState,	
	&asn_DEF_VehBrakeSystemStatus,	
	&asn_DEF_VehSize,	
	&asn_DEF_VehClassification,	
	&asn_DEF_VehEventFlags,	
	&asn_DEF_VehEmergencyExtensions,	
	&asn_DEF_BasicMapNodesInfo,	
	&asn_DEF_BasicMapLinkInfo,	
	&asn_DEF_BasicMapLaneInfo,	
	&asn_DEF_NodeReferenceID,	
	&asn_DEF_RoadRegulatorID,	
	&asn_DEF_NodeID,	
	&asn_DEF_DescriptiveName,	
	&asn_DEF_LaneID,	
	&asn_DEF_LaneWidth,	
	&asn_DEF_SpeedLimitList,	
	&asn_DEF_RegulatorySpeedLimit,	
	&asn_DEF_SpeedLimitType,	
	&asn_DEF_ConnectsToList,	
	&asn_DEF_Connection,	
	&asn_DEF_ConnectingLane,	
	&asn_DEF_AllowedManeuvers,	
	&asn_DEF_RxMapInfo,	
	&asn_DEF_BasicSpatIntersections,	
	&asn_DEF_IntersectionStatusObject,	
	&asn_DEF_DSecond,	
	&asn_DEF_TimeConfidence,	
	&asn_DEF_CurrentPhase,	
	&asn_DEF_PhaseState,	
	&asn_DEF_LightState,	
	&asn_DEF_PhaseID,	
	&asn_DEF_SignType,	
	&asn_DEF_TimeMark,	
	&asn_DEF_RxSpatInfo,	
	&asn_DEF_TestVehicleInfo,	
	&asn_DEF_BasicRSI,	
	&asn_DEF_RteData,	
	&asn_DEF_EventType,	
	&asn_DEF_EventSource,	
	&asn_DEF_RtsData,	
	&asn_DEF_RxRsiInfo,	
	&asn_DEF_BasicRSM,	
	&asn_DEF_PtcData,	
	&asn_DEF_PtcType,	
	&asn_DEF_SourceType,	
	&asn_DEF_RxRsmInfo,	
	&asn_DEF_RsuId,	
	&asn_DEF_TciMsgLayerFrame_MsgID,	
	&asn_DEF_TciMsgLayerFrame_Aid,	
	&asn_DEF_TciMsgLayerFrame_RepeatRate,	
	&asn_DEF_TciMsgLayerFrame_Response,	
	&asn_DEF_TciMsgLayerFrame_ResultCode,	
	&asn_DEF_TciMsgLayerFrame_Exception,	
	&asn_DEF_TciMsgLayerFrame_ExceptionType,	
	&asn_DEF_TciMsgLayerFrame_Module,	
	&asn_DEF_TciMsgLayerFrame_ExceptionId,	
	&asn_DEF_TciMsgLayerFrame_ExceptionText,	
	&asn_DEF_TciMsgLayerFrame_EventHandling,	
	&asn_DEF_TciMsgLayerFrame_RxFlag,	
	&asn_DEF_RxPduParamFlag,	
	&asn_DEF_BsmPduParam,	
	&asn_DEF_RxMapRequirement,	
	&asn_DEF_ParamInMap,	
	&asn_DEF_RxSpatRequirement,	
	&asn_DEF_ParamInSpat,	
	&asn_DEF_RxRsiRequirement,	
	&asn_DEF_ParamInRsi,	
	&asn_DEF_RxRsmRequirement,	
	&asn_DEF_ParamInRsm,	
	&asn_DEF_MsgType,	
	&asn_DEF_TciMsgLayerFrame_Indication,	
	&asn_DEF_TciMsgLayerFrame_Event,	
	&asn_DEF_MsgLayerPduParam,	
	&asn_DEF_PositionOffsetLLV,	
	&asn_DEF_OffsetLL_B12,	
	&asn_DEF_OffsetLL_B14,	
	&asn_DEF_OffsetLL_B16,	
	&asn_DEF_OffsetLL_B18,	
	&asn_DEF_OffsetLL_B22,	
	&asn_DEF_OffsetLL_B24,	
	&asn_DEF_Position_LL_24B,	
	&asn_DEF_Position_LL_28B,	
	&asn_DEF_Position_LL_32B,	
	&asn_DEF_Position_LL_36B,	
	&asn_DEF_Position_LL_44B,	
	&asn_DEF_Position_LL_48B,	
	&asn_DEF_Position_LLmD_64b,	
	&asn_DEF_PositionOffsetLL,	
	&asn_DEF_VerticalOffset,	
	&asn_DEF_VertOffset_B07,	
	&asn_DEF_VertOffset_B08,	
	&asn_DEF_VertOffset_B09,	
	&asn_DEF_VertOffset_B10,	
	&asn_DEF_VertOffset_B11,	
	&asn_DEF_VertOffset_B12,	
	&asn_DEF_PositionConfidenceSet,	
	&asn_DEF_PositionConfidence,	
	&asn_DEF_ElevationConfidence,	
	/* From module TciNetworkLayerFrame in asn/net_conformance.asn */
	&asn_DEF_TciNetworkLayer,	
	&asn_DEF_TciNetworkLayerFrame_TciMsgFrame,	
	&asn_DEF_TciNetworkLayerFrame_Request,	
	&asn_DEF_TciNetworkLayerFrame_SetInitialState,	
	&asn_DEF_StartDsmTx,	
	&asn_DEF_StopDsmTx,	
	&asn_DEF_StartDsmRx,	
	&asn_DEF_StopDsmRx,	
	&asn_DEF_TciNetworkLayerFrame_MsgID,	
	&asn_DEF_TciNetworkLayerFrame_Aid,	
	&asn_DEF_TciNetworkLayerFrame_RepeatRate,	
	&asn_DEF_TciNetworkLayerFrame_Response,	
	&asn_DEF_TciNetworkLayerFrame_ResultCode,	
	&asn_DEF_TciNetworkLayerFrame_Exception,	
	&asn_DEF_TciNetworkLayerFrame_ExceptionType,	
	&asn_DEF_TciNetworkLayerFrame_Module,	
	&asn_DEF_TciNetworkLayerFrame_ExceptionId,	
	&asn_DEF_TciNetworkLayerFrame_ExceptionText,	
	&asn_DEF_TciNetworkLayerFrame_EventHandling,	
	&asn_DEF_TciNetworkLayerFrame_RxFlag,	
	&asn_DEF_TciNetworkLayerFrame_Indication,	
	&asn_DEF_TciNetworkLayerFrame_Event,	
	&asn_DEF_NetworkLayerFrame,	
	&asn_DEF_DsmFrame,	
	&asn_DEF_ProtocolType,	
	&asn_DEF_DsmMaxLength,	
	&asn_DEF_DsmData,	
	&asn_DEF_SetMibInfo,	
	/* From module TciSecMsgFrame in asn/sec_conformance.asn */
	&asn_DEF_TciSecMsg,	
	&asn_DEF_TciSecMsgFrame_TciMsgFrame,	
	&asn_DEF_TciSecMsgFrame_Request,	
	&asn_DEF_TciSecMsgFrame_SetInitialState,	
	&asn_DEF_StartSpduTx,	
	&asn_DEF_StopSpduTx,	
	&asn_DEF_StartSpduRx,	
	&asn_DEF_StopSpduRx,	
	&asn_DEF_Opaque,	
	&asn_DEF_TciSecMsgFrame_MsgID,	
	&asn_DEF_ApplicationType,	
	&asn_DEF_SignerIdentifierType,	
	&asn_DEF_TciSecMsgFrame_RepeatRate,	
	&asn_DEF_TciSecMsgFrame_Response,	
	&asn_DEF_TciSecMsgFrame_ResultCode,	
	&asn_DEF_TciSecMsgFrame_Exception,	
	&asn_DEF_TciSecMsgFrame_ExceptionType,	
	&asn_DEF_TciSecMsgFrame_ExceptionId,	
	&asn_DEF_TciSecMsgFrame_Module,	
	&asn_DEF_TciSecMsgFrame_ExceptionText,	
	&asn_DEF_TciSecMsgFrame_EventHandling,	
	&asn_DEF_TciSecMsgFrame_RxFlag,	
	&asn_DEF_TciSecMsgFrame_Indication,	
	&asn_DEF_TciSecMsgFrame_Event,	
	&asn_DEF_AvailableSpdu,	
	&asn_DEF_IncorrectSpdu,	
	&asn_DEF_SecurityResultCode,	
	&asn_DEF_CertInterface,	
	&asn_DEF_SendCertReq,	
	&asn_DEF_CertRequest,	
	&asn_DEF_CertAck,	
	&asn_DEF_CertDownload,	
	0
};

