/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RsuId_H_
#define	_RsuId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RsuId */
typedef OCTET_STRING_t	 RsuId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RsuId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RsuId;
asn_struct_free_f RsuId_free;
asn_struct_print_f RsuId_print;
asn_constr_check_f RsuId_constraint;
ber_type_decoder_f RsuId_decode_ber;
der_type_encoder_f RsuId_encode_der;
xer_type_decoder_f RsuId_decode_xer;
xer_type_encoder_f RsuId_encode_xer;
oer_type_decoder_f RsuId_decode_oer;
oer_type_encoder_f RsuId_encode_oer;
per_type_decoder_f RsuId_decode_uper;
per_type_encoder_f RsuId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RsuId_H_ */
#include <asn_internal.h>
