/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RxMapInfo_H_
#define	_RxMapInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AllowedManeuvers.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BasicMapNodesInfo;
struct BasicMapLinkInfo;
struct BasicMapLaneInfo;
struct ConnectsToList;

/* RxMapInfo */
typedef struct RxMapInfo {
	struct BasicMapNodesInfo	*basicMapNodesInfo	/* OPTIONAL */;
	struct BasicMapLinkInfo	*basicMapLinkInfo	/* OPTIONAL */;
	struct BasicMapLaneInfo	*basicMapLaneInfo	/* OPTIONAL */;
	struct ConnectsToList	*connectsToList	/* OPTIONAL */;
	AllowedManeuvers_t	*allowedManeuvers	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RxMapInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RxMapInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_RxMapInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_RxMapInfo_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BasicMapNodesInfo.h"
#include "BasicMapLinkInfo.h"
#include "BasicMapLaneInfo.h"
#include "ConnectsToList.h"

#endif	/* _RxMapInfo_H_ */
#include <asn_internal.h>
