/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "RxPduParamFlag.h"

static asn_oer_constraints_t asn_OER_type_RxPduParamFlag_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_RxPduParamFlag_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RxPduParamFlag_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RxPduParamFlag, choice.rxBsmPduParam),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BsmPduParam,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxBsmPduParam"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RxPduParamFlag, choice.rxMapRequirement),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RxMapRequirement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxMapRequirement"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RxPduParamFlag, choice.rxSpatRequirement),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RxSpatRequirement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxSpatRequirement"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RxPduParamFlag, choice.rxRsiRequirement),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RxRsiRequirement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxRsiRequirement"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RxPduParamFlag, choice.rxRsmRequirement),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RxRsmRequirement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxRsmRequirement"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RxPduParamFlag_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rxBsmPduParam */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rxMapRequirement */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rxSpatRequirement */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rxRsiRequirement */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* rxRsmRequirement */
};
asn_CHOICE_specifics_t asn_SPC_RxPduParamFlag_specs_1 = {
	sizeof(struct RxPduParamFlag),
	offsetof(struct RxPduParamFlag, _asn_ctx),
	offsetof(struct RxPduParamFlag, present),
	sizeof(((struct RxPduParamFlag *)0)->present),
	asn_MAP_RxPduParamFlag_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RxPduParamFlag = {
	"RxPduParamFlag",
	"RxPduParamFlag",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_RxPduParamFlag_constr_1, &asn_PER_type_RxPduParamFlag_constr_1, CHOICE_constraint },
	asn_MBR_RxPduParamFlag_1,
	5,	/* Elements count */
	&asn_SPC_RxPduParamFlag_specs_1	/* Additional specs */
};

