/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "RxRsiRequirement.h"

static int
memb_rteId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_rtsId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_rteId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_rteId_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_rtsId_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_rtsId_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RxRsiRequirement_1[] = {
	{ ATF_POINTER, 2, offsetof(struct RxRsiRequirement, rteId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_rteId_constr_2, &asn_PER_memb_rteId_constr_2,  memb_rteId_constraint_1 },
		0, 0, /* No default value */
		"rteId"
		},
	{ ATF_POINTER, 1, offsetof(struct RxRsiRequirement, rtsId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_rtsId_constr_3, &asn_PER_memb_rtsId_constr_3,  memb_rtsId_constraint_1 },
		0, 0, /* No default value */
		"rtsId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RxRsiRequirement, paramInRsi),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ParamInRsi,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"paramInRsi"
		},
};
static const int asn_MAP_RxRsiRequirement_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_RxRsiRequirement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RxRsiRequirement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rteId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rtsId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* paramInRsi */
};
asn_SEQUENCE_specifics_t asn_SPC_RxRsiRequirement_specs_1 = {
	sizeof(struct RxRsiRequirement),
	offsetof(struct RxRsiRequirement, _asn_ctx),
	asn_MAP_RxRsiRequirement_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RxRsiRequirement_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RxRsiRequirement = {
	"RxRsiRequirement",
	"RxRsiRequirement",
	&asn_OP_SEQUENCE,
	asn_DEF_RxRsiRequirement_tags_1,
	sizeof(asn_DEF_RxRsiRequirement_tags_1)
		/sizeof(asn_DEF_RxRsiRequirement_tags_1[0]), /* 1 */
	asn_DEF_RxRsiRequirement_tags_1,	/* Same as above */
	sizeof(asn_DEF_RxRsiRequirement_tags_1)
		/sizeof(asn_DEF_RxRsiRequirement_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RxRsiRequirement_1,
	3,	/* Elements count */
	&asn_SPC_RxRsiRequirement_specs_1	/* Additional specs */
};

