/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RxRsiRequirement_H_
#define	_RxRsiRequirement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ParamInRsi.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RxRsiRequirement */
typedef struct RxRsiRequirement {
	long	*rteId	/* OPTIONAL */;
	long	*rtsId	/* OPTIONAL */;
	ParamInRsi_t	 paramInRsi;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RxRsiRequirement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RxRsiRequirement;
extern asn_SEQUENCE_specifics_t asn_SPC_RxRsiRequirement_specs_1;
extern asn_TYPE_member_t asn_MBR_RxRsiRequirement_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RxRsiRequirement_H_ */
#include <asn_internal.h>
