/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "RxRsiInfo.h"

asn_TYPE_member_t asn_MBR_RxRsiInfo_1[] = {
	{ ATF_POINTER, 3, offsetof(struct RxRsiInfo, basicRSI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BasicRSI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"basicRSI"
		},
	{ ATF_POINTER, 2, offsetof(struct RxRsiInfo, rteData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RteData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rteData"
		},
	{ ATF_POINTER, 1, offsetof(struct RxRsiInfo, rtsData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RtsData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rtsData"
		},
};
static const int asn_MAP_RxRsiInfo_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_RxRsiInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RxRsiInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* basicRSI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rteData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* rtsData */
};
asn_SEQUENCE_specifics_t asn_SPC_RxRsiInfo_specs_1 = {
	sizeof(struct RxRsiInfo),
	offsetof(struct RxRsiInfo, _asn_ctx),
	asn_MAP_RxRsiInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RxRsiInfo_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RxRsiInfo = {
	"RxRsiInfo",
	"RxRsiInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_RxRsiInfo_tags_1,
	sizeof(asn_DEF_RxRsiInfo_tags_1)
		/sizeof(asn_DEF_RxRsiInfo_tags_1[0]), /* 1 */
	asn_DEF_RxRsiInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_RxRsiInfo_tags_1)
		/sizeof(asn_DEF_RxRsiInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RxRsiInfo_1,
	3,	/* Elements count */
	&asn_SPC_RxRsiInfo_specs_1	/* Additional specs */
};

