/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_RxRsmInfo_H_
#define	_RxRsmInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BasicRSM;
struct PtcData;

/* RxRsmInfo */
typedef struct RxRsmInfo {
	struct BasicRSM	*basicRSM	/* OPTIONAL */;
	struct PtcData	*ptcData	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RxRsmInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RxRsmInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_RxRsmInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_RxRsmInfo_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BasicRSM.h"
#include "PtcData.h"

#endif	/* _RxRsmInfo_H_ */
#include <asn_internal.h>
