/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_SendCertReq_H_
#define	_SendCertReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SendCertReq */
typedef BOOLEAN_t	 SendCertReq_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SendCertReq_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SendCertReq;
asn_struct_free_f SendCertReq_free;
asn_struct_print_f SendCertReq_print;
asn_constr_check_f SendCertReq_constraint;
ber_type_decoder_f SendCertReq_decode_ber;
der_type_encoder_f SendCertReq_encode_der;
xer_type_decoder_f SendCertReq_decode_xer;
xer_type_encoder_f SendCertReq_encode_xer;
oer_type_decoder_f SendCertReq_decode_oer;
oer_type_encoder_f SendCertReq_encode_oer;
per_type_decoder_f SendCertReq_decode_uper;
per_type_encoder_f SendCertReq_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SendCertReq_H_ */
#include <asn_internal.h>
