/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_SetBsmInfo_H_
#define	_SetBsmInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BsmInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetBsmInfo */
typedef BsmInfo_t	 SetBsmInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetBsmInfo;
asn_struct_free_f SetBsmInfo_free;
asn_struct_print_f SetBsmInfo_print;
asn_constr_check_f SetBsmInfo_constraint;
ber_type_decoder_f SetBsmInfo_decode_ber;
der_type_encoder_f SetBsmInfo_encode_der;
xer_type_decoder_f SetBsmInfo_decode_xer;
xer_type_encoder_f SetBsmInfo_encode_xer;
oer_type_decoder_f SetBsmInfo_decode_oer;
oer_type_encoder_f SetBsmInfo_encode_oer;
per_type_decoder_f SetBsmInfo_decode_uper;
per_type_encoder_f SetBsmInfo_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SetBsmInfo_H_ */
#include <asn_internal.h>
