/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_SignerIdentifierType_H_
#define	_SignerIdentifierType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignerIdentifierType {
	SignerIdentifierType_digest	= 0,
	SignerIdentifierType_certificate	= 1
	/*
	 * Enumeration is extensible
	 */
} e_SignerIdentifierType;

/* SignerIdentifierType */
typedef long	 SignerIdentifierType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SignerIdentifierType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SignerIdentifierType;
extern const asn_INTEGER_specifics_t asn_SPC_SignerIdentifierType_specs_1;
asn_struct_free_f SignerIdentifierType_free;
asn_struct_print_f SignerIdentifierType_print;
asn_constr_check_f SignerIdentifierType_constraint;
ber_type_decoder_f SignerIdentifierType_decode_ber;
der_type_encoder_f SignerIdentifierType_encode_der;
xer_type_decoder_f SignerIdentifierType_decode_xer;
xer_type_encoder_f SignerIdentifierType_encode_xer;
oer_type_decoder_f SignerIdentifierType_decode_oer;
oer_type_encoder_f SignerIdentifierType_encode_oer;
per_type_decoder_f SignerIdentifierType_decode_uper;
per_type_encoder_f SignerIdentifierType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerIdentifierType_H_ */
#include <asn_internal.h>
