/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_StartSpduRx_H_
#define	_StartSpduRx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ApplicationType.h"
#include "TciSecMsgFrame_EventHandling.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StartSpduRx */
typedef struct StartSpduRx {
	ApplicationType_t	 appType;
	TciSecMsgFrame_EventHandling_t	 eventHandling;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartSpduRx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartSpduRx;
extern asn_SEQUENCE_specifics_t asn_SPC_StartSpduRx_specs_1;
extern asn_TYPE_member_t asn_MBR_StartSpduRx_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _StartSpduRx_H_ */
#include <asn_internal.h>
