/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "StartDsmRx.h"

asn_TYPE_member_t asn_MBR_StartDsmRx_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StartDsmRx, aid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_Aid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartDsmRx, eventHandling),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_EventHandling,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventHandling"
		},
};
static const ber_tlv_tag_t asn_DEF_StartDsmRx_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StartDsmRx_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eventHandling */
};
asn_SEQUENCE_specifics_t asn_SPC_StartDsmRx_specs_1 = {
	sizeof(struct StartDsmRx),
	offsetof(struct StartDsmRx, _asn_ctx),
	asn_MAP_StartDsmRx_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StartDsmRx = {
	"StartDsmRx",
	"StartDsmRx",
	&asn_OP_SEQUENCE,
	asn_DEF_StartDsmRx_tags_1,
	sizeof(asn_DEF_StartDsmRx_tags_1)
		/sizeof(asn_DEF_StartDsmRx_tags_1[0]), /* 1 */
	asn_DEF_StartDsmRx_tags_1,	/* Same as above */
	sizeof(asn_DEF_StartDsmRx_tags_1)
		/sizeof(asn_DEF_StartDsmRx_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_StartDsmRx_1,
	2,	/* Elements count */
	&asn_SPC_StartDsmRx_specs_1	/* Additional specs */
};

