/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_StartSpduTx_H_
#define	_StartSpduTx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ApplicationType.h"
#include "SignerIdentifierType.h"
#include "TciSecMsgFrame_RepeatRate.h"
#include "Opaque.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StartSpduTx */
typedef struct StartSpduTx {
	ApplicationType_t	 appType;
	SignerIdentifierType_t	 signerType;
	TciSecMsgFrame_RepeatRate_t	 repeatRate;
	Opaque_t	 data;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartSpduTx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartSpduTx;
extern asn_SEQUENCE_specifics_t asn_SPC_StartSpduTx_specs_1;
extern asn_TYPE_member_t asn_MBR_StartSpduTx_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _StartSpduTx_H_ */
#include <asn_internal.h>
