/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_StartMsgLayerRx_H_
#define	_StartMsgLayerRx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciMsgLayerFrame_Aid.h"
#include "TciMsgLayerFrame_EventHandling.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StartMsgLayerRx */
typedef struct StartMsgLayerRx {
	TciMsgLayerFrame_Aid_t	 aid;
	TciMsgLayerFrame_EventHandling_t	 eventHandling;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartMsgLayerRx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartMsgLayerRx;
extern asn_SEQUENCE_specifics_t asn_SPC_StartMsgLayerRx_specs_1;
extern asn_TYPE_member_t asn_MBR_StartMsgLayerRx_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _StartMsgLayerRx_H_ */
#include <asn_internal.h>
