/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "StartSpduTx.h"

asn_TYPE_member_t asn_MBR_StartSpduTx_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StartSpduTx, appType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicationType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"appType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartSpduTx, signerType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignerIdentifierType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signerType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartSpduTx, repeatRate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciSecMsgFrame_RepeatRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"repeatRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartSpduTx, data),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"data"
		},
};
static const ber_tlv_tag_t asn_DEF_StartSpduTx_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StartSpduTx_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* appType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* signerType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* repeatRate */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* data */
};
asn_SEQUENCE_specifics_t asn_SPC_StartSpduTx_specs_1 = {
	sizeof(struct StartSpduTx),
	offsetof(struct StartSpduTx, _asn_ctx),
	asn_MAP_StartSpduTx_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StartSpduTx = {
	"StartSpduTx",
	"StartSpduTx",
	&asn_OP_SEQUENCE,
	asn_DEF_StartSpduTx_tags_1,
	sizeof(asn_DEF_StartSpduTx_tags_1)
		/sizeof(asn_DEF_StartSpduTx_tags_1[0]), /* 1 */
	asn_DEF_StartSpduTx_tags_1,	/* Same as above */
	sizeof(asn_DEF_StartSpduTx_tags_1)
		/sizeof(asn_DEF_StartSpduTx_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_StartSpduTx_1,
	4,	/* Elements count */
	&asn_SPC_StartSpduTx_specs_1	/* Additional specs */
};

