/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_StopDsmTx_H_
#define	_StopDsmTx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciNetworkLayerFrame_Aid.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StopDsmTx */
typedef struct StopDsmTx {
	TciNetworkLayerFrame_Aid_t	 aid;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StopDsmTx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StopDsmTx;
extern asn_SEQUENCE_specifics_t asn_SPC_StopDsmTx_specs_1;
extern asn_TYPE_member_t asn_MBR_StopDsmTx_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _StopDsmTx_H_ */
#include <asn_internal.h>
