/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciMsgLayerFrame_Exception.h"

asn_TYPE_member_t asn_MBR_TciMsgLayerFrame_Exception_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TciMsgLayerFrame_Exception, eType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciMsgLayerFrame_ExceptionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciMsgLayerFrame_Exception, eId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciMsgLayerFrame_ExceptionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eId"
		},
	{ ATF_POINTER, 2, offsetof(struct TciMsgLayerFrame_Exception, eModule),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciMsgLayerFrame_Module,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eModule"
		},
	{ ATF_POINTER, 1, offsetof(struct TciMsgLayerFrame_Exception, eDescription),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciMsgLayerFrame_ExceptionText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eDescription"
		},
};
static const int asn_MAP_TciMsgLayerFrame_Exception_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_TciMsgLayerFrame_Exception_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TciMsgLayerFrame_Exception_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eModule */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* eDescription */
};
asn_SEQUENCE_specifics_t asn_SPC_TciMsgLayerFrame_Exception_specs_1 = {
	sizeof(struct TciMsgLayerFrame_Exception),
	offsetof(struct TciMsgLayerFrame_Exception, _asn_ctx),
	asn_MAP_TciMsgLayerFrame_Exception_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_TciMsgLayerFrame_Exception_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_Exception = {
	"Exception",
	"Exception",
	&asn_OP_SEQUENCE,
	asn_DEF_TciMsgLayerFrame_Exception_tags_1,
	sizeof(asn_DEF_TciMsgLayerFrame_Exception_tags_1)
		/sizeof(asn_DEF_TciMsgLayerFrame_Exception_tags_1[0]), /* 1 */
	asn_DEF_TciMsgLayerFrame_Exception_tags_1,	/* Same as above */
	sizeof(asn_DEF_TciMsgLayerFrame_Exception_tags_1)
		/sizeof(asn_DEF_TciMsgLayerFrame_Exception_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TciMsgLayerFrame_Exception_1,
	4,	/* Elements count */
	&asn_SPC_TciMsgLayerFrame_Exception_specs_1	/* Additional specs */
};

