/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciMsgLayerFrame_RxFlag_H_
#define	_TciMsgLayerFrame_RxFlag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciMsgLayerFrame_RxFlag {
	TciMsgLayerFrame_RxFlag_recvAidMatch	= 0,
	TciMsgLayerFrame_RxFlag_recvAllMsg	= 1
	/*
	 * Enumeration is extensible
	 */
} e_TciMsgLayerFrame_RxFlag;

/* RxFlag */
typedef long	 TciMsgLayerFrame_RxFlag_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TciMsgLayerFrame_RxFlag_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_RxFlag;
extern const asn_INTEGER_specifics_t asn_SPC_TciMsgLayerFrame_RxFlag_specs_1;
asn_struct_free_f TciMsgLayerFrame_RxFlag_free;
asn_struct_print_f TciMsgLayerFrame_RxFlag_print;
asn_constr_check_f TciMsgLayerFrame_RxFlag_constraint;
ber_type_decoder_f TciMsgLayerFrame_RxFlag_decode_ber;
der_type_encoder_f TciMsgLayerFrame_RxFlag_encode_der;
xer_type_decoder_f TciMsgLayerFrame_RxFlag_decode_xer;
xer_type_encoder_f TciMsgLayerFrame_RxFlag_encode_xer;
oer_type_decoder_f TciMsgLayerFrame_RxFlag_decode_oer;
oer_type_encoder_f TciMsgLayerFrame_RxFlag_encode_oer;
per_type_decoder_f TciMsgLayerFrame_RxFlag_decode_uper;
per_type_encoder_f TciMsgLayerFrame_RxFlag_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TciMsgLayerFrame_RxFlag_H_ */
#include <asn_internal.h>
