/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciMsgLayerFrame_Event.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_TciMsgLayerFrame_Event_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TciMsgLayerFrame_Event_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_TciMsgLayerFrame_Event_value2enum_1[] = {
	{ 0,	6,	"eBsmRx" },
	{ 1,	6,	"eMapRx" },
	{ 2,	6,	"eRsmRx" },
	{ 3,	7,	"eSpatRx" },
	{ 4,	6,	"eRsiRx" },
	{ 5,	15,	"exceptionReport" }
};
static const unsigned int asn_MAP_TciMsgLayerFrame_Event_enum2value_1[] = {
	0,	/* eBsmRx(0) */
	1,	/* eMapRx(1) */
	4,	/* eRsiRx(4) */
	2,	/* eRsmRx(2) */
	3,	/* eSpatRx(3) */
	5	/* exceptionReport(5) */
};
const asn_INTEGER_specifics_t asn_SPC_TciMsgLayerFrame_Event_specs_1 = {
	asn_MAP_TciMsgLayerFrame_Event_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_TciMsgLayerFrame_Event_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_TciMsgLayerFrame_Event_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_Event = {
	"Event",
	"Event",
	&asn_OP_NativeEnumerated,
	asn_DEF_TciMsgLayerFrame_Event_tags_1,
	sizeof(asn_DEF_TciMsgLayerFrame_Event_tags_1)
		/sizeof(asn_DEF_TciMsgLayerFrame_Event_tags_1[0]), /* 1 */
	asn_DEF_TciMsgLayerFrame_Event_tags_1,	/* Same as above */
	sizeof(asn_DEF_TciMsgLayerFrame_Event_tags_1)
		/sizeof(asn_DEF_TciMsgLayerFrame_Event_tags_1[0]), /* 1 */
	{ &asn_OER_type_TciMsgLayerFrame_Event_constr_1, &asn_PER_type_TciMsgLayerFrame_Event_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_TciMsgLayerFrame_Event_specs_1	/* Additional specs */
};

