/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciMsgLayerFrame_Request_H_
#define	_TciMsgLayerFrame_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciMsgLayerFrame_MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "TciMsgLayerFrame_SetInitialState.h"
#include "StartMsgLayerTx.h"
#include "StopMsgLayerTx.h"
#include "StartMsgLayerRx.h"
#include "StopMsgLayerRx.h"
#include "SetBsmInfo.h"
#include "SetRsmInfo.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciMsgLayerFrame_Request__value_PR {
	TciMsgLayerFrame_Request__value_PR_NOTHING,	/* No components present */
	TciMsgLayerFrame_Request__value_PR_SetInitialState,
	TciMsgLayerFrame_Request__value_PR_StartMsgLayerTx,
	TciMsgLayerFrame_Request__value_PR_StopMsgLayerTx,
	TciMsgLayerFrame_Request__value_PR_StartMsgLayerRx,
	TciMsgLayerFrame_Request__value_PR_StopMsgLayerRx,
	TciMsgLayerFrame_Request__value_PR_SetBsmInfo,
	TciMsgLayerFrame_Request__value_PR_SetRsmInfo
} TciMsgLayerFrame_Request__value_PR;

/* Request */
typedef struct TciMsgLayerFrame_Request {
	TciMsgLayerFrame_MsgID_t	 msgId;
	struct TciMsgLayerFrame_Request__value {
		TciMsgLayerFrame_Request__value_PR present;
		union TciMsgLayerFrame_Request__value_u {
			TciMsgLayerFrame_SetInitialState_t	 SetInitialState;
			StartMsgLayerTx_t	 StartMsgLayerTx;
			StopMsgLayerTx_t	 StopMsgLayerTx;
			StartMsgLayerRx_t	 StartMsgLayerRx;
			StopMsgLayerRx_t	 StopMsgLayerRx;
			SetBsmInfo_t	 SetBsmInfo;
			SetRsmInfo_t	 SetRsmInfo;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciMsgLayerFrame_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_TciMsgLayerFrame_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_TciMsgLayerFrame_Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TciMsgLayerFrame_Request_H_ */
#include <asn_internal.h>
