/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciMsgLayerFrame_TciMsgFrame_H_
#define	_TciMsgLayerFrame_TciMsgFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciMsgLayerFrame_Request.h"
#include "TciMsgLayerFrame_Response.h"
#include "TciMsgLayerFrame_Indication.h"
#include "TciMsgLayerFrame_Exception.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciMsgLayerFrame_TciMsgFrame_PR {
	TciMsgLayerFrame_TciMsgFrame_PR_NOTHING,	/* No components present */
	TciMsgLayerFrame_TciMsgFrame_PR_request,
	TciMsgLayerFrame_TciMsgFrame_PR_response,
	TciMsgLayerFrame_TciMsgFrame_PR_indication,
	TciMsgLayerFrame_TciMsgFrame_PR_exceptionInfo
	/* Extensions may appear below */
	
} TciMsgLayerFrame_TciMsgFrame_PR;

/* TciMsgFrame */
typedef struct TciMsgLayerFrame_TciMsgFrame {
	TciMsgLayerFrame_TciMsgFrame_PR present;
	union TciMsgLayerFrame_TciMsgFrame_u {
		TciMsgLayerFrame_Request_t	 request;
		TciMsgLayerFrame_Response_t	 response;
		TciMsgLayerFrame_Indication_t	 indication;
		TciMsgLayerFrame_Exception_t	 exceptionInfo;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciMsgLayerFrame_TciMsgFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_TciMsgFrame;
extern asn_CHOICE_specifics_t asn_SPC_TciMsgLayerFrame_TciMsgFrame_specs_1;
extern asn_TYPE_member_t asn_MBR_TciMsgLayerFrame_TciMsgFrame_1[4];
extern asn_per_constraints_t asn_PER_type_TciMsgLayerFrame_TciMsgFrame_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TciMsgLayerFrame_TciMsgFrame_H_ */
#include <asn_internal.h>
