/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciMsgLayerFrame_ResultCode_H_
#define	_TciMsgLayerFrame_ResultCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciMsgLayerFrame_ResultCode {
	TciMsgLayerFrame_ResultCode_rcSuccess	= 0,
	TciMsgLayerFrame_ResultCode_rcFailure	= 1
} e_TciMsgLayerFrame_ResultCode;

/* ResultCode */
typedef long	 TciMsgLayerFrame_ResultCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TciMsgLayerFrame_ResultCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_ResultCode;
extern const asn_INTEGER_specifics_t asn_SPC_TciMsgLayerFrame_ResultCode_specs_1;
asn_struct_free_f TciMsgLayerFrame_ResultCode_free;
asn_struct_print_f TciMsgLayerFrame_ResultCode_print;
asn_constr_check_f TciMsgLayerFrame_ResultCode_constraint;
ber_type_decoder_f TciMsgLayerFrame_ResultCode_decode_ber;
der_type_encoder_f TciMsgLayerFrame_ResultCode_encode_der;
xer_type_decoder_f TciMsgLayerFrame_ResultCode_decode_xer;
xer_type_encoder_f TciMsgLayerFrame_ResultCode_encode_xer;
oer_type_decoder_f TciMsgLayerFrame_ResultCode_decode_oer;
oer_type_encoder_f TciMsgLayerFrame_ResultCode_encode_oer;
per_type_decoder_f TciMsgLayerFrame_ResultCode_decode_uper;
per_type_encoder_f TciMsgLayerFrame_ResultCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TciMsgLayerFrame_ResultCode_H_ */
#include <asn_internal.h>
