/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciMsgLayerFrame_EventHandling.h"

asn_TYPE_member_t asn_MBR_TciMsgLayerFrame_EventHandling_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TciMsgLayerFrame_EventHandling, rxFlag),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciMsgLayerFrame_RxFlag,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxFlag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciMsgLayerFrame_EventHandling, rxPduType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RxPduParamFlag,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxPduType"
		},
};
static const ber_tlv_tag_t asn_DEF_TciMsgLayerFrame_EventHandling_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TciMsgLayerFrame_EventHandling_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rxFlag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rxPduType */
};
asn_SEQUENCE_specifics_t asn_SPC_TciMsgLayerFrame_EventHandling_specs_1 = {
	sizeof(struct TciMsgLayerFrame_EventHandling),
	offsetof(struct TciMsgLayerFrame_EventHandling, _asn_ctx),
	asn_MAP_TciMsgLayerFrame_EventHandling_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TciMsgLayerFrame_EventHandling = {
	"EventHandling",
	"EventHandling",
	&asn_OP_SEQUENCE,
	asn_DEF_TciMsgLayerFrame_EventHandling_tags_1,
	sizeof(asn_DEF_TciMsgLayerFrame_EventHandling_tags_1)
		/sizeof(asn_DEF_TciMsgLayerFrame_EventHandling_tags_1[0]), /* 1 */
	asn_DEF_TciMsgLayerFrame_EventHandling_tags_1,	/* Same as above */
	sizeof(asn_DEF_TciMsgLayerFrame_EventHandling_tags_1)
		/sizeof(asn_DEF_TciMsgLayerFrame_EventHandling_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TciMsgLayerFrame_EventHandling_1,
	2,	/* Elements count */
	&asn_SPC_TciMsgLayerFrame_EventHandling_specs_1	/* Additional specs */
};

