/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciNetworkLayerFrame_ExceptionType_H_
#define	_TciNetworkLayerFrame_ExceptionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciNetworkLayerFrame_ExceptionType {
	TciNetworkLayerFrame_ExceptionType_info	= 0,
	TciNetworkLayerFrame_ExceptionType_warning	= 1,
	TciNetworkLayerFrame_ExceptionType_error	= 2
} e_TciNetworkLayerFrame_ExceptionType;

/* ExceptionType */
typedef long	 TciNetworkLayerFrame_ExceptionType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TciNetworkLayerFrame_ExceptionType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TciNetworkLayerFrame_ExceptionType;
extern const asn_INTEGER_specifics_t asn_SPC_TciNetworkLayerFrame_ExceptionType_specs_1;
asn_struct_free_f TciNetworkLayerFrame_ExceptionType_free;
asn_struct_print_f TciNetworkLayerFrame_ExceptionType_print;
asn_constr_check_f TciNetworkLayerFrame_ExceptionType_constraint;
ber_type_decoder_f TciNetworkLayerFrame_ExceptionType_decode_ber;
der_type_encoder_f TciNetworkLayerFrame_ExceptionType_encode_der;
xer_type_decoder_f TciNetworkLayerFrame_ExceptionType_decode_xer;
xer_type_encoder_f TciNetworkLayerFrame_ExceptionType_encode_xer;
oer_type_decoder_f TciNetworkLayerFrame_ExceptionType_decode_oer;
oer_type_encoder_f TciNetworkLayerFrame_ExceptionType_encode_oer;
per_type_decoder_f TciNetworkLayerFrame_ExceptionType_decode_uper;
per_type_encoder_f TciNetworkLayerFrame_ExceptionType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TciNetworkLayerFrame_ExceptionType_H_ */
#include <asn_internal.h>
