/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciNetworkLayerFrame_TciMsgFrame.h"

static asn_oer_constraints_t asn_OER_type_TciNetworkLayerFrame_TciMsgFrame_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TciNetworkLayerFrame_TciMsgFrame_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TciNetworkLayerFrame_TciMsgFrame_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TciNetworkLayerFrame_TciMsgFrame, choice.request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_Request,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciNetworkLayerFrame_TciMsgFrame, choice.response),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_Response,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciNetworkLayerFrame_TciMsgFrame, choice.indication),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_Indication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciNetworkLayerFrame_TciMsgFrame, choice.exceptionInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciNetworkLayerFrame_Exception,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exceptionInfo"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TciNetworkLayerFrame_TciMsgFrame_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* request */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* response */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indication */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* exceptionInfo */
};
asn_CHOICE_specifics_t asn_SPC_TciNetworkLayerFrame_TciMsgFrame_specs_1 = {
	sizeof(struct TciNetworkLayerFrame_TciMsgFrame),
	offsetof(struct TciNetworkLayerFrame_TciMsgFrame, _asn_ctx),
	offsetof(struct TciNetworkLayerFrame_TciMsgFrame, present),
	sizeof(((struct TciNetworkLayerFrame_TciMsgFrame *)0)->present),
	asn_MAP_TciNetworkLayerFrame_TciMsgFrame_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TciNetworkLayerFrame_TciMsgFrame = {
	"TciMsgFrame",
	"TciMsgFrame",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TciNetworkLayerFrame_TciMsgFrame_constr_1, &asn_PER_type_TciNetworkLayerFrame_TciMsgFrame_constr_1, CHOICE_constraint },
	asn_MBR_TciNetworkLayerFrame_TciMsgFrame_1,
	4,	/* Elements count */
	&asn_SPC_TciNetworkLayerFrame_TciMsgFrame_specs_1	/* Additional specs */
};

