/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciNetworkLayerFrame_Request_H_
#define	_TciNetworkLayerFrame_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciNetworkLayerFrame_MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "TciNetworkLayerFrame_SetInitialState.h"
#include "StartDsmTx.h"
#include "StopDsmTx.h"
#include "StartDsmRx.h"
#include "StopDsmRx.h"
#include "SetMibInfo.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciNetworkLayerFrame_Request__value_PR {
	TciNetworkLayerFrame_Request__value_PR_NOTHING,	/* No components present */
	TciNetworkLayerFrame_Request__value_PR_SetInitialState,
	TciNetworkLayerFrame_Request__value_PR_StartDsmTx,
	TciNetworkLayerFrame_Request__value_PR_StopDsmTx,
	TciNetworkLayerFrame_Request__value_PR_StartDsmRx,
	TciNetworkLayerFrame_Request__value_PR_StopDsmRx,
	TciNetworkLayerFrame_Request__value_PR_SetMibInfo
} TciNetworkLayerFrame_Request__value_PR;

/* Request */
typedef struct TciNetworkLayerFrame_Request {
	TciNetworkLayerFrame_MsgID_t	 msgId;
	struct TciNetworkLayerFrame_Request__value {
		TciNetworkLayerFrame_Request__value_PR present;
		union TciNetworkLayerFrame_Request__value_u {
			TciNetworkLayerFrame_SetInitialState_t	 SetInitialState;
			StartDsmTx_t	 StartDsmTx;
			StopDsmTx_t	 StopDsmTx;
			StartDsmRx_t	 StartDsmRx;
			StopDsmRx_t	 StopDsmRx;
			SetMibInfo_t	 SetMibInfo;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciNetworkLayerFrame_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciNetworkLayerFrame_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_TciNetworkLayerFrame_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_TciNetworkLayerFrame_Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TciNetworkLayerFrame_Request_H_ */
#include <asn_internal.h>
