/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciNetworkLayerFrame_Event_H_
#define	_TciNetworkLayerFrame_Event_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciNetworkLayerFrame_Event {
	TciNetworkLayerFrame_Event_eDsmRx	= 0,
	TciNetworkLayerFrame_Event_exceptionReport	= 1
} e_TciNetworkLayerFrame_Event;

/* Event */
typedef long	 TciNetworkLayerFrame_Event_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TciNetworkLayerFrame_Event_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TciNetworkLayerFrame_Event;
extern const asn_INTEGER_specifics_t asn_SPC_TciNetworkLayerFrame_Event_specs_1;
asn_struct_free_f TciNetworkLayerFrame_Event_free;
asn_struct_print_f TciNetworkLayerFrame_Event_print;
asn_constr_check_f TciNetworkLayerFrame_Event_constraint;
ber_type_decoder_f TciNetworkLayerFrame_Event_decode_ber;
der_type_encoder_f TciNetworkLayerFrame_Event_encode_der;
xer_type_decoder_f TciNetworkLayerFrame_Event_decode_xer;
xer_type_encoder_f TciNetworkLayerFrame_Event_encode_xer;
oer_type_decoder_f TciNetworkLayerFrame_Event_decode_oer;
oer_type_encoder_f TciNetworkLayerFrame_Event_encode_oer;
per_type_decoder_f TciNetworkLayerFrame_Event_decode_uper;
per_type_encoder_f TciNetworkLayerFrame_Event_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TciNetworkLayerFrame_Event_H_ */
#include <asn_internal.h>
