/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciNetworkLayerFrame_ExceptionId_H_
#define	_TciNetworkLayerFrame_ExceptionId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciNetworkLayerFrame_ExceptionId {
	TciNetworkLayerFrame_ExceptionId_criticalError	= 1,
	TciNetworkLayerFrame_ExceptionId_incorrectParameterValue	= 2,
	TciNetworkLayerFrame_ExceptionId_missingParameter	= 3,
	TciNetworkLayerFrame_ExceptionId_radioInterfaceUnavailable	= 4,
	TciNetworkLayerFrame_ExceptionId_incorrectDsmMaxLength	= 5
	/*
	 * Enumeration is extensible
	 */
} e_TciNetworkLayerFrame_ExceptionId;

/* ExceptionId */
typedef long	 TciNetworkLayerFrame_ExceptionId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TciNetworkLayerFrame_ExceptionId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TciNetworkLayerFrame_ExceptionId;
extern const asn_INTEGER_specifics_t asn_SPC_TciNetworkLayerFrame_ExceptionId_specs_1;
asn_struct_free_f TciNetworkLayerFrame_ExceptionId_free;
asn_struct_print_f TciNetworkLayerFrame_ExceptionId_print;
asn_constr_check_f TciNetworkLayerFrame_ExceptionId_constraint;
ber_type_decoder_f TciNetworkLayerFrame_ExceptionId_decode_ber;
der_type_encoder_f TciNetworkLayerFrame_ExceptionId_encode_der;
xer_type_decoder_f TciNetworkLayerFrame_ExceptionId_decode_xer;
xer_type_encoder_f TciNetworkLayerFrame_ExceptionId_encode_xer;
oer_type_decoder_f TciNetworkLayerFrame_ExceptionId_decode_oer;
oer_type_encoder_f TciNetworkLayerFrame_ExceptionId_encode_oer;
per_type_decoder_f TciNetworkLayerFrame_ExceptionId_decode_uper;
per_type_encoder_f TciNetworkLayerFrame_ExceptionId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TciNetworkLayerFrame_ExceptionId_H_ */
#include <asn_internal.h>
