/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciNetworkLayerFrame"
 * 	found in "asn/net_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciNetworkLayerFrame_SetInitialState.h"

int
TciNetworkLayerFrame_SetInitialState_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	BOOLEAN_t value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = (*(const long *)sptr) ? 1 : 0;
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using BOOLEAN,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_TciNetworkLayerFrame_SetInitialState_constr_1 CC_NOTUSED = {
	{ 1, 1 }	/* (1..1) */,
	-1};
asn_per_constraints_t asn_PER_type_TciNetworkLayerFrame_SetInitialState_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  1,  1 }	/* (1..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (1 << 2))
};
asn_TYPE_descriptor_t asn_DEF_TciNetworkLayerFrame_SetInitialState = {
	"SetInitialState",
	"SetInitialState",
	&asn_OP_BOOLEAN,
	asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1,
	sizeof(asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1)
		/sizeof(asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1[0]), /* 1 */
	asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1,	/* Same as above */
	sizeof(asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1)
		/sizeof(asn_DEF_TciNetworkLayerFrame_SetInitialState_tags_1[0]), /* 1 */
	{ &asn_OER_type_TciNetworkLayerFrame_SetInitialState_constr_1, &asn_PER_type_TciNetworkLayerFrame_SetInitialState_constr_1, TciNetworkLayerFrame_SetInitialState_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

