/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciSecMsgFrame_TciMsgFrame_H_
#define	_TciSecMsgFrame_TciMsgFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciSecMsgFrame_Request.h"
#include "TciSecMsgFrame_Response.h"
#include "TciSecMsgFrame_Indication.h"
#include "TciSecMsgFrame_Exception.h"
#include "CertInterface.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciSecMsgFrame_TciMsgFrame_PR {
	TciSecMsgFrame_TciMsgFrame_PR_NOTHING,	/* No components present */
	TciSecMsgFrame_TciMsgFrame_PR_request,
	TciSecMsgFrame_TciMsgFrame_PR_response,
	TciSecMsgFrame_TciMsgFrame_PR_indication,
	TciSecMsgFrame_TciMsgFrame_PR_exceptionInfo,
	TciSecMsgFrame_TciMsgFrame_PR_certInterface
	/* Extensions may appear below */
	
} TciSecMsgFrame_TciMsgFrame_PR;

/* TciMsgFrame */
typedef struct TciSecMsgFrame_TciMsgFrame {
	TciSecMsgFrame_TciMsgFrame_PR present;
	union TciSecMsgFrame_TciMsgFrame_u {
		TciSecMsgFrame_Request_t	 request;
		TciSecMsgFrame_Response_t	 response;
		TciSecMsgFrame_Indication_t	 indication;
		TciSecMsgFrame_Exception_t	 exceptionInfo;
		CertInterface_t	 certInterface;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciSecMsgFrame_TciMsgFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciSecMsgFrame_TciMsgFrame;
extern asn_CHOICE_specifics_t asn_SPC_TciSecMsgFrame_TciMsgFrame_specs_1;
extern asn_TYPE_member_t asn_MBR_TciSecMsgFrame_TciMsgFrame_1[5];
extern asn_per_constraints_t asn_PER_type_TciSecMsgFrame_TciMsgFrame_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TciSecMsgFrame_TciMsgFrame_H_ */
#include <asn_internal.h>
