/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciSecMsgFrame_Response_H_
#define	_TciSecMsgFrame_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciSecMsgFrame_MsgID.h"
#include "TciSecMsgFrame_ResultCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Exception;

/* Response */
typedef struct TciSecMsgFrame_Response {
	TciSecMsgFrame_MsgID_t	 msgId;
	TciSecMsgFrame_ResultCode_t	 resultCode;
	struct Exception	*exception	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciSecMsgFrame_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciSecMsgFrame_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_TciSecMsgFrame_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_TciSecMsgFrame_Response_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TciSecMsgFrame_Exception.h"

#endif	/* _TciSecMsgFrame_Response_H_ */
#include <asn_internal.h>
