/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciSecMsgFrame_EventHandling_H_
#define	_TciSecMsgFrame_EventHandling_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciSecMsgFrame_RxFlag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EventHandling */
typedef struct TciSecMsgFrame_EventHandling {
	TciSecMsgFrame_RxFlag_t	 rxFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciSecMsgFrame_EventHandling_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciSecMsgFrame_EventHandling;
extern asn_SEQUENCE_specifics_t asn_SPC_TciSecMsgFrame_EventHandling_specs_1;
extern asn_TYPE_member_t asn_MBR_TciSecMsgFrame_EventHandling_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _TciSecMsgFrame_EventHandling_H_ */
#include <asn_internal.h>
