/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciSecMsgFrame_Event.h"

static asn_oer_constraints_t asn_OER_type_TciSecMsgFrame_Event_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TciSecMsgFrame_Event_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TciSecMsgFrame_Event_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_Event, choice.availableSpdu),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AvailableSpdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"availableSpdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_Event, choice.incorrectSpdu),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IncorrectSpdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"incorrectSpdu"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TciSecMsgFrame_Event_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* availableSpdu */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* incorrectSpdu */
};
asn_CHOICE_specifics_t asn_SPC_TciSecMsgFrame_Event_specs_1 = {
	sizeof(struct TciSecMsgFrame_Event),
	offsetof(struct TciSecMsgFrame_Event, _asn_ctx),
	offsetof(struct TciSecMsgFrame_Event, present),
	sizeof(((struct TciSecMsgFrame_Event *)0)->present),
	asn_MAP_TciSecMsgFrame_Event_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TciSecMsgFrame_Event = {
	"Event",
	"Event",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TciSecMsgFrame_Event_constr_1, &asn_PER_type_TciSecMsgFrame_Event_constr_1, CHOICE_constraint },
	asn_MBR_TciSecMsgFrame_Event_1,
	2,	/* Elements count */
	&asn_SPC_TciSecMsgFrame_Event_specs_1	/* Additional specs */
};

