/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "TciSecMsgFrame_TciMsgFrame.h"

static asn_oer_constraints_t asn_OER_type_TciSecMsgFrame_TciMsgFrame_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TciSecMsgFrame_TciMsgFrame_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TciSecMsgFrame_TciMsgFrame_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_TciMsgFrame, choice.request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciSecMsgFrame_Request,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_TciMsgFrame, choice.response),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciSecMsgFrame_Response,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_TciMsgFrame, choice.indication),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciSecMsgFrame_Indication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_TciMsgFrame, choice.exceptionInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TciSecMsgFrame_Exception,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exceptionInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TciSecMsgFrame_TciMsgFrame, choice.certInterface),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CertInterface,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certInterface"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TciSecMsgFrame_TciMsgFrame_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* request */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* response */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indication */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* exceptionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* certInterface */
};
asn_CHOICE_specifics_t asn_SPC_TciSecMsgFrame_TciMsgFrame_specs_1 = {
	sizeof(struct TciSecMsgFrame_TciMsgFrame),
	offsetof(struct TciSecMsgFrame_TciMsgFrame, _asn_ctx),
	offsetof(struct TciSecMsgFrame_TciMsgFrame, present),
	sizeof(((struct TciSecMsgFrame_TciMsgFrame *)0)->present),
	asn_MAP_TciSecMsgFrame_TciMsgFrame_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TciSecMsgFrame_TciMsgFrame = {
	"TciMsgFrame",
	"TciMsgFrame",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TciSecMsgFrame_TciMsgFrame_constr_1, &asn_PER_type_TciSecMsgFrame_TciMsgFrame_constr_1, CHOICE_constraint },
	asn_MBR_TciSecMsgFrame_TciMsgFrame_1,
	5,	/* Elements count */
	&asn_SPC_TciSecMsgFrame_TciMsgFrame_specs_1	/* Additional specs */
};

