/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciSecMsgFrame"
 * 	found in "asn/sec_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TciSecMsgFrame_Request_H_
#define	_TciSecMsgFrame_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TciSecMsgFrame_MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "TciSecMsgFrame_SetInitialState.h"
#include "StartSpduTx.h"
#include "StopSpduTx.h"
#include "StartSpduRx.h"
#include "StopSpduRx.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TciSecMsgFrame_Request__value_PR {
	TciSecMsgFrame_Request__value_PR_NOTHING,	/* No components present */
	TciSecMsgFrame_Request__value_PR_SetInitialState,
	TciSecMsgFrame_Request__value_PR_StartSpduTx,
	TciSecMsgFrame_Request__value_PR_StopSpduTx,
	TciSecMsgFrame_Request__value_PR_StartSpduRx,
	TciSecMsgFrame_Request__value_PR_StopSpduRx
} TciSecMsgFrame_Request__value_PR;

/* Request */
typedef struct TciSecMsgFrame_Request {
	TciSecMsgFrame_MsgID_t	 msgId;
	struct TciSecMsgFrame_Request__value {
		TciSecMsgFrame_Request__value_PR present;
		union TciSecMsgFrame_Request__value_u {
			TciSecMsgFrame_SetInitialState_t	 SetInitialState;
			StartSpduTx_t	 StartSpduTx;
			StopSpduTx_t	 StopSpduTx;
			StartSpduRx_t	 StartSpduRx;
			StopSpduRx_t	 StopSpduRx;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TciSecMsgFrame_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TciSecMsgFrame_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_TciSecMsgFrame_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_TciSecMsgFrame_Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TciSecMsgFrame_Request_H_ */
#include <asn_internal.h>
