/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_TestVehicleInfo_H_
#define	_TestVehicleInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TestPosition3D.h"
#include "VehHeading.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestVehicleInfo */
typedef struct TestVehicleInfo {
	TestPosition3D_t	 vehPosition;
	VehHeading_t	 vehHeading;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestVehicleInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestVehicleInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_TestVehicleInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_TestVehicleInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TestVehicleInfo_H_ */
#include <asn_internal.h>
