/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_VehBrakeSystemStatus_H_
#define	_VehBrakeSystemStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehBrakeSystemStatus__brakePedalStatus {
	VehBrakeSystemStatus__brakePedalStatus_unavailable	= 0,
	VehBrakeSystemStatus__brakePedalStatus_off	= 1,
	VehBrakeSystemStatus__brakePedalStatus_on	= 2
} e_VehBrakeSystemStatus__brakePedalStatus;
typedef enum VehBrakeSystemStatus__brakeAppliedStatus {
	VehBrakeSystemStatus__brakeAppliedStatus_unavailable	= 0,
	VehBrakeSystemStatus__brakeAppliedStatus_leftFront	= 1,
	VehBrakeSystemStatus__brakeAppliedStatus_leftRear	= 2,
	VehBrakeSystemStatus__brakeAppliedStatus_rightFront	= 3,
	VehBrakeSystemStatus__brakeAppliedStatus_rightRear	= 4
} e_VehBrakeSystemStatus__brakeAppliedStatus;
typedef enum VehBrakeSystemStatus__tractionControlStatus {
	VehBrakeSystemStatus__tractionControlStatus_unavailable	= 0,
	VehBrakeSystemStatus__tractionControlStatus_off	= 1,
	VehBrakeSystemStatus__tractionControlStatus_on	= 2,
	VehBrakeSystemStatus__tractionControlStatus_engaged	= 3
} e_VehBrakeSystemStatus__tractionControlStatus;
typedef enum VehBrakeSystemStatus__antiLockBrakeStatus {
	VehBrakeSystemStatus__antiLockBrakeStatus_unavailable	= 0,
	VehBrakeSystemStatus__antiLockBrakeStatus_off	= 1,
	VehBrakeSystemStatus__antiLockBrakeStatus_on	= 2,
	VehBrakeSystemStatus__antiLockBrakeStatus_engaged	= 3
} e_VehBrakeSystemStatus__antiLockBrakeStatus;
typedef enum VehBrakeSystemStatus__stabilityControlStatus {
	VehBrakeSystemStatus__stabilityControlStatus_unavailable	= 0,
	VehBrakeSystemStatus__stabilityControlStatus_off	= 1,
	VehBrakeSystemStatus__stabilityControlStatus_on	= 2,
	VehBrakeSystemStatus__stabilityControlStatus_engaged	= 3
} e_VehBrakeSystemStatus__stabilityControlStatus;
typedef enum VehBrakeSystemStatus__brakeBoostApplied {
	VehBrakeSystemStatus__brakeBoostApplied_unavailable	= 0,
	VehBrakeSystemStatus__brakeBoostApplied_off	= 1,
	VehBrakeSystemStatus__brakeBoostApplied_on	= 2
} e_VehBrakeSystemStatus__brakeBoostApplied;
typedef enum VehBrakeSystemStatus__auxiliaryBrakeStatus {
	VehBrakeSystemStatus__auxiliaryBrakeStatus_unavailable	= 0,
	VehBrakeSystemStatus__auxiliaryBrakeStatus_off	= 1,
	VehBrakeSystemStatus__auxiliaryBrakeStatus_on	= 2,
	VehBrakeSystemStatus__auxiliaryBrakeStatus_reserved	= 3
} e_VehBrakeSystemStatus__auxiliaryBrakeStatus;

/* VehBrakeSystemStatus */
typedef struct VehBrakeSystemStatus {
	BIT_STRING_t	 brakePedalStatus;
	BIT_STRING_t	 brakeAppliedStatus;
	BIT_STRING_t	 tractionControlStatus;
	BIT_STRING_t	 antiLockBrakeStatus;
	BIT_STRING_t	 stabilityControlStatus;
	BIT_STRING_t	 brakeBoostApplied;
	BIT_STRING_t	 auxiliaryBrakeStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehBrakeSystemStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehBrakeSystemStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_VehBrakeSystemStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_VehBrakeSystemStatus_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _VehBrakeSystemStatus_H_ */
#include <asn_internal.h>
