/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_VehEmergencyExtensions_H_
#define	_VehEmergencyExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehEmergencyExtensions__responseType {
	VehEmergencyExtensions__responseType_notInUseOrNotEquipped	= 0,
	VehEmergencyExtensions__responseType_emergency	= 1,
	VehEmergencyExtensions__responseType_nonEmergency	= 2,
	VehEmergencyExtensions__responseType_pursuit	= 3,
	VehEmergencyExtensions__responseType_stationary	= 4,
	VehEmergencyExtensions__responseType_slowMoving	= 5,
	VehEmergencyExtensions__responseType_stopAndGoMovement	= 6
} e_VehEmergencyExtensions__responseType;
typedef enum VehEmergencyExtensions__sirenInUse {
	VehEmergencyExtensions__sirenInUse_unavailable	= 0,
	VehEmergencyExtensions__sirenInUse_notInUse	= 1,
	VehEmergencyExtensions__sirenInUse_inUse	= 2,
	VehEmergencyExtensions__sirenInUse_reserved	= 3
} e_VehEmergencyExtensions__sirenInUse;
typedef enum VehEmergencyExtensions__lightbarInUse {
	VehEmergencyExtensions__lightbarInUse_unavailable	= 0,
	VehEmergencyExtensions__lightbarInUse_notInUse	= 1,
	VehEmergencyExtensions__lightbarInUse_inUse	= 2,
	VehEmergencyExtensions__lightbarInUse_yellowCautionLights	= 3,
	VehEmergencyExtensions__lightbarInUse_schooldBusLights	= 4,
	VehEmergencyExtensions__lightbarInUse_arrowSignsActive	= 5,
	VehEmergencyExtensions__lightbarInUse_slowMovingVehicle	= 6,
	VehEmergencyExtensions__lightbarInUse_freqStops	= 7
} e_VehEmergencyExtensions__lightbarInUse;

/* VehEmergencyExtensions */
typedef struct VehEmergencyExtensions {
	BIT_STRING_t	 responseType;
	BIT_STRING_t	 sirenInUse;
	BIT_STRING_t	 lightbarInUse;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehEmergencyExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehEmergencyExtensions;
extern asn_SEQUENCE_specifics_t asn_SPC_VehEmergencyExtensions_specs_1;
extern asn_TYPE_member_t asn_MBR_VehEmergencyExtensions_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _VehEmergencyExtensions_H_ */
#include <asn_internal.h>
