/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_VehEventFlags_H_
#define	_VehEventFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehEventFlags {
	VehEventFlags_eventHazardLights	= 0,
	VehEventFlags_eventStopLineViolation	= 1,
	VehEventFlags_eventABSactivated	= 2,
	VehEventFlags_eventTractionControlLoss	= 3,
	VehEventFlags_eventStabilityControlactivated	= 4,
	VehEventFlags_eventHazardousMaterials	= 5,
	VehEventFlags_eventReserved1	= 6,
	VehEventFlags_eventHardBraking	= 7,
	VehEventFlags_eventLightsChanged	= 8,
	VehEventFlags_eventWipersChanged	= 9,
	VehEventFlags_eventFlatTire	= 10,
	VehEventFlags_eventDisabledVehicle	= 11,
	VehEventFlags_eventAirBagDeployment	= 12
} e_VehEventFlags;

/* VehEventFlags */
typedef BIT_STRING_t	 VehEventFlags_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehEventFlags_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehEventFlags;
asn_struct_free_f VehEventFlags_free;
asn_struct_print_f VehEventFlags_print;
asn_constr_check_f VehEventFlags_constraint;
ber_type_decoder_f VehEventFlags_decode_ber;
der_type_encoder_f VehEventFlags_encode_der;
xer_type_decoder_f VehEventFlags_decode_xer;
xer_type_encoder_f VehEventFlags_encode_xer;
oer_type_decoder_f VehEventFlags_decode_oer;
oer_type_encoder_f VehEventFlags_encode_oer;
per_type_decoder_f VehEventFlags_decode_uper;
per_type_encoder_f VehEventFlags_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehEventFlags_H_ */
#include <asn_internal.h>
