/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TciMsgLayerFrame"
 * 	found in "asn/msg_conformance.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_VehTransmissionState_H_
#define	_VehTransmissionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehTransmissionState {
	VehTransmissionState_neutral	= 0,
	VehTransmissionState_park	= 1,
	VehTransmissionState_forwardGears	= 2,
	VehTransmissionState_reverseGears	= 3,
	VehTransmissionState_reserved1	= 4,
	VehTransmissionState_reserved2	= 5,
	VehTransmissionState_reserved3	= 6,
	VehTransmissionState_unavailable	= 7
} e_VehTransmissionState;

/* VehTransmissionState */
typedef long	 VehTransmissionState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehTransmissionState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehTransmissionState;
extern const asn_INTEGER_specifics_t asn_SPC_VehTransmissionState_specs_1;
asn_struct_free_f VehTransmissionState_free;
asn_struct_print_f VehTransmissionState_print;
asn_constr_check_f VehTransmissionState_constraint;
ber_type_decoder_f VehTransmissionState_decode_ber;
der_type_encoder_f VehTransmissionState_encode_der;
xer_type_decoder_f VehTransmissionState_decode_xer;
xer_type_encoder_f VehTransmissionState_encode_xer;
oer_type_decoder_f VehTransmissionState_decode_oer;
oer_type_encoder_f VehTransmissionState_encode_oer;
per_type_decoder_f VehTransmissionState_decode_uper;
per_type_encoder_f VehTransmissionState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehTransmissionState_H_ */
#include <asn_internal.h>
