/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BasicSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationSet4Way;
extern struct asn_TYPE_descriptor_s asn_DEF_Acceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRate;
extern struct asn_TYPE_descriptor_s asn_DEF_Speed;
extern struct asn_TYPE_descriptor_s asn_DEF_Heading;
extern struct asn_TYPE_descriptor_s asn_DEF_CoarseHeading;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_MotionConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_HeadingConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngleConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_ElevationConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D;
extern struct asn_TYPE_descriptor_s asn_DEF_SemiMajorAxisAccuracy;
extern struct asn_TYPE_descriptor_s asn_DEF_SemiMinorAxisAccuracy;
extern struct asn_TYPE_descriptor_s asn_DEF_SemiMajorAxisOrientation;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionalAccuracy;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOffsetLLV;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B14;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B16;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B18;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B22;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B24;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_24B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_28B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_32B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_36B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_44B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_48B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LLmD_64b;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOffsetLL;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B07;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B08;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B09;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B10;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B11;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_DSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_DYear;
extern struct asn_TYPE_descriptor_s asn_DEF_DMonth;
extern struct asn_TYPE_descriptor_s asn_DEF_DDay;
extern struct asn_TYPE_descriptor_s asn_DEF_DHour;
extern struct asn_TYPE_descriptor_s asn_DEF_DMinute;
extern struct asn_TYPE_descriptor_s asn_DEF_DTimeOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_DDateTime;
extern struct asn_TYPE_descriptor_s asn_DEF_MinuteOfTheYear;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeMark;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_MapData;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeList;
extern struct asn_TYPE_descriptor_s asn_DEF_Node;
extern struct asn_TYPE_descriptor_s asn_DEF_DescriptiveName;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeReferenceID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadRegulatorID;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeID;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkList;
extern struct asn_TYPE_descriptor_s asn_DEF_Link;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementList;
extern struct asn_TYPE_descriptor_s asn_DEF_Movement;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneList;
extern struct asn_TYPE_descriptor_s asn_DEF_Lane;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneID;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectsToList;
extern struct asn_TYPE_descriptor_s asn_DEF_Connection;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectingLane;
extern struct asn_TYPE_descriptor_s asn_DEF_AllowedManeuvers;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneSharing;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneTypeAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Vehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Crosswalk;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Bike;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Sidewalk;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Barrier;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Striping;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_TrackedVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Parking;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitList;
extern struct asn_TYPE_descriptor_s asn_DEF_RegulatorySpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitType;
extern struct asn_TYPE_descriptor_s asn_DEF_PointList;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkExList;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkEx;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementExList;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementEx;
extern struct asn_TYPE_descriptor_s asn_DEF_Maneuver;
extern struct asn_TYPE_descriptor_s asn_DEF_SectionList;
extern struct asn_TYPE_descriptor_s asn_DEF_Section;
extern struct asn_TYPE_descriptor_s asn_DEF_SectionId;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneExList;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneEx;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneLineType;
extern struct asn_TYPE_descriptor_s asn_DEF_Dotted_SolidMarkingLineType;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneRefID;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectsToExList;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectionEx;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalWaitingLane;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectingLaneEx;
extern struct asn_TYPE_descriptor_s asn_DEF_STPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_ST_Point;
extern struct asn_TYPE_descriptor_s asn_DEF_ProhibitedZone;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageFrameExt;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtMsgID;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_MsgCount;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMData;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingLotInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_AVPType;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMNodeList;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMNode;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMNodeID;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMNodeAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMDriveList;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMDrive;
extern struct asn_TYPE_descriptor_s asn_DEF_PAMMovementList;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingSlots;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingSlot;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingSlotPosition;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingLock;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingSpaceTheta;
extern struct asn_TYPE_descriptor_s asn_DEF_SlotStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingType;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingGuide;
extern struct asn_TYPE_descriptor_s asn_DEF_CLPMM;
extern struct asn_TYPE_descriptor_s asn_DEF_MemberManagement;
extern struct asn_TYPE_descriptor_s asn_DEF_RoleInPlatooning;
extern struct asn_TYPE_descriptor_s asn_DEF_StatusInPlatooning;
extern struct asn_TYPE_descriptor_s asn_DEF_MemberList;
extern struct asn_TYPE_descriptor_s asn_DEF_MemberNode;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_Non_motorData;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalDeviceUserType;
extern struct asn_TYPE_descriptor_s asn_DEF_PropelledInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanPropelledType;
extern struct asn_TYPE_descriptor_s asn_DEF_AnimalPropelledType;
extern struct asn_TYPE_descriptor_s asn_DEF_MotorizedPropelledType;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberOfParticipantsInCluster;
extern struct asn_TYPE_descriptor_s asn_DEF_Attachment;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalDeviceUsageState;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalAssistive;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadWorkerExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadWorkerType;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadWorkerActivityType;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalCrossing;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadsideCoordination;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneCoordination;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleCoordination;
extern struct asn_TYPE_descriptor_s asn_DEF_CoordinationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveSuggestion;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSideInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_RTEList;
extern struct asn_TYPE_descriptor_s asn_DEF_RTEData;
extern struct asn_TYPE_descriptor_s asn_DEF_EventSource;
extern struct asn_TYPE_descriptor_s asn_DEF_EventType;
extern struct asn_TYPE_descriptor_s asn_DEF_RSITimeDetails;
extern struct asn_TYPE_descriptor_s asn_DEF_ReferencePathList;
extern struct asn_TYPE_descriptor_s asn_DEF_ReferencePath;
extern struct asn_TYPE_descriptor_s asn_DEF_RTSList;
extern struct asn_TYPE_descriptor_s asn_DEF_RTSData;
extern struct asn_TYPE_descriptor_s asn_DEF_AuxiliarySign;
extern struct asn_TYPE_descriptor_s asn_DEF_AuxiliarySignVehicleType;
extern struct asn_TYPE_descriptor_s asn_DEF_AuxiliarySignDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_Description;
extern struct asn_TYPE_descriptor_s asn_DEF_ReferenceLinkList;
extern struct asn_TYPE_descriptor_s asn_DEF_ReferenceLink;
extern struct asn_TYPE_descriptor_s asn_DEF_ReferenceLanes;
extern struct asn_TYPE_descriptor_s asn_DEF_SignType;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_Radius;
extern struct asn_TYPE_descriptor_s asn_DEF_RSIPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadsideSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantList;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantData;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantType;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceType;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMcorrections;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMmsg;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCM_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCM_Payload;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCM_Revision;
extern struct asn_TYPE_descriptor_s asn_DEF_SensorSharingMsg;
extern struct asn_TYPE_descriptor_s asn_DEF_DetectedRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_EquipmentType;
extern struct asn_TYPE_descriptor_s asn_DEF_DetectedPTCList;
extern struct asn_TYPE_descriptor_s asn_DEF_DetectedPTCData;
extern struct asn_TYPE_descriptor_s asn_DEF_PlanningList;
extern struct asn_TYPE_descriptor_s asn_DEF_Planning;
extern struct asn_TYPE_descriptor_s asn_DEF_PlanningDuration;
extern struct asn_TYPE_descriptor_s asn_DEF_AccSet4WayConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_AccConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_DetectedPTCType;
extern struct asn_TYPE_descriptor_s asn_DEF_MotorDataExtension;
extern struct asn_TYPE_descriptor_s asn_DEF_Polygon;
extern struct asn_TYPE_descriptor_s asn_DEF_Attitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Pitch;
extern struct asn_TYPE_descriptor_s asn_DEF_Roll;
extern struct asn_TYPE_descriptor_s asn_DEF_Yaw;
extern struct asn_TYPE_descriptor_s asn_DEF_AttitudeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_AngularVelocity;
extern struct asn_TYPE_descriptor_s asn_DEF_PitchRate;
extern struct asn_TYPE_descriptor_s asn_DEF_RollRate;
extern struct asn_TYPE_descriptor_s asn_DEF_AngularVelocityConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_AngularVConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Non_motorDataExtension;
extern struct asn_TYPE_descriptor_s asn_DEF_DetectedObstacleList;
extern struct asn_TYPE_descriptor_s asn_DEF_DetectedObstacleData;
extern struct asn_TYPE_descriptor_s asn_DEF_ObstacleType;
extern struct asn_TYPE_descriptor_s asn_DEF_ObjectSize;
extern struct asn_TYPE_descriptor_s asn_DEF_SizeValue;
extern struct asn_TYPE_descriptor_s asn_DEF_ObjectSizeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SizeValueConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SPAT;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStateList;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionState;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStatusObject;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseList;
extern struct asn_TYPE_descriptor_s asn_DEF_Phase;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseStateList;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseState;
extern struct asn_TYPE_descriptor_s asn_DEF_LightState;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeChangeDetails;
extern struct asn_TYPE_descriptor_s asn_DEF_UTCTiming;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeCountingDown;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseID;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMsg;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeSystemStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakePedalStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeAppliedStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeBoostApplied;
extern struct asn_TYPE_descriptor_s asn_DEF_TractionControlStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_AntiLockBrakeStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_StabilityControlStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_AuxiliaryBrakeStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleClassification;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicVehicleClass;
extern struct asn_TYPE_descriptor_s asn_DEF_FuelType;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleEmergencyExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_ResponseType;
extern struct asn_TYPE_descriptor_s asn_DEF_SirenInUse;
extern struct asn_TYPE_descriptor_s asn_DEF_LightbarInUse;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSafetyExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistory;
extern struct asn_TYPE_descriptor_s asn_DEF_FullPositionVector;
extern struct asn_TYPE_descriptor_s asn_DEF_GNSSstatus;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistoryPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistoryPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPrediction;
extern struct asn_TYPE_descriptor_s asn_DEF_Confidence;
extern struct asn_TYPE_descriptor_s asn_DEF_RadiusOfCurvature;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSize;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleHeight;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionState;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleEventFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_ExteriorLights;
extern struct asn_TYPE_descriptor_s asn_DEF_VehIntentionAndRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_IARData;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPlanning;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPlanningPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveBehavior;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_ReqInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ReqStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_Req_LaneChange;
extern struct asn_TYPE_descriptor_s asn_DEF_Req_ClearTheWay;
extern struct asn_TYPE_descriptor_s asn_DEF_Req_SignalPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_Req_SensorSharing;
extern struct asn_TYPE_descriptor_s asn_DEF_ParkingRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_Req_ParkingArea;
extern struct asn_TYPE_descriptor_s asn_DEF_VehiclePaymentMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_RST;
extern struct asn_TYPE_descriptor_s asn_DEF_PaymentList;
extern struct asn_TYPE_descriptor_s asn_DEF_ApplicationParameter;
extern struct asn_TYPE_descriptor_s asn_DEF_PaymentInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_PaymentEntityID;
extern struct asn_TYPE_descriptor_s asn_DEF_PaymentInfoType1;
extern struct asn_TYPE_descriptor_s asn_DEF_TollingNodeInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_StationOrGantryId;
extern struct asn_TYPE_descriptor_s asn_DEF_TollingNodeType;
extern struct asn_TYPE_descriptor_s asn_DEF_TollingDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_TollInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_VSI;
extern struct asn_TYPE_descriptor_s asn_DEF_VPApplicationList;
extern struct asn_TYPE_descriptor_s asn_DEF_VPApplicationParameter;
extern struct asn_TYPE_descriptor_s asn_DEF_OBUPaymentInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_OBUPaymentInfoType1;
extern struct asn_TYPE_descriptor_s asn_DEF_EquipmentClass;
extern struct asn_TYPE_descriptor_s asn_DEF_GBICCInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_OBUInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_OBUType;
extern struct asn_TYPE_descriptor_s asn_DEF_OBUMotionStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_RandStr8;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleDimensions;
extern struct asn_TYPE_descriptor_s asn_DEF_TollingPos;
extern struct asn_TYPE_descriptor_s asn_DEF_PassedPos;
extern struct asn_TYPE_descriptor_s asn_DEF_PassedSitesInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_Date;
extern struct asn_TYPE_descriptor_s asn_DEF_Action_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_Action_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_ReturnStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_TransInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_GetTollDataRq;
extern struct asn_TYPE_descriptor_s asn_DEF_GetTollDataRs;
extern struct asn_TYPE_descriptor_s asn_DEF_RangeOfFile;
extern struct asn_TYPE_descriptor_s asn_DEF_File;
extern struct asn_TYPE_descriptor_s asn_DEF_PartOfFile;
extern struct asn_TYPE_descriptor_s asn_DEF_GetSecureRq;
extern struct asn_TYPE_descriptor_s asn_DEF_GetSecureRs;
extern struct asn_TYPE_descriptor_s asn_DEF_SetTollDataRq;
extern struct asn_TYPE_descriptor_s asn_DEF_TransPara;
extern struct asn_TYPE_descriptor_s asn_DEF_SetTollDataRs;
extern struct asn_TYPE_descriptor_s asn_DEF_SetMMIRq;
extern struct asn_TYPE_descriptor_s asn_DEF_TollResult;
extern struct asn_TYPE_descriptor_s asn_DEF_AccountInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_TransCredential;
extern struct asn_TYPE_descriptor_s asn_DEF_ChannelRq;
extern struct asn_TYPE_descriptor_s asn_DEF_ChannelRs;
extern struct asn_TYPE_descriptor_s asn_DEF_ChannelID;
extern struct asn_TYPE_descriptor_s asn_DEF_ApduList;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module BSM in asn/BSM.asn */
	&asn_DEF_BasicSafetyMessage,	
	/* From module DefAcceleration in asn/DefAcceleration.asn */
	&asn_DEF_AccelerationSet4Way,	
	&asn_DEF_Acceleration,	
	&asn_DEF_VerticalAcceleration,	
	&asn_DEF_YawRate,	
	/* From module DefMotion in asn/DefMotion.asn */
	&asn_DEF_Speed,	
	&asn_DEF_Heading,	
	&asn_DEF_CoarseHeading,	
	&asn_DEF_SteeringWheelAngle,	
	&asn_DEF_MotionConfidenceSet,	
	&asn_DEF_HeadingConfidence,	
	&asn_DEF_SpeedConfidence,	
	&asn_DEF_SteeringWheelAngleConfidence,	
	/* From module DefPosition in asn/DefPosition.asn */
	&asn_DEF_Latitude,	
	&asn_DEF_Longitude,	
	&asn_DEF_Elevation,	
	&asn_DEF_PositionConfidenceSet,	
	&asn_DEF_PositionConfidence,	
	&asn_DEF_ElevationConfidence,	
	&asn_DEF_Position3D,	
	&asn_DEF_SemiMajorAxisAccuracy,	
	&asn_DEF_SemiMinorAxisAccuracy,	
	&asn_DEF_SemiMajorAxisOrientation,	
	&asn_DEF_PositionalAccuracy,	
	/* From module DefPositionOffset in asn/DefPositionOffset.asn */
	&asn_DEF_PositionOffsetLLV,	
	&asn_DEF_OffsetLL_B12,	
	&asn_DEF_OffsetLL_B14,	
	&asn_DEF_OffsetLL_B16,	
	&asn_DEF_OffsetLL_B18,	
	&asn_DEF_OffsetLL_B22,	
	&asn_DEF_OffsetLL_B24,	
	&asn_DEF_Position_LL_24B,	
	&asn_DEF_Position_LL_28B,	
	&asn_DEF_Position_LL_32B,	
	&asn_DEF_Position_LL_36B,	
	&asn_DEF_Position_LL_44B,	
	&asn_DEF_Position_LL_48B,	
	&asn_DEF_Position_LLmD_64b,	
	&asn_DEF_PositionOffsetLL,	
	&asn_DEF_VerticalOffset,	
	&asn_DEF_VertOffset_B07,	
	&asn_DEF_VertOffset_B08,	
	&asn_DEF_VertOffset_B09,	
	&asn_DEF_VertOffset_B10,	
	&asn_DEF_VertOffset_B11,	
	&asn_DEF_VertOffset_B12,	
	/* From module DefTime in asn/DefTime.asn */
	&asn_DEF_DSecond,	
	&asn_DEF_DYear,	
	&asn_DEF_DMonth,	
	&asn_DEF_DDay,	
	&asn_DEF_DHour,	
	&asn_DEF_DMinute,	
	&asn_DEF_DTimeOffset,	
	&asn_DEF_DDateTime,	
	&asn_DEF_MinuteOfTheYear,	
	&asn_DEF_TimeMark,	
	&asn_DEF_TimeOffset,	
	&asn_DEF_TimeConfidence,	
	/* From module Map in asn/Map.asn */
	&asn_DEF_MapData,	
	&asn_DEF_NodeList,	
	&asn_DEF_Node,	
	&asn_DEF_DescriptiveName,	
	&asn_DEF_NodeReferenceID,	
	&asn_DEF_RoadRegulatorID,	
	&asn_DEF_NodeID,	
	&asn_DEF_LinkList,	
	&asn_DEF_Link,	
	&asn_DEF_MovementList,	
	&asn_DEF_Movement,	
	&asn_DEF_LaneList,	
	&asn_DEF_Lane,	
	&asn_DEF_LaneID,	
	&asn_DEF_LaneWidth,	
	&asn_DEF_ConnectsToList,	
	&asn_DEF_Connection,	
	&asn_DEF_ConnectingLane,	
	&asn_DEF_AllowedManeuvers,	
	&asn_DEF_LaneAttributes,	
	&asn_DEF_LaneSharing,	
	&asn_DEF_LaneTypeAttributes,	
	&asn_DEF_LaneAttributes_Vehicle,	
	&asn_DEF_LaneAttributes_Crosswalk,	
	&asn_DEF_LaneAttributes_Bike,	
	&asn_DEF_LaneAttributes_Sidewalk,	
	&asn_DEF_LaneAttributes_Barrier,	
	&asn_DEF_LaneAttributes_Striping,	
	&asn_DEF_LaneAttributes_TrackedVehicle,	
	&asn_DEF_LaneAttributes_Parking,	
	&asn_DEF_SpeedLimitList,	
	&asn_DEF_RegulatorySpeedLimit,	
	&asn_DEF_SpeedLimitType,	
	&asn_DEF_PointList,	
	&asn_DEF_RoadPoint,	
	&asn_DEF_LinkExList,	
	&asn_DEF_LinkEx,	
	&asn_DEF_MovementExList,	
	&asn_DEF_MovementEx,	
	&asn_DEF_Maneuver,	
	&asn_DEF_SectionList,	
	&asn_DEF_Section,	
	&asn_DEF_SectionId,	
	&asn_DEF_LaneExList,	
	&asn_DEF_LaneEx,	
	&asn_DEF_LaneLineType,	
	&asn_DEF_Dotted_SolidMarkingLineType,	
	&asn_DEF_LaneRefID,	
	&asn_DEF_ConnectsToExList,	
	&asn_DEF_ConnectionEx,	
	&asn_DEF_SignalWaitingLane,	
	&asn_DEF_ConnectingLaneEx,	
	&asn_DEF_STPointList,	
	&asn_DEF_ST_Point,	
	&asn_DEF_ProhibitedZone,	
	/* From module MsgDayII in asn/MsgDayII.asn */
	&asn_DEF_MessageFrameExt,	
	&asn_DEF_ExtMsgID,	
	/* From module MsgFrame in asn/MsgFrame.asn */
	&asn_DEF_MessageFrame,	
	&asn_DEF_MsgCount,	
	/* From module PAM in asn/PAM.asn */
	&asn_DEF_PAMData,	
	&asn_DEF_ParkingLotInfo,	
	&asn_DEF_AVPType,	
	&asn_DEF_PAMNodeList,	
	&asn_DEF_PAMNode,	
	&asn_DEF_PAMNodeID,	
	&asn_DEF_PAMNodeAttributes,	
	&asn_DEF_PAMDriveList,	
	&asn_DEF_PAMDrive,	
	&asn_DEF_PAMMovementList,	
	&asn_DEF_ParkingSlots,	
	&asn_DEF_ParkingSlot,	
	&asn_DEF_ParkingSlotPosition,	
	&asn_DEF_ParkingLock,	
	&asn_DEF_ParkingSpaceTheta,	
	&asn_DEF_SlotStatus,	
	&asn_DEF_ParkingType,	
	&asn_DEF_ParkingGuide,	
	/* From module Platooning in asn/Platooning.asn */
	&asn_DEF_CLPMM,	
	&asn_DEF_MemberManagement,	
	&asn_DEF_RoleInPlatooning,	
	&asn_DEF_StatusInPlatooning,	
	&asn_DEF_MemberList,	
	&asn_DEF_MemberNode,	
	/* From module PSM in asn/PSM.asn */
	&asn_DEF_PersonalSafetyMessage,	
	&asn_DEF_Non_motorData,	
	&asn_DEF_PersonalDeviceUserType,	
	&asn_DEF_PropelledInformation,	
	&asn_DEF_HumanPropelledType,	
	&asn_DEF_AnimalPropelledType,	
	&asn_DEF_MotorizedPropelledType,	
	&asn_DEF_NumberOfParticipantsInCluster,	
	&asn_DEF_Attachment,	
	&asn_DEF_PersonalExtensions,	
	&asn_DEF_PersonalDeviceUsageState,	
	&asn_DEF_PersonalAssistive,	
	&asn_DEF_RoadWorkerExtensions,	
	&asn_DEF_RoadWorkerType,	
	&asn_DEF_RoadWorkerActivityType,	
	&asn_DEF_PersonalRequest,	
	&asn_DEF_PersonalCrossing,	
	/* From module RSC in asn/RSC.asn */
	&asn_DEF_RoadsideCoordination,	
	&asn_DEF_LaneCoordination,	
	&asn_DEF_VehicleCoordination,	
	&asn_DEF_CoordinationInfo,	
	&asn_DEF_DriveSuggestion,	
	/* From module RSI in asn/RSI.asn */
	&asn_DEF_RoadSideInformation,	
	&asn_DEF_RTEList,	
	&asn_DEF_RTEData,	
	&asn_DEF_EventSource,	
	&asn_DEF_EventType,	
	&asn_DEF_RSITimeDetails,	
	&asn_DEF_ReferencePathList,	
	&asn_DEF_ReferencePath,	
	&asn_DEF_RTSList,	
	&asn_DEF_RTSData,	
	&asn_DEF_AuxiliarySign,	
	&asn_DEF_AuxiliarySignVehicleType,	
	&asn_DEF_AuxiliarySignDirection,	
	&asn_DEF_Description,	
	&asn_DEF_ReferenceLinkList,	
	&asn_DEF_ReferenceLink,	
	&asn_DEF_ReferenceLanes,	
	&asn_DEF_SignType,	
	&asn_DEF_PathPointList,	
	&asn_DEF_Radius,	
	&asn_DEF_RSIPriority,	
	/* From module RSM in asn/RSM.asn */
	&asn_DEF_RoadsideSafetyMessage,	
	&asn_DEF_ParticipantList,	
	&asn_DEF_ParticipantData,	
	&asn_DEF_ParticipantType,	
	&asn_DEF_SourceType,	
	/* From module RTCM in asn/RTCM.asn */
	&asn_DEF_RTCMcorrections,	
	&asn_DEF_RTCMmsg,	
	&asn_DEF_RTCM_ID,	
	&asn_DEF_RTCM_Payload,	
	&asn_DEF_RTCM_Revision,	
	/* From module SensorSharing in asn/SensorSharing.asn */
	&asn_DEF_SensorSharingMsg,	
	&asn_DEF_DetectedRegion,	
	&asn_DEF_EquipmentType,	
	&asn_DEF_DetectedPTCList,	
	&asn_DEF_DetectedPTCData,	
	&asn_DEF_PlanningList,	
	&asn_DEF_Planning,	
	&asn_DEF_PlanningDuration,	
	&asn_DEF_AccSet4WayConfidence,	
	&asn_DEF_AccConfidence,	
	&asn_DEF_DetectedPTCType,	
	&asn_DEF_MotorDataExtension,	
	&asn_DEF_Polygon,	
	&asn_DEF_Attitude,	
	&asn_DEF_Pitch,	
	&asn_DEF_Roll,	
	&asn_DEF_Yaw,	
	&asn_DEF_AttitudeConfidence,	
	&asn_DEF_AngularVelocity,	
	&asn_DEF_PitchRate,	
	&asn_DEF_RollRate,	
	&asn_DEF_AngularVelocityConfidence,	
	&asn_DEF_AngularVConfidence,	
	&asn_DEF_Non_motorDataExtension,	
	&asn_DEF_DetectedObstacleList,	
	&asn_DEF_DetectedObstacleData,	
	&asn_DEF_ObstacleType,	
	&asn_DEF_ObjectSize,	
	&asn_DEF_SizeValue,	
	&asn_DEF_ObjectSizeConfidence,	
	&asn_DEF_SizeValueConfidence,	
	/* From module SignalPhaseAndTiming in asn/SignalPhaseAndTiming.asn */
	&asn_DEF_SPAT,	
	&asn_DEF_IntersectionStateList,	
	&asn_DEF_IntersectionState,	
	&asn_DEF_IntersectionStatusObject,	
	&asn_DEF_PhaseList,	
	&asn_DEF_Phase,	
	&asn_DEF_PhaseStateList,	
	&asn_DEF_PhaseState,	
	&asn_DEF_LightState,	
	&asn_DEF_TimeChangeDetails,	
	&asn_DEF_UTCTiming,	
	&asn_DEF_TimeCountingDown,	
	&asn_DEF_PhaseID,	
	/* From module TestMsg in asn/TestMsg.asn */
	&asn_DEF_TestMsg,	
	/* From module VehBrake in asn/VehBrake.asn */
	&asn_DEF_BrakeSystemStatus,	
	&asn_DEF_BrakePedalStatus,	
	&asn_DEF_BrakeAppliedStatus,	
	&asn_DEF_BrakeBoostApplied,	
	&asn_DEF_TractionControlStatus,	
	&asn_DEF_AntiLockBrakeStatus,	
	&asn_DEF_StabilityControlStatus,	
	&asn_DEF_AuxiliaryBrakeStatus,	
	/* From module VehClass in asn/VehClass.asn */
	&asn_DEF_VehicleClassification,	
	&asn_DEF_BasicVehicleClass,	
	&asn_DEF_FuelType,	
	/* From module VehEmgExt in asn/VehEmgExt.asn */
	&asn_DEF_VehicleEmergencyExtensions,	
	&asn_DEF_ResponseType,	
	&asn_DEF_SirenInUse,	
	&asn_DEF_LightbarInUse,	
	/* From module VehSafetyExt in asn/VehSafetyExt.asn */
	&asn_DEF_VehicleSafetyExtensions,	
	&asn_DEF_PathHistory,	
	&asn_DEF_FullPositionVector,	
	&asn_DEF_GNSSstatus,	
	&asn_DEF_PathHistoryPointList,	
	&asn_DEF_PathHistoryPoint,	
	&asn_DEF_PathPrediction,	
	&asn_DEF_Confidence,	
	&asn_DEF_RadiusOfCurvature,	
	/* From module VehSize in asn/VehSize.asn */
	&asn_DEF_VehicleSize,	
	&asn_DEF_VehicleWidth,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleHeight,	
	/* From module VehStatus in asn/VehStatus.asn */
	&asn_DEF_TransmissionState,	
	&asn_DEF_VehicleEventFlags,	
	&asn_DEF_ExteriorLights,	
	/* From module VIR in asn/VIR.asn */
	&asn_DEF_VehIntentionAndRequest,	
	&asn_DEF_IARData,	
	&asn_DEF_PathPlanning,	
	&asn_DEF_PathPlanningPoint,	
	&asn_DEF_DriveBehavior,	
	&asn_DEF_DriveRequest,	
	&asn_DEF_ReqInfo,	
	&asn_DEF_ReqStatus,	
	&asn_DEF_Req_LaneChange,	
	&asn_DEF_Req_ClearTheWay,	
	&asn_DEF_Req_SignalPriority,	
	&asn_DEF_Req_SensorSharing,	
	&asn_DEF_ParkingRequest,	
	&asn_DEF_Req_ParkingArea,	
	/* From module VPM in asn/VPM.asn */
	&asn_DEF_VehiclePaymentMessage,	
	&asn_DEF_RST,	
	&asn_DEF_PaymentList,	
	&asn_DEF_ApplicationParameter,	
	&asn_DEF_PaymentInfo,	
	&asn_DEF_PaymentEntityID,	
	&asn_DEF_PaymentInfoType1,	
	&asn_DEF_TollingNodeInfo,	
	&asn_DEF_StationOrGantryId,	
	&asn_DEF_TollingNodeType,	
	&asn_DEF_TollingDirection,	
	&asn_DEF_TollInfo,	
	&asn_DEF_VSI,	
	&asn_DEF_VPApplicationList,	
	&asn_DEF_VPApplicationParameter,	
	&asn_DEF_OBUPaymentInfo,	
	&asn_DEF_OBUPaymentInfoType1,	
	&asn_DEF_EquipmentClass,	
	&asn_DEF_GBICCInfo,	
	&asn_DEF_OBUInfo,	
	&asn_DEF_OBUType,	
	&asn_DEF_OBUMotionStatus,	
	&asn_DEF_RandStr8,	
	&asn_DEF_SysInfo,	
	&asn_DEF_VehicleInfo,	
	&asn_DEF_VehicleDimensions,	
	&asn_DEF_TollingPos,	
	&asn_DEF_PassedPos,	
	&asn_DEF_PassedSitesInfo,	
	&asn_DEF_Date,	
	&asn_DEF_Action_Request,	
	&asn_DEF_Action_Response,	
	&asn_DEF_ReturnStatus,	
	&asn_DEF_TransInfo,	
	&asn_DEF_GetTollDataRq,	
	&asn_DEF_GetTollDataRs,	
	&asn_DEF_RangeOfFile,	
	&asn_DEF_File,	
	&asn_DEF_PartOfFile,	
	&asn_DEF_GetSecureRq,	
	&asn_DEF_GetSecureRs,	
	&asn_DEF_SetTollDataRq,	
	&asn_DEF_TransPara,	
	&asn_DEF_SetTollDataRs,	
	&asn_DEF_SetMMIRq,	
	&asn_DEF_TollResult,	
	&asn_DEF_AccountInfo,	
	&asn_DEF_TransCredential,	
	&asn_DEF_ChannelRq,	
	&asn_DEF_ChannelRs,	
	&asn_DEF_ChannelID,	
	&asn_DEF_ApduList,	
	0
};

