/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "CertRequest.h"

asn_TYPE_member_t asn_MBR_CertRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertRequest, version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertRequest, currentTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"currentTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertRequest, tbsCertData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TbsCert,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbsCertData"
		},
	{ ATF_POINTER, 1, offsetof(struct CertRequest, encryptionKey),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PublicEncryptionKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encryptionKey"
		},
};
static const int asn_MAP_CertRequest_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_CertRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CertRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* currentTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tbsCertData */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* encryptionKey */
};
asn_SEQUENCE_specifics_t asn_SPC_CertRequest_specs_1 = {
	sizeof(struct CertRequest),
	offsetof(struct CertRequest, _asn_ctx),
	asn_MAP_CertRequest_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_CertRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CertRequest = {
	"CertRequest",
	"CertRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_CertRequest_tags_1,
	sizeof(asn_DEF_CertRequest_tags_1)
		/sizeof(asn_DEF_CertRequest_tags_1[0]), /* 1 */
	asn_DEF_CertRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_CertRequest_tags_1)
		/sizeof(asn_DEF_CertRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CertRequest_1,
	4,	/* Elements count */
	&asn_SPC_CertRequest_specs_1	/* Additional specs */
};

