/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DefPosition"
 * 	found in "asn/DefPosition.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_DefPosition_Elevation_H_
#define	_DefPosition_Elevation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Elevation */
typedef long	 DefPosition_Elevation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DefPosition_Elevation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DefPosition_Elevation;
asn_struct_free_f DefPosition_Elevation_free;
asn_struct_print_f DefPosition_Elevation_print;
asn_constr_check_f DefPosition_Elevation_constraint;
ber_type_decoder_f DefPosition_Elevation_decode_ber;
der_type_encoder_f DefPosition_Elevation_encode_der;
xer_type_decoder_f DefPosition_Elevation_decode_xer;
xer_type_encoder_f DefPosition_Elevation_encode_xer;
oer_type_decoder_f DefPosition_Elevation_decode_oer;
oer_type_encoder_f DefPosition_Elevation_encode_oer;
per_type_decoder_f DefPosition_Elevation_decode_uper;
per_type_encoder_f DefPosition_Elevation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DefPosition_Elevation_H_ */
#include <asn_internal.h>
