/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_DHResult_H_
#define	_DHResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DHResult {
	DHResult_success	= 0,
	DHResult_refuse	= 1,
	DHResult_stateError	= 2,
	DHResult_timeOut	= 3
	/*
	 * Enumeration is extensible
	 */
} e_DHResult;

/* DHResult */
typedef long	 DHResult_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DHResult_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DHResult;
extern const asn_INTEGER_specifics_t asn_SPC_DHResult_specs_1;
asn_struct_free_f DHResult_free;
asn_struct_print_f DHResult_print;
asn_constr_check_f DHResult_constraint;
ber_type_decoder_f DHResult_decode_ber;
der_type_encoder_f DHResult_encode_der;
xer_type_decoder_f DHResult_decode_xer;
xer_type_encoder_f DHResult_encode_xer;
oer_type_decoder_f DHResult_decode_oer;
oer_type_encoder_f DHResult_encode_oer;
per_type_decoder_f DHResult_decode_uper;
per_type_encoder_f DHResult_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DHResult_H_ */
#include <asn_internal.h>
