/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "ECDHMessage.h"

static int
memb_dhID_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_dhID_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	16	/* (SIZE(16..16)) */};
static asn_per_constraints_t asn_PER_memb_dhID_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  16,  16 }	/* (SIZE(16..16)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ECDHMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHMessage, version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHMessage, hashAlg),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashAlgorithm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashAlg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHMessage, curve),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EccCurve,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"curve"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHMessage, dhID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_dhID_constr_5, &asn_PER_memb_dhID_constr_5,  memb_dhID_constraint_1 },
		0, 0, /* No default value */
		"dhID"
		},
	{ ATF_POINTER, 2, offsetof(struct ECDHMessage, dhStartTime),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dhStartTime"
		},
	{ ATF_POINTER, 1, offsetof(struct ECDHMessage, dhExpireTime),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dhExpireTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHMessage, dhData),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ECDHContent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dhData"
		},
};
static const int asn_MAP_ECDHMessage_oms_1[] = { 4, 5 };
static const ber_tlv_tag_t asn_DEF_ECDHMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ECDHMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hashAlg */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* curve */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dhID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dhStartTime */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* dhExpireTime */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* dhData */
};
asn_SEQUENCE_specifics_t asn_SPC_ECDHMessage_specs_1 = {
	sizeof(struct ECDHMessage),
	offsetof(struct ECDHMessage, _asn_ctx),
	asn_MAP_ECDHMessage_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_ECDHMessage_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ECDHMessage = {
	"ECDHMessage",
	"ECDHMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_ECDHMessage_tags_1,
	sizeof(asn_DEF_ECDHMessage_tags_1)
		/sizeof(asn_DEF_ECDHMessage_tags_1[0]), /* 1 */
	asn_DEF_ECDHMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_ECDHMessage_tags_1)
		/sizeof(asn_DEF_ECDHMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ECDHMessage_1,
	7,	/* Elements count */
	&asn_SPC_ECDHMessage_specs_1	/* Additional specs */
};

