/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHData_H_
#define	_ECDHData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Time32.h"
#include "ECCPoint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHData */
typedef struct ECDHData {
	Time32_t	 keyStartTime;
	Time32_t	 keyExpireTime;
	ECCPoint_t	 dhKey;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECDHData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHData;
extern asn_SEQUENCE_specifics_t asn_SPC_ECDHData_specs_1;
extern asn_TYPE_member_t asn_MBR_ECDHData_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHData_H_ */
#include <asn_internal.h>
