/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHResponseData_H_
#define	_ECDHResponseData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignedMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHResponseData */
typedef SignedMessage_t	 ECDHResponseData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHResponseData;
asn_struct_free_f ECDHResponseData_free;
asn_struct_print_f ECDHResponseData_print;
asn_constr_check_f ECDHResponseData_constraint;
ber_type_decoder_f ECDHResponseData_decode_ber;
der_type_encoder_f ECDHResponseData_encode_der;
xer_type_decoder_f ECDHResponseData_decode_xer;
xer_type_encoder_f ECDHResponseData_encode_xer;
oer_type_decoder_f ECDHResponseData_decode_oer;
oer_type_encoder_f ECDHResponseData_encode_oer;
per_type_decoder_f ECDHResponseData_decode_uper;
per_type_encoder_f ECDHResponseData_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHResponseData_H_ */
#include <asn_internal.h>
