/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "ECDHContent.h"

static asn_oer_constraints_t asn_OER_type_ECDHContent_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ECDHContent_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ECDHContent_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHContent, choice.exchangeData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECDHData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exchangeData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHContent, choice.exchangeConfirm),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECDHConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exchangeConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECDHContent, choice.exchangeResult),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECDHResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exchangeResult"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ECDHContent_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* exchangeData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* exchangeConfirm */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* exchangeResult */
};
asn_CHOICE_specifics_t asn_SPC_ECDHContent_specs_1 = {
	sizeof(struct ECDHContent),
	offsetof(struct ECDHContent, _asn_ctx),
	offsetof(struct ECDHContent, present),
	sizeof(((struct ECDHContent *)0)->present),
	asn_MAP_ECDHContent_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ECDHContent = {
	"ECDHContent",
	"ECDHContent",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ECDHContent_constr_1, &asn_PER_type_ECDHContent_constr_1, CHOICE_constraint },
	asn_MBR_ECDHContent_1,
	3,	/* Elements count */
	&asn_SPC_ECDHContent_specs_1	/* Additional specs */
};

