/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHConfirmOrResultData_H_
#define	_ECDHConfirmOrResultData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignedMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHConfirmOrResultData */
typedef SignedMessage_t	 ECDHConfirmOrResultData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHConfirmOrResultData;
asn_struct_free_f ECDHConfirmOrResultData_free;
asn_struct_print_f ECDHConfirmOrResultData_print;
asn_constr_check_f ECDHConfirmOrResultData_constraint;
ber_type_decoder_f ECDHConfirmOrResultData_decode_ber;
der_type_encoder_f ECDHConfirmOrResultData_encode_der;
xer_type_decoder_f ECDHConfirmOrResultData_decode_xer;
xer_type_encoder_f ECDHConfirmOrResultData_encode_xer;
oer_type_decoder_f ECDHConfirmOrResultData_decode_oer;
oer_type_encoder_f ECDHConfirmOrResultData_encode_oer;
per_type_decoder_f ECDHConfirmOrResultData_decode_uper;
per_type_encoder_f ECDHConfirmOrResultData_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHConfirmOrResultData_H_ */
#include <asn_internal.h>
