/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHExChangeConfirmOrResult_H_
#define	_ECDHExChangeConfirmOrResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECDHMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHExChangeConfirmOrResult */
typedef ECDHMessage_t	 ECDHExChangeConfirmOrResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHExChangeConfirmOrResult;
asn_struct_free_f ECDHExChangeConfirmOrResult_free;
asn_struct_print_f ECDHExChangeConfirmOrResult_print;
asn_constr_check_f ECDHExChangeConfirmOrResult_constraint;
ber_type_decoder_f ECDHExChangeConfirmOrResult_decode_ber;
der_type_encoder_f ECDHExChangeConfirmOrResult_encode_der;
xer_type_decoder_f ECDHExChangeConfirmOrResult_decode_xer;
xer_type_encoder_f ECDHExChangeConfirmOrResult_encode_xer;
oer_type_decoder_f ECDHExChangeConfirmOrResult_decode_oer;
oer_type_encoder_f ECDHExChangeConfirmOrResult_encode_oer;
per_type_decoder_f ECDHExChangeConfirmOrResult_decode_uper;
per_type_encoder_f ECDHExChangeConfirmOrResult_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHExChangeConfirmOrResult_H_ */
#include <asn_internal.h>
