/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHMessage_H_
#define	_ECDHMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "HashAlgorithm.h"
#include "EccCurve.h"
#include <OCTET_STRING.h>
#include "Time32.h"
#include "ECDHContent.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHMessage */
typedef struct ECDHMessage {
	Uint8_t	 version;
	HashAlgorithm_t	 hashAlg;
	EccCurve_t	 curve;
	OCTET_STRING_t	 dhID;
	Time32_t	*dhStartTime	/* OPTIONAL */;
	Time32_t	*dhExpireTime	/* OPTIONAL */;
	ECDHContent_t	 dhData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECDHMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_ECDHMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_ECDHMessage_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHMessage_H_ */
#include <asn_internal.h>
