/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHConfirm_H_
#define	_ECDHConfirm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHConfirm */
typedef struct ECDHConfirm {
	OCTET_STRING_t	 confirmDataS;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECDHConfirm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHConfirm;
extern asn_SEQUENCE_specifics_t asn_SPC_ECDHConfirm_specs_1;
extern asn_TYPE_member_t asn_MBR_ECDHConfirm_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHConfirm_H_ */
#include <asn_internal.h>
