/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ECDHExChangeData_H_
#define	_ECDHExChangeData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECDHMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ECDHExChangeData */
typedef ECDHMessage_t	 ECDHExChangeData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECDHExChangeData;
asn_struct_free_f ECDHExChangeData_free;
asn_struct_print_f ECDHExChangeData_print;
asn_constr_check_f ECDHExChangeData_constraint;
ber_type_decoder_f ECDHExChangeData_decode_ber;
der_type_encoder_f ECDHExChangeData_encode_der;
xer_type_decoder_f ECDHExChangeData_decode_xer;
xer_type_encoder_f ECDHExChangeData_encode_xer;
oer_type_decoder_f ECDHExChangeData_decode_oer;
oer_type_encoder_f ECDHExChangeData_encode_oer;
per_type_decoder_f ECDHExChangeData_decode_uper;
per_type_encoder_f ECDHExChangeData_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ECDHExChangeData_H_ */
#include <asn_internal.h>
