/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_NormalCertRequest_H_
#define	_NormalCertRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NormalCertRequest */
typedef CertRequest_t	 NormalCertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NormalCertRequest;
asn_struct_free_f NormalCertRequest_free;
asn_struct_print_f NormalCertRequest_print;
asn_constr_check_f NormalCertRequest_constraint;
ber_type_decoder_f NormalCertRequest_decode_ber;
der_type_encoder_f NormalCertRequest_encode_der;
xer_type_decoder_f NormalCertRequest_decode_xer;
xer_type_encoder_f NormalCertRequest_encode_xer;
oer_type_decoder_f NormalCertRequest_decode_oer;
oer_type_encoder_f NormalCertRequest_encode_oer;
per_type_decoder_f NormalCertRequest_decode_uper;
per_type_encoder_f NormalCertRequest_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NormalCertRequest_H_ */
#include <asn_internal.h>
