/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_NormalCertRequestSign_H_
#define	_NormalCertRequestSign_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecureMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NormalCertRequestSign */
typedef SecureMessage_t	 NormalCertRequestSign_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NormalCertRequestSign;
asn_struct_free_f NormalCertRequestSign_free;
asn_struct_print_f NormalCertRequestSign_print;
asn_constr_check_f NormalCertRequestSign_constraint;
ber_type_decoder_f NormalCertRequestSign_decode_ber;
der_type_encoder_f NormalCertRequestSign_encode_der;
xer_type_decoder_f NormalCertRequestSign_decode_xer;
xer_type_encoder_f NormalCertRequestSign_encode_xer;
oer_type_decoder_f NormalCertRequestSign_decode_oer;
oer_type_encoder_f NormalCertRequestSign_encode_oer;
per_type_decoder_f NormalCertRequestSign_decode_uper;
per_type_encoder_f NormalCertRequestSign_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NormalCertRequestSign_H_ */
#include <asn_internal.h>
