/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_NormalCertResp_H_
#define	_NormalCertResp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecureMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NormalCertResp */
typedef SecureMessage_t	 NormalCertResp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NormalCertResp;
asn_struct_free_f NormalCertResp_free;
asn_struct_print_f NormalCertResp_print;
asn_constr_check_f NormalCertResp_constraint;
ber_type_decoder_f NormalCertResp_decode_ber;
der_type_encoder_f NormalCertResp_encode_der;
xer_type_decoder_f NormalCertResp_decode_xer;
xer_type_encoder_f NormalCertResp_encode_xer;
oer_type_decoder_f NormalCertResp_decode_oer;
oer_type_encoder_f NormalCertResp_encode_oer;
per_type_decoder_f NormalCertResp_decode_uper;
per_type_encoder_f NormalCertResp_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NormalCertResp_H_ */
#include <asn_internal.h>
