/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_NormalCertRequestEnc_H_
#define	_NormalCertRequestEnc_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecureMessage.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NormalCertRequestEnc */
typedef SecureMessage_t	 NormalCertRequestEnc_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NormalCertRequestEnc;
asn_struct_free_f NormalCertRequestEnc_free;
asn_struct_print_f NormalCertRequestEnc_print;
asn_constr_check_f NormalCertRequestEnc_constraint;
ber_type_decoder_f NormalCertRequestEnc_decode_ber;
der_type_encoder_f NormalCertRequestEnc_encode_der;
xer_type_decoder_f NormalCertRequestEnc_decode_xer;
xer_type_encoder_f NormalCertRequestEnc_encode_xer;
oer_type_decoder_f NormalCertRequestEnc_decode_oer;
oer_type_encoder_f NormalCertRequestEnc_encode_oer;
per_type_decoder_f NormalCertRequestEnc_decode_uper;
per_type_encoder_f NormalCertRequestEnc_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NormalCertRequestEnc_H_ */
#include <asn_internal.h>
