/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BasicSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationSet4Way;
extern struct asn_TYPE_descriptor_s asn_DEF_Acceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRate;
extern struct asn_TYPE_descriptor_s asn_DEF_Speed;
extern struct asn_TYPE_descriptor_s asn_DEF_Heading;
extern struct asn_TYPE_descriptor_s asn_DEF_CoarseHeading;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_MotionConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_HeadingConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngleConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_DefPosition_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_DefPosition_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_DefPosition_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_ElevationConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOffsetLLV;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B14;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B16;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B18;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B22;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B24;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_24B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_28B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_32B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_36B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_44B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LL_48B;
extern struct asn_TYPE_descriptor_s asn_DEF_Position_LLmD_64b;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOffsetLL;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B07;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B08;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B09;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B10;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B11;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_DSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_DYear;
extern struct asn_TYPE_descriptor_s asn_DEF_DMonth;
extern struct asn_TYPE_descriptor_s asn_DEF_DDay;
extern struct asn_TYPE_descriptor_s asn_DEF_DHour;
extern struct asn_TYPE_descriptor_s asn_DEF_DMinute;
extern struct asn_TYPE_descriptor_s asn_DEF_DTimeOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_DDateTime;
extern struct asn_TYPE_descriptor_s asn_DEF_MinuteOfTheYear;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeMark;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint3;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint8;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint16;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint32;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint64;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlSeries;
extern struct asn_TYPE_descriptor_s asn_DEF_Opaque;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId8;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId3;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId10;
extern struct asn_TYPE_descriptor_s asn_DEF_Time32;
extern struct asn_TYPE_descriptor_s asn_DEF_Time64;
extern struct asn_TYPE_descriptor_s asn_DEF_HashAlgorithm;
extern struct asn_TYPE_descriptor_s asn_DEF_CipherText;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmetricAlgorithm;
extern struct asn_TYPE_descriptor_s asn_DEF_EccCurve;
extern struct asn_TYPE_descriptor_s asn_DEF_CircularRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_TwoDLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_NinetyDegreeInt;
extern struct asn_TYPE_descriptor_s asn_DEF_Ieee1GMV2X_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Ieee1GMV2X_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_OneEightyDegreeInt;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_RectangularRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfRectangularRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_GeographicRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_PolygonalRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_ECCPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicVerifyKey;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicEncryptionKey;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectType;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ItsAid;
extern struct asn_TYPE_descriptor_s asn_DEF_ItsAidSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectAssurance;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfitsAidList;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfitsAidSspList;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectAttribute;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeStartAndEnd;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidityPeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidityRestriction;
extern struct asn_TYPE_descriptor_s asn_DEF_TbsCert;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateDigest;
extern struct asn_TYPE_descriptor_s asn_DEF_IssuerId;
extern struct asn_TYPE_descriptor_s asn_DEF_Signature;
extern struct asn_TYPE_descriptor_s asn_DEF_Certificate;
extern struct asn_TYPE_descriptor_s asn_DEF_RevokeInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfRevokeInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedCrl;
extern struct asn_TYPE_descriptor_s asn_DEF_Crl;
extern struct asn_TYPE_descriptor_s asn_DEF_Ieee1GMV2X_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_ThreeDLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_HeaderInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_TBSData;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfCertificate;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedData;
extern struct asn_TYPE_descriptor_s asn_DEF_SM4CipherTextCbc;
extern struct asn_TYPE_descriptor_s asn_DEF_AesCcmCipherText;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmetricCipherText;
extern struct asn_TYPE_descriptor_s asn_DEF_EciesEncryptedKey;
extern struct asn_TYPE_descriptor_s asn_DEF_PKRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_PreSharedKeyRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmRecipInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_RecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptedData;
extern struct asn_TYPE_descriptor_s asn_DEF_Payload;
extern struct asn_TYPE_descriptor_s asn_DEF_SecureMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_CertRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_EnrollmentCertRequestData;
extern struct asn_TYPE_descriptor_s asn_DEF_EnrollmentCertRespData;
extern struct asn_TYPE_descriptor_s asn_DEF_EnrollmentCertResp;
extern struct asn_TYPE_descriptor_s asn_DEF_NormalCertRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_NormalCertRequestEnc;
extern struct asn_TYPE_descriptor_s asn_DEF_NormalCertRequestSign;
extern struct asn_TYPE_descriptor_s asn_DEF_NormalCertRespData;
extern struct asn_TYPE_descriptor_s asn_DEF_NormalCertResp;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_StaticEncryptMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_EphemeralEncryptMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_SignEncryptMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_DHResult;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfHashID8;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHData;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHConfirm;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHResult;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHContent;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHExChangeData;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHExChangeConfirmOrResult;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHRequestData;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHResponseData;
extern struct asn_TYPE_descriptor_s asn_DEF_ECDHConfirmOrResultData;
extern struct asn_TYPE_descriptor_s asn_DEF_MapData;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneList;
extern struct asn_TYPE_descriptor_s asn_DEF_Lane;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneID;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectsToList;
extern struct asn_TYPE_descriptor_s asn_DEF_Connection;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectingLane;
extern struct asn_TYPE_descriptor_s asn_DEF_AllowedManeuvers;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneSharing;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneTypeAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Vehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Crosswalk;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Bike;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Sidewalk;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Barrier;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Striping;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_TrackedVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Parking;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkList;
extern struct asn_TYPE_descriptor_s asn_DEF_Link;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementList;
extern struct asn_TYPE_descriptor_s asn_DEF_Movement;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeList;
extern struct asn_TYPE_descriptor_s asn_DEF_Node;
extern struct asn_TYPE_descriptor_s asn_DEF_DescriptiveName;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeReferenceID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadRegulatorID;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeID;
extern struct asn_TYPE_descriptor_s asn_DEF_PointList;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitList;
extern struct asn_TYPE_descriptor_s asn_DEF_RegulatorySpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitType;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_MsgCount;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSideInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_Radius;
extern struct asn_TYPE_descriptor_s asn_DEF_AlertType;
extern struct asn_TYPE_descriptor_s asn_DEF_Priority;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadsideSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantList;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantData;
extern struct asn_TYPE_descriptor_s asn_DEF_ParticipantType;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceType;
extern struct asn_TYPE_descriptor_s asn_DEF_SPAT;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStateList;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionState;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStatusObject;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseList;
extern struct asn_TYPE_descriptor_s asn_DEF_Phase;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseStateList;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseState;
extern struct asn_TYPE_descriptor_s asn_DEF_LightState;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeChangeDetails;
extern struct asn_TYPE_descriptor_s asn_DEF_PhaseID;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeSystemStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakePedalStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeAppliedStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeBoostApplied;
extern struct asn_TYPE_descriptor_s asn_DEF_TractionControlStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_AntiLockBrakeStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_StabilityControlStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_AuxiliaryBrakeStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleClassification;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicVehicleClass;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSafetyExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistory;
extern struct asn_TYPE_descriptor_s asn_DEF_FullPositionVector;
extern struct asn_TYPE_descriptor_s asn_DEF_GNSSstatus;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistoryPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistoryPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPrediction;
extern struct asn_TYPE_descriptor_s asn_DEF_Confidence;
extern struct asn_TYPE_descriptor_s asn_DEF_RadiusOfCurvature;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSize;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleHeight;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionState;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleEventFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_ExteriorLights;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module BSM in asn/BSM.asn */
	&asn_DEF_BasicSafetyMessage,	
	/* From module DefAcceleration in asn/DefAcceleration.asn */
	&asn_DEF_AccelerationSet4Way,	
	&asn_DEF_Acceleration,	
	&asn_DEF_VerticalAcceleration,	
	&asn_DEF_YawRate,	
	/* From module DefMotion in asn/DefMotion.asn */
	&asn_DEF_Speed,	
	&asn_DEF_Heading,	
	&asn_DEF_CoarseHeading,	
	&asn_DEF_SteeringWheelAngle,	
	&asn_DEF_MotionConfidenceSet,	
	&asn_DEF_HeadingConfidence,	
	&asn_DEF_SpeedConfidence,	
	&asn_DEF_SteeringWheelAngleConfidence,	
	/* From module DefPosition in asn/DefPosition.asn */
	&asn_DEF_DefPosition_Latitude,	
	&asn_DEF_DefPosition_Longitude,	
	&asn_DEF_DefPosition_Elevation,	
	&asn_DEF_PositionConfidenceSet,	
	&asn_DEF_PositionConfidence,	
	&asn_DEF_ElevationConfidence,	
	&asn_DEF_Position3D,	
	/* From module DefPositionOffset in asn/DefPositionOffset.asn */
	&asn_DEF_PositionOffsetLLV,	
	&asn_DEF_OffsetLL_B12,	
	&asn_DEF_OffsetLL_B14,	
	&asn_DEF_OffsetLL_B16,	
	&asn_DEF_OffsetLL_B18,	
	&asn_DEF_OffsetLL_B22,	
	&asn_DEF_OffsetLL_B24,	
	&asn_DEF_Position_LL_24B,	
	&asn_DEF_Position_LL_28B,	
	&asn_DEF_Position_LL_32B,	
	&asn_DEF_Position_LL_36B,	
	&asn_DEF_Position_LL_44B,	
	&asn_DEF_Position_LL_48B,	
	&asn_DEF_Position_LLmD_64b,	
	&asn_DEF_PositionOffsetLL,	
	&asn_DEF_VerticalOffset,	
	&asn_DEF_VertOffset_B07,	
	&asn_DEF_VertOffset_B08,	
	&asn_DEF_VertOffset_B09,	
	&asn_DEF_VertOffset_B10,	
	&asn_DEF_VertOffset_B11,	
	&asn_DEF_VertOffset_B12,	
	/* From module DefTime in asn/DefTime.asn */
	&asn_DEF_DSecond,	
	&asn_DEF_DYear,	
	&asn_DEF_DMonth,	
	&asn_DEF_DDay,	
	&asn_DEF_DHour,	
	&asn_DEF_DMinute,	
	&asn_DEF_DTimeOffset,	
	&asn_DEF_DDateTime,	
	&asn_DEF_MinuteOfTheYear,	
	&asn_DEF_TimeMark,	
	&asn_DEF_TimeOffset,	
	&asn_DEF_TimeConfidence,	
	/* From module Ieee1GMV2X in asn/GM.asn */
	&asn_DEF_Uint3,	
	&asn_DEF_Uint8,	
	&asn_DEF_Uint16,	
	&asn_DEF_Uint32,	
	&asn_DEF_Uint64,	
	&asn_DEF_CrlSeries,	
	&asn_DEF_Opaque,	
	&asn_DEF_HashedId8,	
	&asn_DEF_HashedId3,	
	&asn_DEF_HashedId10,	
	&asn_DEF_Time32,	
	&asn_DEF_Time64,	
	&asn_DEF_HashAlgorithm,	
	&asn_DEF_CipherText,	
	&asn_DEF_SymmetricAlgorithm,	
	&asn_DEF_EccCurve,	
	&asn_DEF_CircularRegion,	
	&asn_DEF_TwoDLocation,	
	&asn_DEF_NinetyDegreeInt,	
	&asn_DEF_Ieee1GMV2X_Latitude,	
	&asn_DEF_KnownLatitude,	
	&asn_DEF_UnknownLatitude,	
	&asn_DEF_Ieee1GMV2X_Longitude,	
	&asn_DEF_OneEightyDegreeInt,	
	&asn_DEF_KnownLongitude,	
	&asn_DEF_UnknownLongitude,	
	&asn_DEF_RectangularRegion,	
	&asn_DEF_SequenceOfRectangularRegion,	
	&asn_DEF_GeographicRegion,	
	&asn_DEF_PolygonalRegion,	
	&asn_DEF_ECCPoint,	
	&asn_DEF_PublicVerifyKey,	
	&asn_DEF_PublicEncryptionKey,	
	&asn_DEF_SubjectType,	
	&asn_DEF_SubjectInfo,	
	&asn_DEF_ItsAid,	
	&asn_DEF_ItsAidSsp,	
	&asn_DEF_SubjectAssurance,	
	&asn_DEF_SequenceOfitsAidList,	
	&asn_DEF_SequenceOfitsAidSspList,	
	&asn_DEF_SubjectAttribute,	
	&asn_DEF_TimeStartAndEnd,	
	&asn_DEF_ValidityPeriod,	
	&asn_DEF_ValidityRestriction,	
	&asn_DEF_TbsCert,	
	&asn_DEF_CertificateDigest,	
	&asn_DEF_IssuerId,	
	&asn_DEF_Signature,	
	&asn_DEF_Certificate,	
	&asn_DEF_RevokeInfo,	
	&asn_DEF_SequenceOfRevokeInfo,	
	&asn_DEF_ToBeSignedCrl,	
	&asn_DEF_Crl,	
	&asn_DEF_Ieee1GMV2X_Elevation,	
	&asn_DEF_ThreeDLocation,	
	&asn_DEF_HeaderInfo,	
	&asn_DEF_TBSData,	
	&asn_DEF_SequenceOfCertificate,	
	&asn_DEF_SignerInfo,	
	&asn_DEF_SignedData,	
	&asn_DEF_SM4CipherTextCbc,	
	&asn_DEF_AesCcmCipherText,	
	&asn_DEF_SymmetricCipherText,	
	&asn_DEF_EciesEncryptedKey,	
	&asn_DEF_PKRecipientInfo,	
	&asn_DEF_PreSharedKeyRecipientInfo,	
	&asn_DEF_SymmRecipInfo,	
	&asn_DEF_RecipientInfo,	
	&asn_DEF_SequenceOfRecipientInfo,	
	&asn_DEF_EncryptedData,	
	&asn_DEF_Payload,	
	&asn_DEF_SecureMessage,	
	&asn_DEF_CertRequest,	
	&asn_DEF_EnrollmentCertRequestData,	
	&asn_DEF_EnrollmentCertRespData,	
	&asn_DEF_EnrollmentCertResp,	
	&asn_DEF_NormalCertRequest,	
	&asn_DEF_NormalCertRequestEnc,	
	&asn_DEF_NormalCertRequestSign,	
	&asn_DEF_NormalCertRespData,	
	&asn_DEF_NormalCertResp,	
	&asn_DEF_SignedMessage,	
	&asn_DEF_StaticEncryptMessage,	
	&asn_DEF_EphemeralEncryptMessage,	
	&asn_DEF_SignEncryptMessage,	
	&asn_DEF_DHResult,	
	&asn_DEF_SequenceOfHashID8,	
	&asn_DEF_ECDHData,	
	&asn_DEF_ECDHConfirm,	
	&asn_DEF_ECDHResult,	
	&asn_DEF_ECDHContent,	
	&asn_DEF_ECDHMessage,	
	&asn_DEF_ECDHExChangeData,	
	&asn_DEF_ECDHExChangeConfirmOrResult,	
	&asn_DEF_ECDHRequestData,	
	&asn_DEF_ECDHResponseData,	
	&asn_DEF_ECDHConfirmOrResultData,	
	/* From module Map in asn/Map.asn */
	&asn_DEF_MapData,	
	/* From module MapLane in asn/MapLane.asn */
	&asn_DEF_LaneList,	
	&asn_DEF_Lane,	
	&asn_DEF_LaneID,	
	&asn_DEF_LaneWidth,	
	&asn_DEF_ConnectsToList,	
	&asn_DEF_Connection,	
	&asn_DEF_ConnectingLane,	
	&asn_DEF_AllowedManeuvers,	
	&asn_DEF_LaneAttributes,	
	&asn_DEF_LaneSharing,	
	&asn_DEF_LaneTypeAttributes,	
	&asn_DEF_LaneAttributes_Vehicle,	
	&asn_DEF_LaneAttributes_Crosswalk,	
	&asn_DEF_LaneAttributes_Bike,	
	&asn_DEF_LaneAttributes_Sidewalk,	
	&asn_DEF_LaneAttributes_Barrier,	
	&asn_DEF_LaneAttributes_Striping,	
	&asn_DEF_LaneAttributes_TrackedVehicle,	
	&asn_DEF_LaneAttributes_Parking,	
	/* From module MapLink in asn/MapLink.asn */
	&asn_DEF_LinkList,	
	&asn_DEF_Link,	
	&asn_DEF_MovementList,	
	&asn_DEF_Movement,	
	/* From module MapNode in asn/MapNode.asn */
	&asn_DEF_NodeList,	
	&asn_DEF_Node,	
	&asn_DEF_DescriptiveName,	
	&asn_DEF_NodeReferenceID,	
	&asn_DEF_RoadRegulatorID,	
	&asn_DEF_NodeID,	
	/* From module MapPoint in asn/MapPoint.asn */
	&asn_DEF_PointList,	
	&asn_DEF_RoadPoint,	
	/* From module MapSpeedLimit in asn/MapSpeedLimit.asn */
	&asn_DEF_SpeedLimitList,	
	&asn_DEF_RegulatorySpeedLimit,	
	&asn_DEF_SpeedLimitType,	
	/* From module MsgFrame in asn/MsgFrame.asn */
	&asn_DEF_MessageFrame,	
	&asn_DEF_MsgCount,	
	/* From module RSI in asn/RSI.asn */
	&asn_DEF_RoadSideInformation,	
	&asn_DEF_PathPointList,	
	&asn_DEF_Radius,	
	&asn_DEF_AlertType,	
	&asn_DEF_Priority,	
	/* From module RSM in asn/RSM.asn */
	&asn_DEF_RoadsideSafetyMessage,	
	&asn_DEF_ParticipantList,	
	&asn_DEF_ParticipantData,	
	&asn_DEF_ParticipantType,	
	&asn_DEF_SourceType,	
	/* From module SignalPhaseAndTiming in asn/SignalPhaseAndTiming.asn */
	&asn_DEF_SPAT,	
	/* From module SPATIntersectionState in asn/SPATIntersectionState.asn */
	&asn_DEF_IntersectionStateList,	
	&asn_DEF_IntersectionState,	
	&asn_DEF_IntersectionStatusObject,	
	&asn_DEF_PhaseList,	
	&asn_DEF_Phase,	
	&asn_DEF_PhaseStateList,	
	&asn_DEF_PhaseState,	
	&asn_DEF_LightState,	
	&asn_DEF_TimeChangeDetails,	
	&asn_DEF_PhaseID,	
	/* From module VehBrake in asn/VehBrake.asn */
	&asn_DEF_BrakeSystemStatus,	
	&asn_DEF_BrakePedalStatus,	
	&asn_DEF_BrakeAppliedStatus,	
	&asn_DEF_BrakeBoostApplied,	
	&asn_DEF_TractionControlStatus,	
	&asn_DEF_AntiLockBrakeStatus,	
	&asn_DEF_StabilityControlStatus,	
	&asn_DEF_AuxiliaryBrakeStatus,	
	/* From module VehClass in asn/VehClass.asn */
	&asn_DEF_VehicleClassification,	
	&asn_DEF_BasicVehicleClass,	
	/* From module VehSafetyExt in asn/VehSafetyExt.asn */
	&asn_DEF_VehicleSafetyExtensions,	
	&asn_DEF_PathHistory,	
	&asn_DEF_FullPositionVector,	
	&asn_DEF_GNSSstatus,	
	&asn_DEF_PathHistoryPointList,	
	&asn_DEF_PathHistoryPoint,	
	&asn_DEF_PathPrediction,	
	&asn_DEF_Confidence,	
	&asn_DEF_RadiusOfCurvature,	
	/* From module VehSize in asn/VehSize.asn */
	&asn_DEF_VehicleSize,	
	&asn_DEF_VehicleWidth,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleHeight,	
	/* From module VehStatus in asn/VehStatus.asn */
	&asn_DEF_TransmissionState,	
	&asn_DEF_VehicleEventFlags,	
	&asn_DEF_ExteriorLights,	
	0
};

