/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#include "RevokeInfo.h"

asn_TYPE_member_t asn_MBR_RevokeInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RevokeInfo, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashedId10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RevokeInfo, hashAlg),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashAlgorithm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashAlg"
		},
	{ ATF_POINTER, 1, offsetof(struct RevokeInfo, expiry),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"expiry"
		},
};
static const int asn_MAP_RevokeInfo_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_RevokeInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RevokeInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hashAlg */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* expiry */
};
asn_SEQUENCE_specifics_t asn_SPC_RevokeInfo_specs_1 = {
	sizeof(struct RevokeInfo),
	offsetof(struct RevokeInfo, _asn_ctx),
	asn_MAP_RevokeInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RevokeInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RevokeInfo = {
	"RevokeInfo",
	"RevokeInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_RevokeInfo_tags_1,
	sizeof(asn_DEF_RevokeInfo_tags_1)
		/sizeof(asn_DEF_RevokeInfo_tags_1[0]), /* 1 */
	asn_DEF_RevokeInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_RevokeInfo_tags_1)
		/sizeof(asn_DEF_RevokeInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RevokeInfo_1,
	3,	/* Elements count */
	&asn_SPC_RevokeInfo_specs_1	/* Additional specs */
};

