/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_SequenceOfHashID8_H_
#define	_SequenceOfHashID8_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HashedId8.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfHashID8 */
typedef struct SequenceOfHashID8 {
	A_SEQUENCE_OF(HashedId8_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfHashID8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfHashID8;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfHashID8_H_ */
#include <asn_internal.h>
