/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_SignerInfo_H_
#define	_SignerInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "SequenceOfCertificate.h"
#include "CertificateDigest.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignerInfo_PR {
	SignerInfo_PR_NOTHING,	/* No components present */
	SignerInfo_PR_self,
	SignerInfo_PR_certificate,
	SignerInfo_PR_certificateDigest
	/* Extensions may appear below */
	
} SignerInfo_PR;

/* SignerInfo */
typedef struct SignerInfo {
	SignerInfo_PR present;
	union SignerInfo_u {
		NULL_t	 self;
		SequenceOfCertificate_t	 certificate;
		CertificateDigest_t	 certificateDigest;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerInfo;
extern asn_CHOICE_specifics_t asn_SPC_SignerInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SignerInfo_1[3];
extern asn_per_constraints_t asn_PER_type_SignerInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerInfo_H_ */
#include <asn_internal.h>
