/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ThreeDLocation_H_
#define	_ThreeDLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ieee1GMV2X_Latitude.h"
#include "Ieee1GMV2X_Longitude.h"
#include "Ieee1GMV2X_Elevation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ThreeDLocation */
typedef struct ThreeDLocation {
	Ieee1GMV2X_Latitude_t	 latitude;
	Ieee1GMV2X_Longitude_t	 longitude;
	Ieee1GMV2X_Elevation_t	 elevation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ThreeDLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThreeDLocation;
extern asn_SEQUENCE_specifics_t asn_SPC_ThreeDLocation_specs_1;
extern asn_TYPE_member_t asn_MBR_ThreeDLocation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ThreeDLocation_H_ */
#include <asn_internal.h>
