/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1GMV2X"
 * 	found in "asn/GM.asn"
 * 	`asn1c -fcompound-names -fnative-types -Werror -gen-PER -pdu=all`
 */

#ifndef	_ToBeSignedCrl_H_
#define	_ToBeSignedCrl_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint32.h"
#include "Time32.h"
#include "SequenceOfRevokeInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ToBeSignedCrl */
typedef struct ToBeSignedCrl {
	Uint32_t	 crlSerial;
	Time32_t	 issueDate;
	Time32_t	 nextCrl;
	SequenceOfRevokeInfo_t	 entries;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ToBeSignedCrl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedCrl;
extern asn_SEQUENCE_specifics_t asn_SPC_ToBeSignedCrl_specs_1;
extern asn_TYPE_member_t asn_MBR_ToBeSignedCrl_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ToBeSignedCrl_H_ */
#include <asn_internal.h>
