g_all_dll_projects ={
    {
        path="test_dll",
        dll_name="test.dll",
        src_dll_name="dll.dll",        
    },{
        path="camera_dll",
        dll_name="webcamera.dll",
        src_dll_name="dll.dll",        
    },{
        path="asn1/v2x_gb2019_dll",
        dll_name="asn1_v2x_gb2019.dll",
        src_dll_name="test.dll",     
    },{
        path="asn1/v2x_gb2017_dll",
        dll_name="asn1_v2x_gb2017.dll",
        src_dll_name="test.dll",     
    },{
        path="asn1/v2x_gb2020_dll",
        dll_name="asn1_v2x_gb2020.dll",
        src_dll_name="test.dll",     
    },{
        path="asn1/gxx_obu_dll",
        dll_name="asn1_gxx_obu.dll",
        src_dll_name="test.dll",     
    }
};
