/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_AcaEeCertResponseCubkSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaEeCertResponsePlainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaEeCertResponsePrivateSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateChainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_CompositeCrlSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EcaEeCertResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeEcaCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaCertRequestPlainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaDownloadRequestPlainSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaDownloadRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaSuccessorEnrollmentCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeCertAckSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeCertInfoSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeEnrollmentCertAckSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityMgmtAid;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaEeInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaEeCertResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaRaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_RaAcaCertRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_RaAcaCertRequestFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaRaCertResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_RaAcaCertRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaRaCertResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_CertManagementPdu;
extern struct asn_TYPE_descriptor_s asn_DEF_CompositeCrl;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateChain;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlContents;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlPriorityInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedHashIdCrl;
extern struct asn_TYPE_descriptor_s asn_DEF_HashBasedRevocationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfHashBasedRevocationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedLinkageValueCrl;
extern struct asn_TYPE_descriptor_s asn_DEF_JMaxGroup;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfJMaxGroup;
extern struct asn_TYPE_descriptor_s asn_DEF_LAGroup;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfLAGroup;
extern struct asn_TYPE_descriptor_s asn_DEF_IMaxGroup;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfIMaxGroup;
extern struct asn_TYPE_descriptor_s asn_DEF_IndividualRevocation;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfIndividualRevocation;
extern struct asn_TYPE_descriptor_s asn_DEF_CRLBaseTypes_LinkageSeed;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfLinkageSeed;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupCrlEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfGroupCrlEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupSingleSeedCrlEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfGroupSingleSeedCrlEntry;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlAid;
extern struct asn_TYPE_descriptor_s asn_DEF_SecuredCrl;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_CracaType;
extern struct asn_TYPE_descriptor_s asn_DEF_PermissibleCrls;
extern struct asn_TYPE_descriptor_s asn_DEF_RootCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedRootCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_PkiCtlInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfPkiCtlInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_PkiCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedPkiCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_PkiCertInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfPkiCertInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_EcaEeInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeEcaCertRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_EcaEeCertResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaCertRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_AdditionalParams;
extern struct asn_TYPE_descriptor_s asn_DEF_ButterflyParamsOriginal;
extern struct asn_TYPE_descriptor_s asn_DEF_ButterflyExpansion;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeCertInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_EeRaDownloadRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_AaaAuthorizationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfAaaAuthorizationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_RaEeCertAck;
extern struct asn_TYPE_descriptor_s asn_DEF_LaMaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_MaLaLinkageSeedRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_IndividualLV;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupLV;
extern struct asn_TYPE_descriptor_s asn_DEF_LaMaLinkageSeedResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_IndividualLSInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupLSInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_MaLaLinkageSeedRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_LaMaLinkageSeedResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_LaRaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaLinkageValueRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaIndividualLinkageValueRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkageChainId;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaGroupLinkageValueRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaRequestHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_LaPraLinkageValueResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_IndividualLVResponseLinkageChain;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupLVResponseLinkageChain;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptedIndividualLV;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptedGroupLV;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaIndividualLinkageValueRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_PraLaGroupLinkageValueRequestSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_LaPraLinkageValueResponseSpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_ScmsPdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaLaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaMaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_MaRaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_EeMaInterfacePdu;
extern struct asn_TYPE_descriptor_s asn_DEF_ScmsSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_RootCaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_MaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_PgSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_IcaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_EcaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_AcaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_CraSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_DcmSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_LaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_RaSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_EeSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint3;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint8;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint16;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint32;
extern struct asn_TYPE_descriptor_s asn_DEF_Uint64;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfUint8;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfUint16;
extern struct asn_TYPE_descriptor_s asn_DEF_Opaque;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId32;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId10;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId8;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId4;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedId3;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfHashedId3;
extern struct asn_TYPE_descriptor_s asn_DEF_Time32;
extern struct asn_TYPE_descriptor_s asn_DEF_Time64;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidityPeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_Duration;
extern struct asn_TYPE_descriptor_s asn_DEF_GeographicRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_CircularRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_RectangularRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfRectangularRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_PolygonalRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_TwoDLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_IdentifiedRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfIdentifiedRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_CountryOnly;
extern struct asn_TYPE_descriptor_s asn_DEF_CountryAndRegions;
extern struct asn_TYPE_descriptor_s asn_DEF_CountryAndSubregions;
extern struct asn_TYPE_descriptor_s asn_DEF_RegionAndSubregions;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfRegionAndSubregions;
extern struct asn_TYPE_descriptor_s asn_DEF_ThreeDLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_NinetyDegreeInt;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_OneEightyDegreeInt;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_ElevInt;
extern struct asn_TYPE_descriptor_s asn_DEF_Signature;
extern struct asn_TYPE_descriptor_s asn_DEF_EcdsaP256Signature;
extern struct asn_TYPE_descriptor_s asn_DEF_EcsigP256Signature;
extern struct asn_TYPE_descriptor_s asn_DEF_EcdsaP384Signature;
extern struct asn_TYPE_descriptor_s asn_DEF_EccP256CurvePoint;
extern struct asn_TYPE_descriptor_s asn_DEF_EccP384CurvePoint;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmAlgorithm;
extern struct asn_TYPE_descriptor_s asn_DEF_HashAlgorithm;
extern struct asn_TYPE_descriptor_s asn_DEF_EciesP256EncryptedKey;
extern struct asn_TYPE_descriptor_s asn_DEF_EcencP256EncryptedKey;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptionKey;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicEncryptionKey;
extern struct asn_TYPE_descriptor_s asn_DEF_BasePublicEncryptionKey;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicVerificationKey;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmetricEncryptionKey;
extern struct asn_TYPE_descriptor_s asn_DEF_AidSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfAidSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_Aid;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfAid;
extern struct asn_TYPE_descriptor_s asn_DEF_ServiceSpecificPermissions;
extern struct asn_TYPE_descriptor_s asn_DEF_BitmapSsp;
extern struct asn_TYPE_descriptor_s asn_DEF_SspValue;
extern struct asn_TYPE_descriptor_s asn_DEF_SspBitmask;
extern struct asn_TYPE_descriptor_s asn_DEF_AidSspRange;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfAidSspRange;
extern struct asn_TYPE_descriptor_s asn_DEF_SspRange;
extern struct asn_TYPE_descriptor_s asn_DEF_BitmapSspRange;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfOctetString;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectAssurance;
extern struct asn_TYPE_descriptor_s asn_DEF_CrlSeries;
extern struct asn_TYPE_descriptor_s asn_DEF_IValue;
extern struct asn_TYPE_descriptor_s asn_DEF_Hostname;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkageValue;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupLinkageValue;
extern struct asn_TYPE_descriptor_s asn_DEF_LaId;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityBaseDataTypes_LinkageSeed;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedDataPayload;
extern struct asn_TYPE_descriptor_s asn_DEF_V2XSecData;
extern struct asn_TYPE_descriptor_s asn_DEF_V2XSecContent;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedData;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedData;
extern struct asn_TYPE_descriptor_s asn_DEF_HashedData;
extern struct asn_TYPE_descriptor_s asn_DEF_HeaderInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_MissingCrlIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_PduFunctionalType;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptedData;
extern struct asn_TYPE_descriptor_s asn_DEF_RecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_PreSharedKeyRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_PKRecipientInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptedDataEncryptionKey;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmetricCiphertext;
extern struct asn_TYPE_descriptor_s asn_DEF_One28BitCcmCiphertext;
extern struct asn_TYPE_descriptor_s asn_DEF_Certificate;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfCertificate;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateBase;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateType;
extern struct asn_TYPE_descriptor_s asn_DEF_ExplicitCertificate;
extern struct asn_TYPE_descriptor_s asn_DEF_Reserved;
extern struct asn_TYPE_descriptor_s asn_DEF_IssuerIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_ToBeSignedCertificate;
extern struct asn_TYPE_descriptor_s asn_DEF_CertificateId;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkageData;
extern struct asn_TYPE_descriptor_s asn_DEF_EndEntityType;
extern struct asn_TYPE_descriptor_s asn_DEF_AidGroupPermissions;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfAidGroupPermissions;
extern struct asn_TYPE_descriptor_s asn_DEF_SubjectPermissions;
extern struct asn_TYPE_descriptor_s asn_DEF_VerificationKeyIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_V2XSecData_EncryptedOpen;
extern struct asn_TYPE_descriptor_s asn_DEF_ScmsPdu_Scoped;
extern struct asn_TYPE_descriptor_s asn_DEF_ScopedCertificateRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedCertificateRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerSelf;
extern struct asn_TYPE_descriptor_s asn_DEF_SignerSingleCert;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module AcaEeCertResponseCubkSpdu in asn/AcaEeCertResponseCubkSpdu.asn */
	&asn_DEF_AcaEeCertResponseCubkSpdu,	
	&asn_DEF_AcaEeCertResponsePlainSpdu,	
	&asn_DEF_AcaEeCertResponsePrivateSpdu,	
	&asn_DEF_CertificateChainSpdu,	
	&asn_DEF_CompositeCrlSpdu,	
	&asn_DEF_EcaEeCertResponseSpdu,	
	&asn_DEF_EeEcaCertRequestSpdu,	
	&asn_DEF_EeRaCertRequestPlainSpdu,	
	&asn_DEF_EeRaCertRequestSpdu,	
	&asn_DEF_EeRaDownloadRequestPlainSpdu,	
	&asn_DEF_EeRaDownloadRequestSpdu,	
	&asn_DEF_EeRaSuccessorEnrollmentCertRequestSpdu,	
	&asn_DEF_RaEeCertAckSpdu,	
	&asn_DEF_RaEeCertInfoSpdu,	
	&asn_DEF_RaEeEnrollmentCertAckSpdu,	
	&asn_DEF_SecurityMgmtAid,	
	/* From module AcaEeInterfacePdu in asn/AcaEeInterfacePdu.asn */
	&asn_DEF_AcaEeInterfacePdu,	
	&asn_DEF_AcaEeCertResponse,	
	/* From module AcaRaInterfacePdu in asn/AcaRaInterfacePdu.asn */
	&asn_DEF_AcaRaInterfacePdu,	
	&asn_DEF_RaAcaCertRequest,	
	&asn_DEF_RaAcaCertRequestFlags,	
	&asn_DEF_AcaRaCertResponse,	
	&asn_DEF_AcaResponse,	
	&asn_DEF_RaAcaCertRequestSpdu,	
	&asn_DEF_AcaRaCertResponseSpdu,	
	/* From module CertManagementPdu in asn/CertManagementPdu.asn */
	&asn_DEF_CertManagementPdu,	
	&asn_DEF_CompositeCrl,	
	&asn_DEF_CertificateChain,	
	/* From module CRLBaseTypes in asn/CRLBaseTypes.asn */
	&asn_DEF_CrlContents,	
	&asn_DEF_CrlPriorityInfo,	
	&asn_DEF_ToBeSignedHashIdCrl,	
	&asn_DEF_HashBasedRevocationInfo,	
	&asn_DEF_SequenceOfHashBasedRevocationInfo,	
	&asn_DEF_ToBeSignedLinkageValueCrl,	
	&asn_DEF_JMaxGroup,	
	&asn_DEF_SequenceOfJMaxGroup,	
	&asn_DEF_LAGroup,	
	&asn_DEF_SequenceOfLAGroup,	
	&asn_DEF_IMaxGroup,	
	&asn_DEF_SequenceOfIMaxGroup,	
	&asn_DEF_IndividualRevocation,	
	&asn_DEF_SequenceOfIndividualRevocation,	
	&asn_DEF_CRLBaseTypes_LinkageSeed,	
	&asn_DEF_SequenceOfLinkageSeed,	
	&asn_DEF_GroupCrlEntry,	
	&asn_DEF_SequenceOfGroupCrlEntry,	
	&asn_DEF_GroupSingleSeedCrlEntry,	
	&asn_DEF_SequenceOfGroupSingleSeedCrlEntry,	
	/* From module SecuredCrl in asn/CRLSecurityPacage.asn */
	&asn_DEF_CrlAid,	
	&asn_DEF_SecuredCrl,	
	/* From module CrlSsp in asn/CRLSSP.asn */
	&asn_DEF_CrlSsp,	
	&asn_DEF_CracaType,	
	&asn_DEF_PermissibleCrls,	
	/* From module CTL in asn/CTL.asn */
	&asn_DEF_RootCtl,	
	&asn_DEF_ToBeSignedRootCtl,	
	&asn_DEF_PkiCtlInfo,	
	&asn_DEF_SequenceOfPkiCtlInfo,	
	&asn_DEF_PkiCtl,	
	&asn_DEF_ToBeSignedPkiCtl,	
	&asn_DEF_PkiCertInfo,	
	&asn_DEF_SequenceOfPkiCertInfo,	
	/* From module EcaEeInterfacePdu in asn/EcaEeInterfacePdu.asn */
	&asn_DEF_EcaEeInterfacePdu,	
	&asn_DEF_EeEcaCertRequest,	
	&asn_DEF_EcaEeCertResponse,	
	/* From module EeRaInterfacePdu in asn/EeRaInterfacePdu.asn */
	&asn_DEF_EeRaInterfacePdu,	
	&asn_DEF_EeRaCertRequest,	
	&asn_DEF_AdditionalParams,	
	&asn_DEF_ButterflyParamsOriginal,	
	&asn_DEF_ButterflyExpansion,	
	&asn_DEF_RaEeCertInfo,	
	&asn_DEF_EeRaDownloadRequest,	
	&asn_DEF_AaaAuthorizationInfo,	
	&asn_DEF_SequenceOfAaaAuthorizationInfo,	
	&asn_DEF_RaEeCertAck,	
	/* From module LaMaInterfacePdu in asn/LaMaInterfacePdu.asn */
	&asn_DEF_LaMaInterfacePdu,	
	&asn_DEF_MaLaLinkageSeedRequest,	
	&asn_DEF_IndividualLV,	
	&asn_DEF_GroupLV,	
	&asn_DEF_LaMaLinkageSeedResponse,	
	&asn_DEF_IndividualLSInfo,	
	&asn_DEF_GroupLSInfo,	
	&asn_DEF_MaLaLinkageSeedRequestSpdu,	
	&asn_DEF_LaMaLinkageSeedResponseSpdu,	
	/* From module LaRaInterfacePdu in asn/LaRaInterfacePdu.asn */
	&asn_DEF_LaRaInterfacePdu,	
	&asn_DEF_PraLaLinkageValueRequest,	
	&asn_DEF_PraLaIndividualLinkageValueRequest,	
	&asn_DEF_LinkageChainId,	
	&asn_DEF_PraLaGroupLinkageValueRequest,	
	&asn_DEF_PraLaRequestHeader,	
	&asn_DEF_LaPraLinkageValueResponse,	
	&asn_DEF_IndividualLVResponseLinkageChain,	
	&asn_DEF_GroupLVResponseLinkageChain,	
	&asn_DEF_EncryptedIndividualLV,	
	&asn_DEF_EncryptedGroupLV,	
	&asn_DEF_PraLaIndividualLinkageValueRequestSpdu,	
	&asn_DEF_PraLaGroupLinkageValueRequestSpdu,	
	&asn_DEF_LaPraLinkageValueResponseSpdu,	
	/* From module ScmsPdu in asn/ScmsPdu.asn */
	&asn_DEF_ScmsPdu,	
	&asn_DEF_AcaLaInterfacePdu,	
	&asn_DEF_AcaMaInterfacePdu,	
	&asn_DEF_MaRaInterfacePdu,	
	&asn_DEF_EeMaInterfacePdu,	
	/* From module ScmsSsp in asn/ScmsSsp.asn */
	&asn_DEF_ScmsSsp,	
	&asn_DEF_RootCaSsp,	
	&asn_DEF_MaSsp,	
	&asn_DEF_PgSsp,	
	&asn_DEF_IcaSsp,	
	&asn_DEF_EcaSsp,	
	&asn_DEF_AcaSsp,	
	&asn_DEF_CraSsp,	
	&asn_DEF_DcmSsp,	
	&asn_DEF_LaSsp,	
	&asn_DEF_RaSsp,	
	&asn_DEF_EeSsp,	
	/* From module SecurityBaseDataTypes in asn/SecurityBaseDataTypes.asn */
	&asn_DEF_Uint3,	
	&asn_DEF_Uint8,	
	&asn_DEF_Uint16,	
	&asn_DEF_Uint32,	
	&asn_DEF_Uint64,	
	&asn_DEF_SequenceOfUint8,	
	&asn_DEF_SequenceOfUint16,	
	&asn_DEF_Opaque,	
	&asn_DEF_HashedId32,	
	&asn_DEF_HashedId10,	
	&asn_DEF_HashedId8,	
	&asn_DEF_HashedId4,	
	&asn_DEF_HashedId3,	
	&asn_DEF_SequenceOfHashedId3,	
	&asn_DEF_Time32,	
	&asn_DEF_Time64,	
	&asn_DEF_ValidityPeriod,	
	&asn_DEF_Duration,	
	&asn_DEF_GeographicRegion,	
	&asn_DEF_CircularRegion,	
	&asn_DEF_RectangularRegion,	
	&asn_DEF_SequenceOfRectangularRegion,	
	&asn_DEF_PolygonalRegion,	
	&asn_DEF_TwoDLocation,	
	&asn_DEF_IdentifiedRegion,	
	&asn_DEF_SequenceOfIdentifiedRegion,	
	&asn_DEF_CountryOnly,	
	&asn_DEF_CountryAndRegions,	
	&asn_DEF_CountryAndSubregions,	
	&asn_DEF_RegionAndSubregions,	
	&asn_DEF_SequenceOfRegionAndSubregions,	
	&asn_DEF_ThreeDLocation,	
	&asn_DEF_Latitude,	
	&asn_DEF_Longitude,	
	&asn_DEF_Elevation,	
	&asn_DEF_NinetyDegreeInt,	
	&asn_DEF_KnownLatitude,	
	&asn_DEF_UnknownLatitude,	
	&asn_DEF_OneEightyDegreeInt,	
	&asn_DEF_KnownLongitude,	
	&asn_DEF_UnknownLongitude,	
	&asn_DEF_ElevInt,	
	&asn_DEF_Signature,	
	&asn_DEF_EcdsaP256Signature,	
	&asn_DEF_EcsigP256Signature,	
	&asn_DEF_EcdsaP384Signature,	
	&asn_DEF_EccP256CurvePoint,	
	&asn_DEF_EccP384CurvePoint,	
	&asn_DEF_SymmAlgorithm,	
	&asn_DEF_HashAlgorithm,	
	&asn_DEF_EciesP256EncryptedKey,	
	&asn_DEF_EcencP256EncryptedKey,	
	&asn_DEF_EncryptionKey,	
	&asn_DEF_PublicEncryptionKey,	
	&asn_DEF_BasePublicEncryptionKey,	
	&asn_DEF_PublicVerificationKey,	
	&asn_DEF_SymmetricEncryptionKey,	
	&asn_DEF_AidSsp,	
	&asn_DEF_SequenceOfAidSsp,	
	&asn_DEF_Aid,	
	&asn_DEF_SequenceOfAid,	
	&asn_DEF_ServiceSpecificPermissions,	
	&asn_DEF_BitmapSsp,	
	&asn_DEF_SspValue,	
	&asn_DEF_SspBitmask,	
	&asn_DEF_AidSspRange,	
	&asn_DEF_SequenceOfAidSspRange,	
	&asn_DEF_SspRange,	
	&asn_DEF_BitmapSspRange,	
	&asn_DEF_SequenceOfOctetString,	
	&asn_DEF_SubjectAssurance,	
	&asn_DEF_CrlSeries,	
	&asn_DEF_IValue,	
	&asn_DEF_Hostname,	
	&asn_DEF_LinkageValue,	
	&asn_DEF_GroupLinkageValue,	
	&asn_DEF_LaId,	
	&asn_DEF_SecurityBaseDataTypes_LinkageSeed,	
	/* From module SecurityDataTypes in asn/SecurityDataTypes.asn */
	&asn_DEF_SignedDataPayload,	
	&asn_DEF_V2XSecData,	
	&asn_DEF_V2XSecContent,	
	&asn_DEF_SignedData,	
	&asn_DEF_SignerIdentifier,	
	&asn_DEF_ToBeSignedData,	
	&asn_DEF_HashedData,	
	&asn_DEF_HeaderInfo,	
	&asn_DEF_MissingCrlIdentifier,	
	&asn_DEF_PduFunctionalType,	
	&asn_DEF_EncryptedData,	
	&asn_DEF_RecipientInfo,	
	&asn_DEF_SequenceOfRecipientInfo,	
	&asn_DEF_PreSharedKeyRecipientInfo,	
	&asn_DEF_SymmRecipientInfo,	
	&asn_DEF_PKRecipientInfo,	
	&asn_DEF_EncryptedDataEncryptionKey,	
	&asn_DEF_SymmetricCiphertext,	
	&asn_DEF_One28BitCcmCiphertext,	
	&asn_DEF_Certificate,	
	&asn_DEF_SequenceOfCertificate,	
	&asn_DEF_CertificateBase,	
	&asn_DEF_CertificateType,	
	&asn_DEF_ExplicitCertificate,	
	&asn_DEF_Reserved,	
	&asn_DEF_IssuerIdentifier,	
	&asn_DEF_ToBeSignedCertificate,	
	&asn_DEF_CertificateId,	
	&asn_DEF_LinkageData,	
	&asn_DEF_EndEntityType,	
	&asn_DEF_AidGroupPermissions,	
	&asn_DEF_SequenceOfAidGroupPermissions,	
	&asn_DEF_SubjectPermissions,	
	&asn_DEF_VerificationKeyIndicator,	
	/* From module V2XSecData-Encrypted in asn/V2XSecData-Encrypted.asn */
	&asn_DEF_V2XSecData_EncryptedOpen,	
	&asn_DEF_ScmsPdu_Scoped,	
	&asn_DEF_ScopedCertificateRequest,	
	&asn_DEF_SignedCertificateRequest,	
	&asn_DEF_SignerSelf,	
	&asn_DEF_SignerSingleCert,	
	0
};

